import * as Phaser from 'phaser';
import { InimigoReino } from './InimigoReino';

/** Gnomo atirador: patrulha pouco, mira e lança uma noz à distância. */
export class ArqueiroReino extends Phaser.Physics.Arcade.Sprite implements InimigoReino {
    readonly colideComPlataformas=true;get corpoColisao():Phaser.Physics.Arcade.Sprite{return this;}derrotado=false;
    private readonly origemX:number;private direcao=-1;private vida=2;private estado:'patrulha'|'mirando'='patrulha';private miraAte=0;private proximoDisparo=0;
    constructor(cena:Phaser.Scene,x:number,y:number,private readonly alvo:Phaser.Physics.Arcade.Sprite,private readonly aoAcertar:()=>void){super(cena,x,y,'reino-gnomo-noz',0);cena.add.existing(this);cena.physics.add.existing(this);this.origemX=x;this.setScale(.17).setDepth(8);(this.body as Phaser.Physics.Arcade.Body).setSize(245,390).setOffset(125,330).setMaxVelocity(75,650);}
    atualizar():void {if(this.derrotado)return;const agora=this.scene.time.now,dx=this.alvo.x-this.x,mesmaAltura=Math.abs(this.alvo.y-this.y)<100,dentro=Math.abs(dx)<420;if(this.estado==='patrulha'&&dentro&&mesmaAltura&&agora>=this.proximoDisparo){this.estado='mirando';this.miraAte=agora+500;this.direcao=Math.sign(dx)||this.direcao;this.setVelocityX(0).setFrame(0);}else if(this.estado==='mirando'&&(!dentro||!mesmaAltura))this.cancelarMira(agora+450);else if(this.estado==='mirando'&&agora>=this.miraAte){this.setFrame(1);this.disparar();this.cancelarMira(agora+1750);}if(this.estado==='patrulha'){if(this.x<this.origemX-55)this.direcao=1;else if(this.x>this.origemX+55)this.direcao=-1;this.setVelocityX(this.direcao*28);}this.setFlipX(this.direcao>0);}
    atingir():boolean {if(this.derrotado)return false;if(--this.vida>0){this.setAlpha(.35);this.scene.time.delayedCall(120,()=>{if(this.active)this.setAlpha(1);});return false;}this.derrotar();return true;}
    derrotar():void {if(this.derrotado)return;this.derrotado=true;this.setVelocity(0,0).disableBody().setFrame(3);this.scene.tweens.add({targets:this,y:this.y+30,angle:80,alpha:0,scale:.08,duration:520,ease:'Back.In',onComplete:()=>this.destroy()});}
    private cancelarMira(proximo:number):void {this.estado='patrulha';this.proximoDisparo=proximo;this.scene.time.delayedCall(250,()=>{if(this.active&&!this.derrotado)this.setFrame(0);});}
    private disparar():void {if(!this.scene.textures.exists('noz-gnomo-reino')){const g=this.scene.make.graphics({x:0,y:0});g.fillStyle(0x8a5527).fillCircle(9,10,8).fillStyle(0x563319).fillRect(4,1,10,4).generateTexture('noz-gnomo-reino',18,18);g.destroy();}const dx=this.alvo.x-this.x,dy=this.alvo.y-this.y,distancia=Math.max(1,Math.hypot(dx,dy)),noz=this.scene.physics.add.sprite(this.x+Math.sign(dx)*35,this.y-15,'noz-gnomo-reino').setDepth(9),corpo=noz.body as Phaser.Physics.Arcade.Body;corpo.setAllowGravity(true).setGravityY(-500).setCircle(8);noz.setVelocity(dx/distancia*280,dy/distancia*180-90).setAngularVelocity(Math.sign(dx)*600);let encerrada=false;let sobreposicao!:Phaser.Physics.Arcade.Collider;const encerrar=(atingiu=false)=>{if(encerrada)return;encerrada=true;if(atingiu)this.aoAcertar();sobreposicao?.destroy();if(noz.active)noz.destroy();};sobreposicao=this.scene.physics.add.overlap(noz,this.alvo,()=>encerrar(true));this.scene.time.delayedCall(1600,()=>encerrar());}
}
