import * as Phaser from 'phaser';
import { REGIOES_REINO } from '../dados/mundoReinoPortas';
import { DISCIPLINA_DESAFIO, NOMES_DESAFIO, TIPOS_DESAFIO, type DificuldadeDesafio, type DisciplinaDesafio, type TipoDesafio } from '../sistemas/DesafiosReino';
import { progressoReino, type EstadoReino } from '../sistemas/ProgressoReino';

const FONTE='Arial Rounded MT Bold, Arial Black, Arial';
const ROTULO_DIFICULDADE:Record<DificuldadeDesafio,string>={easy:'FÁCIL',medium:'MÉDIO',hard:'DIFÍCIL'};

export class ConfiguracaoReino extends Phaser.Scene {
    private estado!:EstadoReino;
    private tela:'configuracao'|'fases'='configuracao';
    constructor(){super('ConfiguracaoReino');}
    init(dados?:{tela?:'configuracao'|'fases'}):void {this.tela=dados?.tela??'configuracao';}
    create():void {this.estado=progressoReino.carregar();this.cameras.main.setBackgroundColor(0x183f35);this.add.graphics().fillGradientStyle(0x1c5b4c,0x1c5b4c,0x102d2b,0x102d2b,1).fillRect(0,0,960,640);this.add.image(480,325,'reino-panorama').setDisplaySize(960,420).setAlpha(.16);this.add.rectangle(480,320,960,640,0x102c27,.35);if(this.tela==='fases')this.criarTelaFases();else this.criarTelaConfiguracao();}

    private criarTelaConfiguracao():void {
        this.titulo('PREPARE SUA JORNADA','Escolha os desafios e depois a fase');this.add.text(480,105,'DIFICULDADE GERAL',{fontFamily:FONTE,fontSize:'13px',fontStyle:'bold',color:'#d9f3e7'}).setOrigin(.5);
        (['easy','medium','hard'] as DificuldadeDesafio[]).forEach((difficulty,i)=>this.botao(326+i*154,137,138,42,ROTULO_DIFICULDADE[difficulty],this.estado.globalDifficulty===difficulty?0xc28c3d:0x477b6c,()=>{const challenges={...this.estado.challenges};for(const type of TIPOS_DESAFIO)challenges[type]={...challenges[type],difficulty};progressoReino.salvar({globalDifficulty:difficulty,challenges});this.scene.restart();}));
        this.cardDisciplina('portugues',480,222,0x6d68a8);this.cardDisciplina('matematica',480,316,0xb8793f);
        const inv=this.estado.invencivel;this.card(480,405,720,66,inv?0x4f9277:0x60756d);this.add.text(150,394,'🛡  MODO INVENCÍVEL',{fontFamily:FONTE,fontSize:'16px',fontStyle:'bold',color:'#ffffff'}).setOrigin(0,.5);this.add.text(150,418,'A criança não perde vidas nem é derrubada.',{fontFamily:FONTE,fontSize:'11px',color:'#dcefe7'}).setOrigin(0,.5);this.botao(765,405,100,42,inv?'LIGADO':'DESLIGADO',inv?0x62aa83:0x87948f,()=>{progressoReino.salvar({invencivel:!inv});this.scene.restart();});
        const fase=REGIOES_REINO[Phaser.Math.Clamp(this.estado.selectedLevel,0,this.estado.faseAtual)];this.card(480,488,720,70,fase.cor);this.add.text(150,476,`🏰  FASE ${this.estado.selectedLevel+1}`,{fontFamily:FONTE,fontSize:'12px',fontStyle:'bold',color:'#fff3bd'}).setOrigin(0,.5);this.add.text(150,501,fase.nome,{fontFamily:FONTE,fontSize:'17px',fontStyle:'bold',color:'#ffffff'}).setOrigin(0,.5);this.botao(740,488,150,44,'ESCOLHER  ›',0x557f9c,()=>this.scene.restart({tela:'fases'}));
        this.botao(480,573,300,56,'COMEÇAR JORNADA',0xc28c3d,()=>this.iniciar());this.botao(92,42,150,38,'‹ EDUCAPP',0x557f9c,()=>this.scene.start('EducApp'));
    }

    private cardDisciplina(disciplina:DisciplinaDesafio,x:number,y:number,cor:number):void {const tipos=TIPOS_DESAFIO.filter(type=>DISCIPLINA_DESAFIO[type]===disciplina),ativos=tipos.filter(type=>this.estado.challenges[type].enabled).length,nome=disciplina==='portugues'?'📚  PORTUGUÊS':'🔢  MATEMÁTICA';this.card(x,y,720,76,cor);this.add.text(150,y-11,nome,{fontFamily:FONTE,fontSize:'18px',fontStyle:'bold',color:'#ffffff'}).setOrigin(0,.5);this.add.text(150,y+16,`${ativos} de ${tipos.length} desafios ativos`,{fontFamily:FONTE,fontSize:'12px',color:'#f2f3df'}).setOrigin(0,.5);this.botao(740,y,150,44,'CONFIGURAR  ›',0x315f51,()=>this.abrirDisciplina(disciplina));}

    private abrirDisciplina(disciplina:DisciplinaDesafio):void {
        const overlay=this.add.container(480,320).setDepth(20),cor=disciplina==='portugues'?0x6d68a8:0xb8793f,tipos=TIPOS_DESAFIO.filter(type=>DISCIPLINA_DESAFIO[type]===disciplina);overlay.add([this.add.rectangle(0,0,960,640,0x102c27,.82).setInteractive(),this.add.graphics().fillStyle(0xfffdf3,1).fillRoundedRect(-365,-260,730,520,28).lineStyle(5,cor).strokeRoundedRect(-365,-260,730,520,28),this.add.text(0,-220,disciplina==='portugues'?'DESAFIOS DE PORTUGUÊS':'DESAFIOS DE MATEMÁTICA',{fontFamily:FONTE,fontSize:'24px',fontStyle:'bold',color:`#${cor.toString(16).padStart(6,'0')}`}).setOrigin(.5)]);tipos.forEach((type,i)=>this.linhaDesafio(overlay,type,-135+i*74,cor));
        if(disciplina==='matematica'){const faixa=this.estado.faixaSoma;overlay.add(this.add.text(-315,150,`AJUSTES AVANÇADOS  •  faixa numérica: ${faixa.minimo} a ${faixa.maximo}`,{fontFamily:FONTE,fontSize:'12px',fontStyle:'bold',color:'#526a61'}).setOrigin(0,.5));this.botaoNo(overlay,-190,185,105,36,'− MÍN',0x6c8178,()=>this.mudarFaixa(-1,0));this.botaoNo(overlay,-65,185,105,36,'+ MÍN',0x557f9c,()=>this.mudarFaixa(1,0));this.botaoNo(overlay,65,185,105,36,'− MÁX',0x6c8178,()=>this.mudarFaixa(0,-5));this.botaoNo(overlay,190,185,105,36,'+ MÁX',0x557f9c,()=>this.mudarFaixa(0,5));}
        this.botaoNo(overlay,0,disciplina==='matematica'?235:210,180,44,'CONCLUÍDO',0x4c9276,()=>overlay.destroy(true));
    }

    private linhaDesafio(pai:Phaser.GameObjects.Container,type:TipoDesafio,y:number,cor:number):void {const cfg=this.estado.challenges[type];pai.add([this.add.graphics().fillStyle(0x315f51,.07).fillRoundedRect(-325,y-28,650,56,14),this.add.text(-300,y,NOMES_DESAFIO[type],{fontFamily:FONTE,fontSize:'15px',fontStyle:'bold',color:'#315f51'}).setOrigin(0,.5)]);this.botaoNo(pai,145,y,96,38,cfg.enabled?'ATIVO':'DESLIG.',cfg.enabled?cor:0x929b97,()=>{const challenges={...this.estado.challenges,[type]:{...cfg,enabled:!cfg.enabled}};this.estado=progressoReino.salvar({challenges});pai.destroy(true);this.abrirDisciplina(DISCIPLINA_DESAFIO[type]);});this.botaoNo(pai,260,y,112,38,ROTULO_DIFICULDADE[cfg.difficulty],0x4f7569,()=>{const ordem:DificuldadeDesafio[]=['easy','medium','hard'],difficulty=ordem[(ordem.indexOf(cfg.difficulty)+1)%3],challenges={...this.estado.challenges,[type]:{...cfg,difficulty}};this.estado=progressoReino.salvar({challenges});pai.destroy(true);this.abrirDisciplina(DISCIPLINA_DESAFIO[type]);});}
    private mudarFaixa(deltaMin:number,deltaMax:number):void {const atual=this.estado.faixaSoma,minimo=Phaser.Math.Clamp(atual.minimo+deltaMin,0,atual.maximo-1),maximo=Phaser.Math.Clamp(atual.maximo+deltaMax,minimo+1,100);this.estado=progressoReino.salvar({faixaSoma:{minimo,maximo}});this.children.getAll().filter(obj=>((obj as Phaser.GameObjects.GameObject&{depth?:number}).depth??0)>=20).forEach(obj=>obj.destroy());this.abrirDisciplina('matematica');}

    private criarTelaFases():void {this.titulo('ESCOLHA A FASE','Sua configuração ficará guardada ao voltar');REGIOES_REINO.forEach((regiao,i)=>{const coluna=i%4,linha=Math.floor(i/4),x=150+coluna*220,y=225+linha*220,liberado=i<=this.estado.faseAtual,selecionado=i===this.estado.selectedLevel,card=this.add.container(x,y).setSize(192,174);card.add([this.add.graphics().fillStyle(liberado?regiao.cor:0x53635f,1).fillRoundedRect(-96,-87,192,174,20).lineStyle(selecionado?6:3,selecionado?0xffdc68:regiao.corDestaque,1).strokeRoundedRect(-96,-87,192,174,20),this.add.image(0,-25,`reino-fundo-${regiao.id}`).setDisplaySize(180,104).setAlpha(liberado?1:.25),this.add.text(0,48,`FASE ${i+1}`,{fontFamily:FONTE,fontSize:'11px',fontStyle:'bold',color:'#fff3bd'}).setOrigin(.5),this.add.text(0,69,regiao.nome,{fontFamily:FONTE,fontSize:'12px',fontStyle:'bold',color:'#ffffff',align:'center',wordWrap:{width:170}}).setOrigin(.5)]);if(!liberado){card.add(this.add.text(0,-25,'🔒',{fontFamily:FONTE,fontSize:'30px'}).setOrigin(.5));return;}card.setInteractive({useHandCursor:true}).on('pointerdown',()=>{progressoReino.salvar({selectedLevel:i});this.scene.restart({tela:'fases'});});});this.botao(240,585,195,48,'‹ CONFIGURAÇÃO',0x557f9c,()=>this.scene.restart({tela:'configuracao'}));this.botao(480,585,195,48,'JOGAR ESTA FASE',0xc28c3d,()=>this.iniciar());this.botao(720,585,195,48,'🐉 3 VOOS DO DRAGÃO',0x398f9d,()=>this.scene.start('VooDragaoReino'));}
    private iniciar():void {const atual=progressoReino.carregar();if(!TIPOS_DESAFIO.some(type=>atual.challenges[type].enabled)){this.aviso('Ative pelo menos um desafio para começar.');return;}const fase=Phaser.Math.Clamp(atual.selectedLevel,0,atual.faseAtual),reiniciar=atual.checkpointLevel!==fase||atual.checkpointX>=6000,seed=reiniciar?Date.now()>>>0:atual.levelSeed;progressoReino.salvar({selectedLevel:fase,checkpointLevel:fase,checkpointX:reiniciar?120:atual.checkpointX,portasAbertas:reiniciar?0:atual.portasAbertas,levelSeed:seed,aventura:reiniciar?{fase,seed,eventos:[]}:atual.aventura});this.scene.start('ReinoDasPortas',{fase});}
    private aviso(texto:string):void {const t=this.add.text(480,540,texto,{fontFamily:FONTE,fontSize:'15px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#9b5146',padding:{x:18,y:10}}).setOrigin(.5).setDepth(40);this.time.delayedCall(2200,()=>t.destroy());}
    private titulo(titulo:string,subtitulo:string):void {this.add.text(480,42,titulo,{fontFamily:FONTE,fontSize:'30px',fontStyle:'bold',color:'#fff7d1',stroke:'#285c4b',strokeThickness:7}).setOrigin(.5);this.add.text(480,75,subtitulo,{fontFamily:FONTE,fontSize:'14px',color:'#d9f3e7'}).setOrigin(.5);}
    private card(x:number,y:number,w:number,h:number,cor:number):void {this.add.graphics().fillStyle(0x102e29,.22).fillRoundedRect(x-w/2,y-h/2+5,w,h,18).fillStyle(cor,.94).fillRoundedRect(x-w/2,y-h/2,w,h,18).lineStyle(2,0xffffff,.35).strokeRoundedRect(x-w/2,y-h/2,w,h,18);}
    private botao(x:number,y:number,w:number,h:number,texto:string,cor:number,acao:()=>void):Phaser.GameObjects.Container {const c=this.add.container(x,y);this.desenharBotao(c,w,h,texto,cor,acao);return c;}
    private botaoNo(pai:Phaser.GameObjects.Container,x:number,y:number,w:number,h:number,texto:string,cor:number,acao:()=>void):Phaser.GameObjects.Container {const c=this.add.container(x,y);this.desenharBotao(c,w,h,texto,cor,acao);pai.add(c);return c;}
    private desenharBotao(c:Phaser.GameObjects.Container,w:number,h:number,texto:string,cor:number,acao:()=>void):void {c.setSize(w,h).setInteractive({useHandCursor:true});c.add([this.add.graphics().fillStyle(cor,1).fillRoundedRect(-w/2,-h/2,w,h,h/2).lineStyle(2,0xffffff,.45).strokeRoundedRect(-w/2,-h/2,w,h,h/2),this.add.text(0,0,texto,{fontFamily:FONTE,fontSize:'12px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5)]);c.on('pointerdown',acao).on('pointerover',()=>c.setScale(1.03)).on('pointerout',()=>c.setScale(1));}
}
