import * as Phaser from 'phaser';
import { servicoVoz } from '../../services/ServicoVoz';
import { CASO_LAPIS_DOURADO, AmbienteDetetive, IdSuspeito, PistaDetetive, SuspeitoDetetive } from '../dados/casoLapisDourado';
import { DetetiveJogador } from '../entidades/DetetiveJogador';
import { audioJogo } from '../sistemas/SistemaAudio';
import { confirmarSaidaParaEducApp } from '../sistemas/ConfirmacaoSaida';

interface Interacao {x:number;y:number;rotulo:string;executar:()=>void}
type Marcacao='neutro'|'descartado'|'suspeito';
const NOMES_AMBIENTE:Record<AmbienteDetetive,string>={sala:'SALA DE AULA',biblioteca:'BIBLIOTECA',patio:'PÁTIO',refeitorio:'REFEITÓRIO'};
const FRAME_AMBIENTE:Record<AmbienteDetetive,number>={sala:0,biblioteca:1,patio:2,refeitorio:3};

export class DetetiveMirim extends Phaser.Scene {
    private jogador!:DetetiveJogador;private ambiente:AmbienteDetetive='sala';private conteudo!:Phaser.GameObjects.Container;
    private cursores!:Phaser.Types.Input.Keyboard.CursorKeys;private teclas!:Record<string,Phaser.Input.Keyboard.Key>;
    private touch={esquerda:false,direita:false,cima:false,baixo:false};private bloqueado=true;private trocando=false;
    private interacoes:Interacao[]=[];private proxima?:Interacao;private botaoInteragir!:Phaser.GameObjects.Container;private textoInteragir!:Phaser.GameObjects.Text;
    private pistas=new Set<string>();private textoPistas!:Phaser.GameObjects.Text;private resolver?:Phaser.GameObjects.Container;
    private modal?:Phaser.GameObjects.Container;private marcacoes:Record<IdSuspeito,Marcacao>={coelho:'neutro',gato:'neutro',pato:'neutro',sapo:'neutro'};

    constructor(){super('DetetiveMirim');}
    create():void {
        this.ambiente='sala';this.pistas.clear();this.bloqueado=true;this.cameras.main.setBackgroundColor(0xe9ddbd);this.criarAnimacoes();
        this.conteudo=this.add.container(0,0);this.jogador=new DetetiveJogador(this,480,500);
        this.cursores=this.input.keyboard!.createCursorKeys();this.teclas=this.input.keyboard!.addKeys('W,A,S,D,E,SPACE') as Record<string,Phaser.Input.Keyboard.Key>;this.input.keyboard!.on('keydown-E',()=>this.interagir());
        this.criarHUD();this.criarControles();this.renderizarAmbiente();this.mostrarIntroducao();
        audioJogo.iniciarMusicaDetetive();this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>{audioJogo.pararMusicaDetetive();servicoVoz.parar();});
    }
    update():void {
        if(this.bloqueado)return;const dx=(this.touch.direita||this.cursores.right.isDown||this.teclas.D.isDown?1:0)-(this.touch.esquerda||this.cursores.left.isDown||this.teclas.A.isDown?1:0),dy=(this.touch.baixo||this.cursores.down.isDown||this.teclas.S.isDown?1:0)-(this.touch.cima||this.cursores.up.isDown||this.teclas.W.isDown?1:0);
        this.jogador.mover(dx,dy);this.verificarTransicao(dx,dy);this.atualizarInteracao();
    }
    private criarAnimacoes():void {
        const criar=(key:string,frames:number[])=>{if(!this.anims.exists(key))this.anims.create({key,frames:this.anims.generateFrameNumbers('detetive-jogador',{frames}),frameRate:7,repeat:-1});};criar('detetive-baixo',[0,1,2]);criar('detetive-cima',[3,4,5]);criar('detetive-lado',[6,7,8,9,10,11]);
    }
    private renderizarAmbiente():void {
        this.conteudo.removeAll(true);this.interacoes=[];this.conteudo.add(this.add.image(480,320,'detetive-escola',FRAME_AMBIENTE[this.ambiente]).setDisplaySize(960,640).setDepth(0));
        this.conteudo.add(this.add.rectangle(480,91,300,39,0x234f49,.82).setStrokeStyle(2,0xffffff,.55).setDepth(2));this.conteudo.add(this.add.text(480,91,NOMES_AMBIENTE[this.ambiente],{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'17px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5).setDepth(3));
        this.criarSetasSaida();CASO_LAPIS_DOURADO.suspeitos.filter(s=>s.ambiente===this.ambiente).forEach(s=>this.criarNPC(s));CASO_LAPIS_DOURADO.pistas.filter(p=>p.ambiente===this.ambiente&&p.tipo==='objeto').forEach(p=>this.criarObjetoPista(p));
    }
    private criarSetasSaida():void {
        const saidas:Partial<Record<'esquerda'|'direita'|'cima'|'baixo',AmbienteDetetive>>=this.ambiente==='sala'?{direita:'biblioteca',baixo:'patio'}:this.ambiente==='biblioteca'?{esquerda:'sala',baixo:'refeitorio'}:this.ambiente==='patio'?{cima:'sala',direita:'refeitorio'}:{cima:'biblioteca',esquerda:'patio'};
        Object.keys(saidas).forEach(d=>{const dir=d as keyof typeof saidas,pos={esquerda:[22,340,'◀'],direita:[938,340,'▶'],cima:[480,110,'▲'],baixo:[480,612,'▼']}[dir] as [number,number,string];this.conteudo.add(this.add.text(pos[0],pos[1],pos[2],{fontFamily:'Arial',fontSize:'25px',color:'#ffffff',backgroundColor:'#347568',padding:{x:7,y:4}}).setOrigin(.5).setDepth(5).setAlpha(.78));});
    }
    private criarNPC(s:SuspeitoDetetive):void {
        const pos:Record<IdSuspeito,[number,number]>={gato:[760,250],coelho:[735,470],pato:[265,250],sapo:[720,420]},[x,y]=pos[s.id],frame=CASO_LAPIS_DOURADO.suspeitos.findIndex(v=>v.id===s.id);const npc=this.add.image(x,y,'detetive-suspeitos',frame).setDisplaySize(122,162).setDepth(7);this.conteudo.add(npc);const fala=this.add.image(x+45,y-78,'detetive-objetos',5).setDisplaySize(37,37).setDepth(8);this.conteudo.add(fala);this.tweens.add({targets:fala,y:y-84,yoyo:true,repeat:-1,duration:700});this.interacoes.push({x,y,rotulo:'💬 CONVERSAR',executar:()=>this.dialogar(s)});
    }
    private criarObjetoPista(p:PistaDetetive):void {
        const desenho=p.fonte==='desenho',x=desenho?330:610,y=desenho?430:245,frame=desenho?2:1;const obj=this.add.image(x,y,'detetive-objetos',frame).setDisplaySize(desenho?70:54,desenho?70:72).setDepth(6);this.conteudo.add(obj);if(!this.pistas.has(p.id)){const brilho=this.add.image(x+28,y-28,'detetive-objetos',6).setDisplaySize(34,34).setDepth(8);this.conteudo.add(brilho);this.tweens.add({targets:brilho,scale:1.25,alpha:.45,yoyo:true,repeat:-1,duration:600});}this.interacoes.push({x,y,rotulo:'🔍 INVESTIGAR',executar:()=>this.investigar(p)});
    }
    private verificarTransicao(dx:number,dy:number):void {
        if(this.trocando)return;let destino:AmbienteDetetive|undefined,px=this.jogador.x,py=this.jogador.y;if(dx>0&&px>=916)destino=this.ambiente==='sala'?'biblioteca':this.ambiente==='patio'?'refeitorio':undefined;if(dx<0&&px<=44)destino=this.ambiente==='biblioteca'?'sala':this.ambiente==='refeitorio'?'patio':undefined;if(dy>0&&py>=582)destino=this.ambiente==='sala'?'patio':this.ambiente==='biblioteca'?'refeitorio':undefined;if(dy<0&&py<=108)destino=this.ambiente==='patio'?'sala':this.ambiente==='refeitorio'?'biblioteca':undefined;if(!destino)return;this.trocando=true;this.cameras.main.fadeOut(120,255,255,255,(_c:Phaser.Cameras.Scene2D.Camera,p:number)=>{if(p!==1)return;this.ambiente=destino!;this.renderizarAmbiente();this.jogador.setPosition(dx>0?65:dx<0?895:this.jogador.x,dy>0?130:dy<0?555:this.jogador.y).setDepth(12);this.cameras.main.fadeIn(140,255,255,255);this.time.delayedCall(180,()=>this.trocando=false);});
    }
    private atualizarInteracao():void {this.proxima=this.interacoes.reduce<Interacao|undefined>((melhor,i)=>{const d=Phaser.Math.Distance.Between(this.jogador.x,this.jogador.y,i.x,i.y);return d<135&&(!melhor||d<Phaser.Math.Distance.Between(this.jogador.x,this.jogador.y,melhor.x,melhor.y))?i:melhor;},undefined);this.botaoInteragir.setVisible(Boolean(this.proxima));if(this.proxima)this.textoInteragir.setText(this.proxima.rotulo);}
    private interagir():void {if(!this.bloqueado)this.proxima?.executar();}
    private dialogar(s:SuspeitoDetetive):void {audioJogo.efeito('dialogo');const pista=CASO_LAPIS_DOURADO.pistas.find(p=>p.tipo==='npc'&&p.fonte===s.id);this.abrirDialogo(s.nome,s.dialogo,()=>{if(pista)this.registrarPista(pista);});}
    private investigar(p:PistaDetetive):void {if(this.pistas.has(p.id)){this.abrirDialogo('ANOTAÇÃO',p.texto);return;}this.registrarPista(p);this.abrirDialogo('NOVA PISTA!',p.texto);}
    private registrarPista(p:PistaDetetive):void {if(this.pistas.has(p.id))return;this.pistas.add(p.id);audioJogo.efeito('pista');this.textoPistas.setText(`🔍  PISTAS: ${this.pistas.size}/4`);this.criarCelebracao();if(this.pistas.size>=3&&!this.resolver)this.criarBotaoResolver();this.renderizarAmbiente();}
    private abrirDialogo(titulo:string,texto:string,aoFechar?:()=>void):void {
        if(this.modal)return;this.bloqueado=true;const c=this.criarBaseModal(480,390,700,250);this.modal=c;c.add([this.add.text(-305,-80,titulo,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'18px',fontStyle:'bold',color:'#34695f'}).setOrigin(0,.5),this.add.text(-305,-20,texto,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'20px',color:'#3f544d',wordWrap:{width:600},lineSpacing:7}).setOrigin(0,.5)]);const ouvir=this.botao(-230,76,110,42,'🔊 OUVIR',0x548aa0),ok=this.botao(215,76,130,42,'ENTENDI',0x429272);c.add([ouvir,ok]);ouvir.on('pointerdown',()=>servicoVoz.falar(texto,{obrigatoria:true}));ok.on('pointerdown',()=>{c.destroy(true);this.modal=undefined;this.bloqueado=false;aoFechar?.();});
    }
    private criarHUD():void {
        const hud=this.add.container(0,0).setDepth(40);hud.add(this.add.rectangle(480,34,930,56,0x173e38,.82).setStrokeStyle(2,0xffffff,.3));this.textoPistas=this.add.text(45,34,'🔍  PISTAS: 0/4',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',fontStyle:'bold',color:'#ffffff'}).setOrigin(0,.5);hud.add(this.textoPistas);const caderno=this.botao(680,34,150,42,'📒 CADERNO',0x4f836e),sair=this.botao(860,34,130,42,'‹ EDUCAPP',0x55778a);hud.add([caderno,sair]);caderno.on('pointerdown',()=>this.abrirCaderno());sair.on('pointerdown',()=>confirmarSaidaParaEducApp(this,{aoAbrir:()=>this.bloqueado=true,aoCancelar:()=>this.bloqueado=false}));
    }
    private criarControles():void {
        const press=(x:number,y:number,label:string,chave:keyof typeof this.touch)=>{const c=this.add.container(x,y).setDepth(45).setSize(64,64).setInteractive({useHandCursor:true});c.add([this.add.circle(0,3,30,0x173e38,.25),this.add.circle(0,0,30,0x36796b,.7).setStrokeStyle(2,0xffffff,.6),this.add.text(0,0,label,{fontFamily:'Arial',fontSize:'22px',color:'#ffffff'}).setOrigin(.5)]);const on=()=>{this.touch[chave]=true;c.setScale(.92);},off=()=>{this.touch[chave]=false;c.setScale(1);};c.on('pointerdown',on).on('pointerup',off).on('pointerout',off);};press(75,545,'◀','esquerda');press(145,545,'▶','direita');press(110,475,'▲','cima');press(110,605,'▼','baixo');this.botaoInteragir=this.botao(800,555,230,58,'💬 INTERAGIR',0xbd7b3f).setDepth(45).setVisible(false);this.textoInteragir=this.botaoInteragir.getData('texto') as Phaser.GameObjects.Text;this.botaoInteragir.on('pointerdown',()=>this.interagir());
    }
    private mostrarIntroducao():void {const c=this.criarBaseModal(480,320,710,380);this.modal=c;c.add([this.add.image(-250,-85,'detetive-objetos',3).setDisplaySize(130,130),this.add.text(70,-120,CASO_LAPIS_DOURADO.titulo,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'25px',fontStyle:'bold',color:'#315f56',align:'center',wordWrap:{width:470}}).setOrigin(.5),this.add.text(70,-30,CASO_LAPIS_DOURADO.introducao,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'19px',color:'#536a62',align:'center',wordWrap:{width:430},lineSpacing:7}).setOrigin(.5)]);const comecar=this.botao(70,105,220,55,'COMEÇAR  🔍',0x3d9271);c.add(comecar);comecar.on('pointerdown',()=>{c.destroy(true);this.modal=undefined;this.bloqueado=false;});}
    private abrirCaderno():void {if(this.modal)return;audioJogo.efeito('caderno');this.bloqueado=true;const c=this.criarBaseModal(480,330,850,540);this.modal=c;const titulo=this.add.text(0,-225,'📒  CADERNO DO DETETIVE',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'24px',fontStyle:'bold',color:'#315f56'}).setOrigin(.5),area=this.add.container(0,10);c.add([titulo,area]);const mostrarPistas=()=>{area.removeAll(true);const lista=this.pistas.size?[...this.pistas].map(id=>`✓ ${CASO_LAPIS_DOURADO.pistas.find(p=>p.id===id)!.titulo}`).join('\n\n'):'Nenhuma pista encontrada ainda.';area.add(this.add.text(-355,-135,lista,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'17px',color:'#40584f',lineSpacing:6,wordWrap:{width:710}}));};const mostrarSuspeitos=()=>{area.removeAll(true);CASO_LAPIS_DOURADO.suspeitos.forEach((s,i)=>this.criarCardSuspeito(area,s,-270+i*180,0));};const pistas=this.botao(-110,-178,180,40,'PISTAS',0x4c8d72),suspeitos=this.botao(110,-178,180,40,'SUSPEITOS',0x657fa0),fechar=this.botao(0,225,160,42,'FECHAR',0x7b817e);c.add([pistas,suspeitos,fechar]);pistas.on('pointerdown',mostrarPistas);suspeitos.on('pointerdown',mostrarSuspeitos);fechar.on('pointerdown',()=>{c.destroy(true);this.modal=undefined;this.bloqueado=false;});mostrarPistas();}
    private criarCardSuspeito(area:Phaser.GameObjects.Container,s:SuspeitoDetetive,x:number,y:number):void {const frame=CASO_LAPIS_DOURADO.suspeitos.indexOf(s),card=this.add.container(x,y),bg=this.add.graphics().fillStyle(0xf4f0df,1).fillRoundedRect(-78,-125,156,250,19).lineStyle(3,0x78968a,.5).strokeRoundedRect(-78,-125,156,250,19),img=this.add.image(0,-62,'detetive-suspeitos',frame).setDisplaySize(86,105),info=this.add.text(0,20,`${s.nome}\nMochila ${s.mochila}\n${s.chapeu?'Usa chapéu':'Sem chapéu'}`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',color:'#40584f',align:'center',lineSpacing:4}).setOrigin(.5),marcar=this.botao(0,90,132,36,'SEM MARCA',0x75827d);card.add([bg,img,info,marcar]);area.add(card);const atualizar=()=>{const estado=this.marcacoes[s.id];(marcar.getData('texto') as Phaser.GameObjects.Text).setText(estado==='neutro'?'SEM MARCA':estado==='descartado'?'❌ DESCARTADO':'⭐ SUSPEITO');};marcar.on('pointerdown',()=>{this.marcacoes[s.id]=this.marcacoes[s.id]==='neutro'?'descartado':this.marcacoes[s.id]==='descartado'?'suspeito':'neutro';atualizar();});atualizar();}
    private criarBotaoResolver():void {this.resolver=this.botao(475,34,185,42,'🔎 RESOLVER O CASO',0xb17439).setDepth(45);this.resolver.on('pointerdown',()=>this.abrirDeducao());this.tweens.add({targets:this.resolver,scale:1.05,yoyo:true,repeat:3,duration:220});}
    private abrirDeducao():void {if(this.modal)return;this.bloqueado=true;const c=this.criarBaseModal(480,330,850,520);this.modal=c;c.add(this.add.text(0,-205,'QUEM FICOU COM O LÁPIS?',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'26px',fontStyle:'bold',color:'#315f56'}).setOrigin(.5));CASO_LAPIS_DOURADO.suspeitos.forEach((s,i)=>{const x=-285+i*190,b=this.add.container(x,15).setSize(160,250).setInteractive({useHandCursor:true}),g=this.add.graphics().fillStyle(0xf7f2df,1).fillRoundedRect(-76,-120,152,240,20).lineStyle(3,0xd1ad61,.65).strokeRoundedRect(-76,-120,152,240,20),img=this.add.image(0,-38,'detetive-suspeitos',i).setDisplaySize(120,150),nome=this.add.text(0,82,s.nome,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',fontStyle:'bold',color:'#40584f'}).setOrigin(.5);b.add([g,img,nome]);c.add(b);b.on('pointerdown',()=>this.escolherCulpado(s.id,c));});const voltar=this.botao(0,205,180,40,'VOLTAR',0x71807a);c.add(voltar);voltar.on('pointerdown',()=>{c.destroy(true);this.modal=undefined;this.bloqueado=false;});}
    private escolherCulpado(id:IdSuspeito,c:Phaser.GameObjects.Container):void {if(id!==CASO_LAPIS_DOURADO.culpado){audioJogo.efeito('erro');const aviso=this.add.text(0,168,'Essa pista ainda não combina. Vamos pensar outra vez?',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'14px',color:'#a05248',backgroundColor:'#fff1e9',padding:{x:15,y:8}}).setOrigin(.5);c.add(aviso);this.time.delayedCall(1800,()=>aviso.destroy());return;}c.destroy(true);this.modal=undefined;this.mostrarFinal();}
    private mostrarFinal():void {audioJogo.efeito('caso');this.bloqueado=true;const c=this.criarBaseModal(480,320,790,480);this.modal=c;c.add([this.add.image(-260,-20,'detetive-suspeitos',0).setDisplaySize(190,240),this.add.image(260,45,'detetive-objetos',0).setDisplaySize(80,110),this.add.text(75,-155,'CASO RESOLVIDO!',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'31px',fontStyle:'bold',color:'#34805f'}).setOrigin(.5),this.add.text(75,-45,CASO_LAPIS_DOURADO.solucao,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'19px',color:'#40584f',align:'center',wordWrap:{width:420},lineSpacing:7}).setOrigin(.5)]);const ouvir=this.botao(-10,125,125,44,'🔊 OUVIR',0x568ca0),menu=this.botao(155,125,150,44,'EDUCAPP',0x478d6d);c.add([ouvir,menu]);ouvir.on('pointerdown',()=>servicoVoz.falar(CASO_LAPIS_DOURADO.solucao,{obrigatoria:true}));menu.on('pointerdown',()=>confirmarSaidaParaEducApp(this));this.criarCelebracao(36);}
    private criarBaseModal(x:number,y:number,w:number,h:number):Phaser.GameObjects.Container {const c=this.add.container(x,y).setDepth(100);c.add([this.add.rectangle(0,0,960,640,0x193a34,.55),this.add.graphics().fillStyle(0x183e36,.2).fillRoundedRect(-w/2,-h/2+9,w,h,28).fillStyle(0xfffdf4,1).fillRoundedRect(-w/2,-h/2,w,h,28).lineStyle(4,0xd2ae62,.9).strokeRoundedRect(-w/2,-h/2,w,h,28)]);c.setAlpha(0).setScale(.94);this.tweens.add({targets:c,alpha:1,scale:1,duration:180,ease:'Back.Out'});return c;}
    private criarCelebracao(q=16):void {for(let i=0;i<q;i++){const p=this.add.image(Phaser.Math.Between(220,740),Phaser.Math.Between(120,450),'detetive-objetos',6).setDisplaySize(Phaser.Math.Between(15,30),Phaser.Math.Between(15,30)).setDepth(130);this.tweens.add({targets:p,y:p.y-Phaser.Math.Between(50,130),x:p.x+Phaser.Math.Between(-55,55),alpha:0,angle:180,duration:Phaser.Math.Between(500,950),onComplete:()=>p.destroy()});}}
    private botao(x:number,y:number,w:number,h:number,texto:string,cor:number):Phaser.GameObjects.Container {const c=this.add.container(x,y).setSize(w,h).setInteractive({useHandCursor:true}),g=this.add.graphics().fillStyle(0x244b42,.18).fillRoundedRect(-w/2,-h/2+4,w,h,h/2).fillStyle(cor,1).fillRoundedRect(-w/2,-h/2,w,h,h/2),t=this.add.text(0,0,texto,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'12px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5);c.add([g,t]);c.setData('texto',t);return c;}
}
