import * as Phaser from 'phaser';
import { servicoVoz } from '../../services/ServicoVoz';
import { criarDesafio, CategoriaDesafio, DesafioPorta } from '../dados/configuracaoReinoPortas';
import { CavaleiroReino } from '../entidades/CavaleiroReino';
import { InimigoReino } from '../entidades/InimigoReino';
import { SlimeReino } from '../entidades/SlimeReino';
import { MorcegoReino } from '../entidades/MorcegoReino';
import { GoblinReino } from '../entidades/GoblinReino';
import { ArqueiroReino } from '../entidades/ArqueiroReino';
import { PlantaReino } from '../entidades/PlantaReino';
import { audioJogo } from '../sistemas/SistemaAudio';
import { confirmarSaidaParaEducApp } from '../sistemas/ConfirmacaoSaida';
import { EQUIPAMENTOS_REINO, MISSOES_REINO, POSICOES_INIMIGOS, REGIOES_REINO } from '../dados/mundoReinoPortas';
import { progressoReino } from '../sistemas/ProgressoReino';

interface PortaReino {x:number;categoria:CategoriaDesafio;sprite:Phaser.Physics.Arcade.Sprite;aberta:boolean}
const CORES_ROUPAS:Record<string,number>={'armadura-verde':0x79c879,'armadura-azul':0x75bdf0,'capa-mago':0xc28be8};

export class ReinoDasPortas extends Phaser.Scene {
    private readonly larguraMundo=6200;private faseAtual=0;
    private cavaleiro!:CavaleiroReino;private plataformas!:Phaser.Physics.Arcade.StaticGroup;
    private inimigos:InimigoReino[]=[];private portas:PortaReino[]=[];private moedas=0;private vidas=3;private checkpoint=120;
    private cursores!:Phaser.Types.Input.Keyboard.CursorKeys;private teclas!:Record<string,Phaser.Input.Keyboard.Key>;
    private esquerdaTouch=false;private direitaTouch=false;private bloqueado=false;private modal?:Phaser.GameObjects.Container;
    private ataquePendente=false;
    private zonasDesafio:Phaser.GameObjects.Zone[]=[];
    private zonasPainel:Phaser.GameObjects.Zone[]=[];
    private textoMoedas!:Phaser.GameObjects.Text;private coracoes!:Phaser.GameObjects.Image[];private portaAtual?:PortaReino;
    private textoRegiao!:Phaser.GameObjects.Text;private barraProgresso!:Phaser.GameObjects.Graphics;private regiaoAtual='';private defesaTouch=false;
    private deslocamentoCamera=0;
    private errosPorta=0;private comboPortas=0;private primeiraTentativa=true;private pausado=false;
    private gamepadPuloAntes=false;private gamepadAtaqueAntes=false;private avisoPortalEm=0;
    private filtroEntardecer!:Phaser.GameObjects.Rectangle;

    constructor(){super('ReinoDasPortas');}
    init(dados?:{fase?:number}):void {this.faseAtual=Phaser.Math.Clamp(dados?.fase??progressoReino.carregar().faseAtual,0,REGIOES_REINO.length-1);}
    create():void {
        this.inimigos=[];this.portas=[];this.zonasDesafio=[];this.zonasPainel=[];this.moedas=0;this.vidas=3;this.checkpoint=120;this.portaAtual=undefined;this.modal=undefined;this.bloqueado=false;this.pausado=false;this.esquerdaTouch=false;this.direitaTouch=false;this.defesaTouch=false;this.ataquePendente=false;this.comboPortas=0;this.regiaoAtual='';
        this.physics.world.gravity.y=920;this.physics.world.setBounds(0,0,this.larguraMundo,640);
        this.criarCenario();this.criarAnimacoes();this.criarPlataformas();this.filtroEntardecer=this.add.rectangle(480,320,960,640,0x764873,0).setScrollFactor(0).setDepth(20);
        this.cavaleiro=new CavaleiroReino(this,120,450);this.physics.add.collider(this.cavaleiro,this.plataformas);
        this.criarMoedas();this.criarSlimes();this.criarPortas();this.criarSegredos();this.criarComposicoesCenario();this.criarAmbiente();this.criarPortal();this.criarHUD();this.criarControlesTouch();
        this.cameras.main.setBounds(0,0,this.larguraMundo,640).startFollow(this.cavaleiro,true,.09,.09,0,45);
        const salvo=progressoReino.carregar(),checkpointValido=salvo.faseAtual===this.faseAtual&&salvo.checkpointX<this.larguraMundo-300;this.checkpoint=checkpointValido?salvo.checkpointX:120;this.cavaleiro.x=this.checkpoint;this.cavaleiro.aplicarRoupa(salvo.skin);this.portas.forEach((p,i)=>{if(checkpointValido&&i<salvo.portasAbertas){p.aberta=true;p.sprite.setFrame(1);p.sprite.disableBody();}});this.vidas=salvo.dificuldade==='tranquilo'?4:salvo.dificuldade==='aventura'?2:3;this.atualizarVidas();
        this.cursores=this.input.keyboard!.createCursorKeys();this.teclas=this.input.keyboard!.addKeys('A,D,S,Z,X,J,P,SHIFT,SPACE') as Record<string,Phaser.Input.Keyboard.Key>;
        this.input.keyboard!.on('keydown-Z',()=>this.atacar());this.input.keyboard!.on('keydown-J',()=>this.atacar());
        this.input.keyboard!.on('keydown-SHIFT',()=>this.dash());this.input.keyboard!.on('keydown-P',()=>this.alternarPausa());
        this.input.keyboard!.on('keyup-UP',()=>this.cavaleiro.encerrarPulo());this.input.keyboard!.on('keyup-SPACE',()=>this.cavaleiro.encerrarPulo());
        this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>{servicoVoz.parar();audioJogo.pararMusicaReino();});
        audioJogo.iniciarMusicaReino();this.mostrarDicaInicial();
    }
    update():void {
        if(!this.cavaleiro||this.bloqueado)return;
        const esquerda=this.esquerdaTouch||this.cursores.left.isDown||this.teclas.A.isDown,direita=this.direitaTouch||this.cursores.right.isDown||this.teclas.D.isDown;
        const pad=this.input.gamepad?.getPad(0),eixo=pad?.axes[0]?.getValue()??0,defendendo=this.defesaTouch||this.teclas.X.isDown||this.teclas.S.isDown||this.cursores.down.isDown||(pad?.L1??0)>0;this.cavaleiro.agachar(false,false);this.cavaleiro.defender(defendendo);this.cavaleiro.mover(this.cavaleiro.defendendo?0:Math.abs(eixo)>.25?Math.sign(eixo):esquerda?-1:direita?1:0,false);
        const gpPulo=!!pad?.buttons[0]?.pressed,gpAtaque=!!pad?.buttons[2]?.pressed;if(gpPulo&&!this.gamepadPuloAntes)this.pular();if(gpAtaque&&!this.gamepadAtaqueAntes)this.atacar();this.gamepadPuloAntes=gpPulo;this.gamepadAtaqueAntes=gpAtaque;
        if(Phaser.Input.Keyboard.JustDown(this.cursores.up)||Phaser.Input.Keyboard.JustDown(this.cursores.space)||Phaser.Input.Keyboard.JustDown(this.teclas.SPACE))this.pular();
        this.cavaleiro.sustentarPulo(this.cursores.up.isDown||this.cursores.space.isDown||this.teclas.SPACE.isDown||gpPulo);
        this.inimigos.forEach(inimigo=>inimigo.atualizar());this.verificarPortas();this.atualizarRegiao();const inicioEntardecer=this.larguraMundo*.65,extensaoEntardecer=this.larguraMundo*.32;this.filtroEntardecer.setAlpha(Phaser.Math.Clamp((this.cavaleiro.x-inicioEntardecer)/extensaoEntardecer,0,1)*.16);this.deslocamentoCamera=Phaser.Math.Linear(this.deslocamentoCamera,-this.cavaleiro.olhando*72,.045);this.cameras.main.setFollowOffset(this.deslocamentoCamera,45);if(this.cavaleiro.y>620)this.reposicionar();
    }
    private criarCenario():void {
        const tema=REGIOES_REINO[this.faseAtual];
        if(this.faseAtual===0)this.add.image(480,320,'reino-bosque').setDisplaySize(960,640).setScrollFactor(0).setDepth(-20);
        else this.add.image(480,320,'reino-panorama').setDisplaySize(1600,640).setScrollFactor(0).setDepth(-20);
        this.add.rectangle(480,320,960,640,tema.cor,.1).setScrollFactor(0).setDepth(-19);
        this.add.text(180,355,tema.nome.toUpperCase(),{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'20px',fontStyle:'bold',color:'#ffffff',stroke:'#31554b',strokeThickness:5}).setOrigin(.5).setScrollFactor(0).setDepth(2);
    }
    private criarAnimacoes():void {
        if(!this.anims.exists('reino-idle'))this.anims.create({key:'reino-idle',frames:[{key:'reino-cavaleiro',frame:0}],frameRate:1,repeat:-1});
        if(!this.anims.exists('reino-correr'))this.anims.create({key:'reino-correr',frames:this.anims.generateFrameNumbers('reino-cavaleiro',{frames:[2,3,4]}),frameRate:9,repeat:-1});
        if(!this.anims.exists('reino-atacar'))this.anims.create({key:'reino-atacar',frames:this.anims.generateFrameNumbers('reino-cavaleiro',{frames:[7,8,7]}),frameRate:14,repeat:0});
        if(!this.anims.exists('reino-slime-mover'))this.anims.create({key:'reino-slime-mover',frames:this.anims.generateFrameNumbers('reino-slime',{frames:[0,1,2]}),frameRate:5,repeat:-1});
    }
    private criarPlataformas():void {
        this.plataformas=this.physics.add.staticGroup();
        const decorarPlataforma=(x:number,y:number,w:number,h:number)=>{const regiao=this.regiaoEm(x),madeira=this.faseAtual%2===1||w<300,g=this.add.graphics().setDepth(3);if(madeira){const base=0x865735,topo=0xc58a4d,escuro=0x52351f;g.fillStyle(base).fillRoundedRect(x-w/2,y-h/2,w,h,7).lineStyle(4,escuro).strokeRoundedRect(x-w/2,y-h/2,w,h,7).fillStyle(topo).fillRoundedRect(x-w/2+4,y-h/2+4,w-8,8,4);for(let px=x-w/2+42;px<x+w/2;px+=48)g.lineStyle(2,escuro,.45).lineBetween(px,y-h/2+4,px,y+h/2-4);}else{const borda=this.misturarCor(regiao.cor,0x000000,.34);g.fillStyle(regiao.cor).fillRoundedRect(x-w/2,y-h/2,w,h,8).lineStyle(4,borda).strokeRoundedRect(x-w/2,y-h/2,w,h,8).fillStyle(this.misturarCor(regiao.cor,regiao.corDestaque,.72)).fillRoundedRect(x-w/2+3,y-h/2+3,w-6,10,5);for(let px=x-w/2+28;px<x+w/2;px+=55)g.fillStyle(regiao.corDestaque,.32).fillCircle(px,y+h/2-5,3);}return g;};
        const adicionarColisao=(x:number,y:number,w:number,h:number)=>{const corpo=this.add.rectangle(x,y,w,h,0xffffff,0);this.plataformas.add(corpo);(corpo.body as Phaser.Physics.Arcade.StaticBody).updateFromGameObject();};
        decorarPlataforma(this.larguraMundo/2,590,this.larguraMundo,100);adicionarColisao(this.larguraMundo/2,590,this.larguraMundo,100);
        [[650,485,180],[1050,415,160],[1450,485,190],[2050,405,180],[2550,475,160],[3100,390,190],[3650,470,170],[4200,400,180],[4750,480,160],[5250,390,190],[5700,470,180]].forEach(([x,y,w])=>{decorarPlataforma(x,y,w,26);adicionarColisao(x,y,w,26);});
        for(let x=350;x<this.larguraMundo-200;x+=520){this.add.image(x,526,'reino-objetos',Phaser.Math.Between(6,9)).setDisplaySize(105,95).setDepth(2).setAlpha(.92);}
    }
    private criarMoedas():void {
        const pontos=[[350,500],[650,420],[1050,350],[1450,420],[1800,500],[2050,340],[2550,410],[2850,500],[3100,325],[3650,405],[3950,500],[4200,335],[4750,415],[5050,500],[5250,325],[5700,405]];
        pontos.forEach(([x,y])=>{const moeda=this.physics.add.sprite(x,y,'reino-objetos',2).setDisplaySize(46,46).setDepth(6);const body=moeda.body as Phaser.Physics.Arcade.Body;body.setAllowGravity(false).setCircle(120,55,100);this.tweens.add({targets:moeda,y:y-10,angle:360,yoyo:true,repeat:-1,duration:650+Phaser.Math.Between(0,250)});const brilho=this.add.circle(x,y,28,0xffed91,.12).setDepth(5);this.tweens.add({targets:brilho,scale:1.45,alpha:0,yoyo:true,repeat:-1,duration:700});this.physics.add.overlap(this.cavaleiro,moeda,()=>{if(!moeda.active)return;brilho.destroy();moeda.disableBody(true,true);this.moedas++;this.textoMoedas?.setText(`${this.moedas}`);audioJogo.efeito('moeda');this.criarParticulas(moeda.x,moeda.y,0xffd85a,12);});});
    }
    private criarSlimes():void {
        const tipos=POSICOES_INIMIGOS.slice(this.faseAtual*4,this.faseAtual*4+6);[900,1800,2700,3800,4700,5500].forEach((x,i)=>{const tipo=tipos[i]?.tipo??'slime',y=tipo==='morcego'?350:i===2?390:500;let inimigo:InimigoReino;if(tipo==='morcego')inimigo=new MorcegoReino(this,x,y,this.cavaleiro);else if(tipo==='goblin')inimigo=new GoblinReino(this,x,y,this.cavaleiro);else if(tipo==='arqueiro')inimigo=new ArqueiroReino(this,x,y,this.cavaleiro,()=>this.dano(inimigo));else if(tipo==='planta')inimigo=new PlantaReino(this,x,y);else inimigo=new SlimeReino(this,x,y,tipo);this.inimigos.push(inimigo);if(inimigo.colideComPlataformas)this.physics.add.collider(inimigo.corpoColisao,this.plataformas);this.physics.add.overlap(this.cavaleiro,inimigo.corpoColisao,()=>this.dano(inimigo));});
    }
    private criarPortas():void {
        const categorias:CategoriaDesafio[]=['matematica','letras','silabas'];
        [1600,3300,5000].forEach((x,i)=>{const d={x,categoria:categorias[i]};
            const sprite=this.physics.add.staticSprite(d.x,469,'reino-objetos',0).setDisplaySize(132,190).setDepth(6);const body=sprite.body as Phaser.Physics.Arcade.StaticBody;body.setSize(100,180).setOffset(130,230);this.physics.add.collider(this.cavaleiro,sprite);this.portas.push({...d,sprite,aberta:false});
        });
    }
    private criarSegredos():void {[[1250,510],[2850,510],[4550,510],[5550,510]].forEach(([x,y])=>{const bau=this.add.container(x,y).setDepth(6),g=this.add.graphics().fillStyle(0x6d452b,1).fillRoundedRect(-28,-18,56,36,8).fillStyle(0xe0af43,1).fillRect(-28,-5,56,7).fillCircle(0,2,5);bau.add(g);const zona=this.physics.add.staticImage(x,y,'reino-objetos',2).setVisible(false).setSize(62,44);this.physics.add.overlap(this.cavaleiro,zona,()=>{if(!zona.active)return;zona.disableBody(true,true);this.tweens.add({targets:bau,y:y-18,alpha:0,duration:300,onComplete:()=>bau.destroy(true)});this.moedas+=3;this.textoMoedas?.setText(`${this.moedas}`);audioJogo.efeito('moeda');this.criarParticulas(x,y,this.regiaoEm(x).corDestaque,20);});});}
    private criarComposicoesCenario():void {
        const tema=this.regiaoEm(0),morro=(x:number,w:number,h:number,cor:number)=>this.add.ellipse(x,570,w,h,cor,.82).setDepth(-8).setStrokeStyle(5,this.misturarCor(cor,0x000000,.2));morro(900,720,260,this.misturarCor(tema.cor,tema.corDestaque,.48));morro(2500,900,330,this.misturarCor(tema.cor,tema.corDestaque,.34));morro(4400,760,280,this.misturarCor(tema.cor,tema.corDestaque,.52));
        const barril=(x:number)=>{const c=this.add.container(x,520).setDepth(5),g=this.add.graphics().fillStyle(0x8f5b32).fillRoundedRect(-22,-30,44,60,12).lineStyle(5,0x55351f).strokeRoundedRect(-22,-30,44,60,12).lineStyle(4,0xd09a55).lineBetween(-20,-13,20,-13).lineBetween(-20,14,20,14);c.add(g);};[780,2360,4100,5420].forEach(barril);
        [560,2250,3920,5350].forEach((x,i)=>{this.add.image(x,490,'reino-objetos',6+i%4).setDisplaySize(125,125).setDepth(2);this.add.rectangle(x+72,535,105,14,0x6f4326).setAngle(i%2?8:-7).setDepth(3);});
        const colmeia=this.add.container(1180,330).setDepth(4),g=this.add.graphics().fillStyle(0xd9a532).fillEllipse(0,0,48,58).lineStyle(4,0x9c6a20).strokeEllipse(0,0,48,58).fillStyle(0x5c3b1d).fillCircle(0,12,7);colmeia.add(g);for(let i=0;i<4;i++){const abelha=this.add.container(1180+i*11,330+i*5).setDepth(5),corpo=this.add.ellipse(0,0,13,8,0xf4c542).setStrokeStyle(2,0x49351c),asa1=this.add.ellipse(-3,-6,7,6,0xffffff,.7),asa2=this.add.ellipse(4,-6,7,6,0xffffff,.7);abelha.add([asa1,asa2,corpo]);this.tweens.add({targets:abelha,x:abelha.x+Phaser.Math.Between(25,65),y:abelha.y+Phaser.Math.Between(-25,25),duration:750+i*170,yoyo:true,repeat:-1,ease:'Sine.InOut'});}
    }
    private criarAmbiente():void {
        for(let i=0;i<112;i++){const x=Phaser.Math.Between(0,this.larguraMundo),y=Phaser.Math.Between(80,500),r=this.regiaoEm(x),p=this.add.circle(x,y,Phaser.Math.Between(2,4),i%3?r.corDestaque:0xffffff,Phaser.Math.FloatBetween(.18,.45)).setDepth(1);this.tweens.add({targets:p,y:y-Phaser.Math.Between(25,70),x:x+Phaser.Math.Between(-18,18),alpha:0,yoyo:true,repeat:-1,duration:Phaser.Math.Between(1800,4200)});}
        this.criarParticulasRegionais();
        for(let i=0;i<28;i++){const x=Phaser.Math.Between(0,this.larguraMundo),folha=this.add.ellipse(x,Phaser.Math.Between(40,420),10,5,i%2?0x8fbd45:0xd7a642,.55).setDepth(2).setAngle(Phaser.Math.Between(0,180));this.tweens.add({targets:folha,y:570,x:x+Phaser.Math.Between(-80,80),angle:folha.angle+360,alpha:.1,duration:3500+i*130,repeat:-1,onRepeat:()=>{folha.y=Phaser.Math.Between(20,120);folha.x=Phaser.Math.Between(0,this.larguraMundo);}});}
    }
    private criarParticulasRegionais():void {
        const tema=REGIOES_REINO[this.faseAtual];for(let i=0;i<22;i++){const x=Phaser.Math.Between(40,this.larguraMundo-40),y=Phaser.Math.Between(90,530),neve=tema.id==='montanha',pantano=tema.id==='pantano',p=this.add.circle(x,pantano?Phaser.Math.Between(500,545):y,Phaser.Math.Between(2,5),neve?0xffffff:tema.corDestaque,neve?.72:.32).setDepth(2);this.tweens.add({targets:p,y:pantano?p.y-80:neve?555:y-55,x:x+Phaser.Math.Between(-25,25),alpha:0,yoyo:!neve,repeat:-1,duration:1500+i*95,onRepeat:()=>{if(neve)p.y=Phaser.Math.Between(70,150);}});}
    }
    private regiaoEm(_x:number){return REGIOES_REINO[this.faseAtual];}
    private misturarCor(a:number,b:number,proporcao:number):number {const t=Phaser.Math.Clamp(proporcao,0,1),ar=(a>>16)&255,ag=(a>>8)&255,ab=a&255,br=(b>>16)&255,bg=(b>>8)&255,bb=b&255;return (Math.round(ar+(br-ar)*t)<<16)|(Math.round(ag+(bg-ag)*t)<<8)|Math.round(ab+(bb-ab)*t);}
    private criarPortal():void {
        const xPortal=this.larguraMundo-250,portal=this.physics.add.staticSprite(xPortal,465,'reino-objetos',4).setDisplaySize(150,190).setDepth(5);(portal.body as Phaser.Physics.Arcade.StaticBody).setSize(160,250).setOffset(95,170);this.tweens.add({targets:portal,alpha:.72,yoyo:true,repeat:-1,duration:800});for(let i=0;i<10;i++){const p=this.add.circle(xPortal+Phaser.Math.Between(-48,48),470+Phaser.Math.Between(-70,70),Phaser.Math.Between(2,5),0x9df5df,.7).setDepth(7);this.tweens.add({targets:p,y:p.y-55,alpha:0,yoyo:true,repeat:-1,duration:900+i*95});}this.physics.add.overlap(this.cavaleiro,portal,()=>{const faltam=this.portas.filter(p=>!p.aberta).length;if(faltam){if(this.time.now>this.avisoPortalEm){this.avisoPortalEm=this.time.now+2200;this.mostrarAviso(`Ainda falta abrir ${faltam} porta${faltam>1?'s':''}!`);}return;}if(!this.bloqueado)this.concluir();});
    }
    private criarHUD():void {
        const hud=this.add.container(0,0).setScrollFactor(0).setDepth(30);hud.add(this.add.graphics().fillStyle(0x173d34,.76).fillRoundedRect(16,14,270,58,18).lineStyle(2,0xffffff,.35).strokeRoundedRect(16,14,270,58,18));
        this.coracoes=[0,1,2,3].map(i=>this.add.image(42+i*38,43,'reino-objetos',3).setDisplaySize(31,31));this.textoMoedas=this.add.text(244,43,'0',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'22px',fontStyle:'bold',color:'#fff3b0'}).setOrigin(.5);hud.add([...this.coracoes,this.add.image(208,43,'reino-objetos',2).setDisplaySize(32,32),this.textoMoedas]);
        this.textoRegiao=this.add.text(480,34,'BOSQUE DOS NÚMEROS',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'15px',fontStyle:'bold',color:'#ffffff',stroke:'#244d42',strokeThickness:4}).setOrigin(.5).setScrollFactor(0).setDepth(35);this.barraProgresso=this.add.graphics().setScrollFactor(0).setDepth(35);
        this.botaoTela(884,42,118,42,'‹ EDUCAPP',0x376e61);const areaSair=this.add.zone(884,42,118,42).setScrollFactor(0).setDepth(42).setInteractive({useHandCursor:true});areaSair.on('pointerdown',()=>confirmarSaidaParaEducApp(this,{aoAbrir:()=>{this.bloqueado=true;this.cavaleiro.setVelocity(0);this.physics.pause();},aoCancelar:()=>{this.physics.resume();this.bloqueado=false;}}));this.botaoTela(748,42,112,42,'☰ JORNADA',0x557f9c);this.add.zone(748,42,112,42).setScrollFactor(0).setDepth(42).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.abrirPainelJornada());this.botaoTela(665,42,42,42,'Ⅱ',0x9a7048);this.add.zone(665,42,42,42).setScrollFactor(0).setDepth(42).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.alternarPausa());
    }
    private criarControlesTouch():void {
        const pressionavel=(x:number,y:number,rotulo:string,cor:number,down:()=>void,up?:()=>void)=>{const c=this.add.container(x,y).setScrollFactor(0).setDepth(40).setSize(72,72).setInteractive({useHandCursor:true});c.add([this.add.circle(0,4,34,0x173d34,.25),this.add.circle(0,0,34,cor,.72).setStrokeStyle(3,0xffffff,.65),this.add.text(0,0,rotulo,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'25px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5)]);c.on('pointerdown',()=>{c.setScale(.92);down();});const soltar=()=>{c.setScale(1);up?.();};c.on('pointerup',soltar);c.on('pointerout',soltar);return c;};
        pressionavel(72,555,'◀',0x3f8271,()=>this.esquerdaTouch=true,()=>this.esquerdaTouch=false);pressionavel(150,555,'▶',0x3f8271,()=>this.direitaTouch=true,()=>this.direitaTouch=false);pressionavel(640,555,'➜',0x8667a7,()=>this.dash());pressionavel(720,555,'◆',0x507fa4,()=>this.defesaTouch=true,()=>this.defesaTouch=false);pressionavel(805,555,'↑',0x4d82aa,()=>this.pular(),()=>this.cavaleiro.encerrarPulo());pressionavel(886,555,'⚔',0xb77b43,()=>this.atacar());
    }
    private verificarPortas():void {const porta=this.portas.find(p=>!p.aberta&&Math.abs(this.cavaleiro.x-p.x)<105);if(porta&&!this.portaAtual)this.abrirDesafio(porta);}
    private abrirDesafio(porta:PortaReino):void {
        this.limparZonasDesafio();
        this.errosPorta=0;this.primeiraTentativa=true;
        this.portaAtual=porta;this.bloqueado=true;this.cavaleiro.setVelocity(0);this.physics.pause();const estado=progressoReino.carregar(),desafio=criarDesafio(porta.categoria,estado.dificuldade,{soma:estado.faixaSoma,quantidade:estado.faixaQuantidade});
        const c=this.add.container(480,320).setScrollFactor(0).setDepth(100);this.modal=c;c.add(this.add.rectangle(0,0,960,640,0x12372e,.55));
        c.add(this.add.graphics().fillStyle(0x183d34,.2).fillRoundedRect(-308,-191,616,402,28).fillStyle(0xfffdf3,1).fillRoundedRect(-308,-201,616,402,28).lineStyle(5,0xe4b75c,1).strokeRoundedRect(-308,-201,616,402,28));
        const titulo=desafio.categoria==='matematica'?'PORTA DOS NÚMEROS':desafio.categoria==='letras'?'PORTA DAS LETRAS':desafio.categoria==='silabas'?'PORTA DAS PARTES':'PORTA DAS QUANTIDADES';c.add(this.add.text(0,-160,titulo,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'20px',fontStyle:'bold',color:'#92662e'}).setOrigin(.5));
        c.add(this.add.text(0,desafio.categoria==='quantidade'?-118:-72,desafio.pergunta,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:desafio.pergunta.length>22?'27px':'38px',fontStyle:'bold',color:'#315f51',align:'center',wordWrap:{width:530}}).setOrigin(.5));
        if(desafio.categoria==='quantidade')for(let i=0;i<desafio.resposta;i++){const colunas=5,x=(i%colunas-2)*48,y=-74+Math.floor(i/colunas)*34;c.add(this.add.star(x,y,5,7,14,i%2?0xe5ad3f:0xf2c956,1).setStrokeStyle(2,0xa87528,.8));}
        const yOuvir=desafio.categoria==='quantidade'?6:-10,ouvir=this.botaoModal(0,yOuvir,70,44,'🔊',0x4b8e7b);c.add(ouvir);const zonaOuvir=this.criarZonaDesafio(480,320+yOuvir,70,44);zonaOuvir.on('pointerdown',()=>servicoVoz.falar(desafio.palavra??desafio.pergunta));
        const dicaCoruja=progressoReino.carregar().equipado.companheiro==='coruja'?desafio.alternativas.findIndex(valor=>valor!==desafio.resposta):-1;
        desafio.alternativas.forEach((valor,i)=>{const xLocal=-170+i*170,b=this.botaoModal(xLocal,85,130,74,`${valor}`,0x4a9078);c.add(b);const zona=this.criarZonaDesafio(480+xLocal,405,130,74);zona.on('pointerover',()=>b.setScale(1.04));zona.on('pointerout',()=>b.setScale(1));zona.on('pointerdown',()=>{this.responderDesafio(b,valor,desafio,porta);if(valor!==desafio.resposta&&this.errosPorta>=2){zona.disableInteractive();b.setAlpha(.32);}});if(i===dicaCoruja){zona.disableInteractive();b.setAlpha(.32);}});
        c.setAlpha(0).setScale(.9);this.tweens.add({targets:c,alpha:1,scale:1,duration:220,ease:'Back.Out'});servicoVoz.falar(desafio.palavra??desafio.pergunta);
    }
    private responderDesafio(botao:Phaser.GameObjects.Container,valor:number,desafio:DesafioPorta,porta:PortaReino):void {
        if(valor!==desafio.resposta){this.errosPorta++;this.primeiraTentativa=false;this.comboPortas=0;audioJogo.efeito('erro');this.tweens.add({targets:botao,x:botao.x-7,yoyo:true,repeat:3,duration:50});const dica=this.add.text(480,505,this.errosPorta===1?'Quase lá! Tente outra resposta.':desafio.explicacao,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',color:'#5b6e67',backgroundColor:'#fffdf3',padding:{x:16,y:9},align:'center',wordWrap:{width:520}}).setOrigin(.5).setScrollFactor(0).setDepth(115);this.time.delayedCall(2600,()=>dica.destroy());if(this.errosPorta>1)servicoVoz.falar(desafio.explicacao);return;}
        if(this.primeiraTentativa){this.comboPortas++;this.moedas+=this.comboPortas;this.mostrarAviso(`COMBO ${this.comboPortas}! +${this.comboPortas} moeda${this.comboPortas>1?'s':''}`);}this.limparZonasDesafio();audioJogo.efeito('porta');this.criarParticulas(porta.x,410,0xffd867,24);porta.aberta=true;porta.sprite.setFrame(1);porta.sprite.disableBody();this.checkpoint=porta.x+125;progressoReino.salvar({faseAtual:this.faseAtual,checkpointX:this.checkpoint,portasAbertas:this.portas.filter(p=>p.aberta).length});
        this.modal?.disableInteractive();this.tweens.add({targets:this.modal,alpha:0,scale:1.05,duration:300,onComplete:()=>{this.modal?.destroy(true);this.modal=undefined;this.portaAtual=undefined;this.physics.resume();this.bloqueado=false;this.cavaleiro.x=porta.x+115;}});
    }
    private atacar():void {if(this.bloqueado||this.cavaleiro.defendendo)return;if(this.cavaleiro.atacando){this.ataquePendente=true;return;}const arma=progressoReino.carregar().equipado.arma,duracao=arma==='espada-rapida'?155:arma==='martelo'?280:220,alcance=arma==='martelo'?170:arma==='lanca'?195:135;this.cavaleiro.atacar(duracao);audioJogo.efeito('espada');if(arma==='arco')this.dispararFlecha();else this.time.delayedCall(95,()=>this.inimigos.forEach(inimigo=>{const dx=(inimigo.x-this.cavaleiro.x)*this.cavaleiro.olhando;if(!inimigo.derrotado&&dx>0&&dx<alcance&&Math.abs(inimigo.y-this.cavaleiro.y)<95)this.acertarInimigo(inimigo,arma==='martelo');}));this.time.delayedCall(duracao+10,()=>{if(this.ataquePendente&&!this.bloqueado){this.ataquePendente=false;this.atacar();}});}
    private acertarInimigo(inimigo:InimigoReino,forcarDerrota=false):void {const derrotado=forcarDerrota?(inimigo.derrotar(),true):inimigo.atingir();audioJogo.efeito('acerto');this.criarParticulas(inimigo.x,inimigo.y,derrotado?0x83dc63:0xc9f5a8,18);if(derrotado&&Math.random()<.7)this.soltarMoeda(inimigo.x,inimigo.y-25);}
    private dispararFlecha():void {const direcao=this.cavaleiro.olhando,inicioX=this.cavaleiro.x+direcao*45,projetil=this.add.ellipse(inicioX,this.cavaleiro.y-5,30,7,0xffd75e,1).setStrokeStyle(3,0xfff2a6,.8).setDepth(10),distancia=280;let tween!:Phaser.Tweens.Tween;tween=this.tweens.add({targets:projetil,x:inicioX+direcao*distancia,duration:500,ease:'Linear',onUpdate:()=>{if(!projetil.active)return;const alvo=this.inimigos.find(inimigo=>!inimigo.derrotado&&Math.abs(inimigo.x-projetil.x)<28&&Math.abs(inimigo.y-projetil.y)<95);if(alvo){this.acertarInimigo(alvo);tween.stop();projetil.destroy();}},onComplete:()=>projetil.destroy()});}
    private dash():void {if(this.bloqueado)return;if(this.cavaleiro.dash()){audioJogo.efeito('espada');this.cameras.main.shake(90,.002);}}
    private pular():void {if(this.bloqueado)return;if(this.cavaleiro.pular())audioJogo.efeito('pulo');}
    private dano(inimigo:InimigoReino):void {if(this.bloqueado||this.cavaleiro.invulneravel||inimigo.derrotado||this.cavaleiro.atacando)return;if(progressoReino.carregar().invencivel){this.cavaleiro.invulneravel=true;audioJogo.efeito('acerto');this.criarParticulas(this.cavaleiro.x,this.cavaleiro.y,0x9df5df,5);this.time.delayedCall(350,()=>this.cavaleiro.invulneravel=false);return;}if(this.cavaleiro.defendendo){this.cavaleiro.invulneravel=true;audioJogo.efeito('acerto');this.cavaleiro.setVelocityX((this.cavaleiro.x<inimigo.x?-1:1)*80);this.time.delayedCall(280,()=>this.cavaleiro.invulneravel=false);return;}this.vidas--;audioJogo.efeito('dano');this.cameras.main.shake(320,.014);this.cameras.main.flash(120,255,90,90);this.criarParticulas(this.cavaleiro.x,this.cavaleiro.y,0xff7048,8);this.cavaleiro.levarDano(inimigo.x);this.atualizarVidas();if(this.vidas<=0)this.time.delayedCall(450,()=>this.reposicionar());}
    private atualizarVidas():void {this.coracoes.forEach((c,i)=>c.setAlpha(i<this.vidas?1:.18));}
    private reposicionar():void {const dificuldade=progressoReino.carregar().dificuldade;this.vidas=dificuldade==='tranquilo'?4:dificuldade==='aventura'?2:3;this.atualizarVidas();this.cavaleiro.resetarEstado();this.cavaleiro.setPosition(this.checkpoint,430).setVelocity(0).setAlpha(1);this.cavaleiro.invulneravel=true;this.time.delayedCall(900,()=>this.cavaleiro.invulneravel=false);}
    private soltarMoeda(x:number,y:number):void {const m=this.physics.add.sprite(x,y,'reino-objetos',2).setDisplaySize(42,42).setVelocityY(-220).setDepth(7);this.physics.add.collider(m,this.plataformas);this.physics.add.overlap(this.cavaleiro,m,()=>{if(!m.active)return;m.disableBody(true,true);this.moedas++;this.textoMoedas.setText(`${this.moedas}`);audioJogo.efeito('moeda');this.criarParticulas(m.x,m.y,0xffd85a,12);});}
    private concluir():void {this.bloqueado=true;this.physics.pause();const estado=progressoReino.concluir(this.moedas),ultima=this.faseAtual>=REGIOES_REINO.length-1,proxima=ultima?0:this.faseAtual+1;audioJogo.efeito('conclusao');this.criarParticulas(this.cavaleiro.x,this.cavaleiro.y,0x72e4d2,35);const c=this.add.container(480,320).setScrollFactor(0).setDepth(120);c.add([this.add.rectangle(0,0,960,640,0x173c33,.56),this.add.graphics().fillStyle(0xfffdf3,1).fillRoundedRect(-300,-150,600,300,30).lineStyle(5,0x67b895).strokeRoundedRect(-300,-150,600,300,30),this.add.text(0,-88,ultima?'REINO DESBLOQUEADO!':'FASE CONCLUÍDA!',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'31px',fontStyle:'bold',color:'#34745c'}).setOrigin(.5),this.add.text(0,-28,`Moedas nesta fase: ${this.moedas}\nPróximo destino: ${REGIOES_REINO[proxima].nome}\nMelhor resultado: ${estado.melhorMoedas}`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',color:'#61776c',align:'center',lineSpacing:8}).setOrigin(.5)]);const novamente=this.botaoModal(-105,82,180,52,ultima?'RECOMEÇAR':'PRÓXIMA FASE',0x4c9a72),menu=this.botaoModal(110,82,180,52,'EDUCAPP',0x557f9c);c.add([novamente,menu]);const zNovo=this.add.zone(375,402,180,52).setScrollFactor(0).setDepth(130).setInteractive({useHandCursor:true}),zMenu=this.add.zone(590,402,180,52).setScrollFactor(0).setDepth(130).setInteractive({useHandCursor:true});zNovo.on('pointerdown',()=>{progressoReino.salvar({faseAtual:proxima,checkpointX:120,portasAbertas:0});this.scene.restart({fase:proxima});});zMenu.on('pointerdown',()=>confirmarSaidaParaEducApp(this));}
    private abrirPainelJornada():void {
        if(this.bloqueado)return;this.bloqueado=true;this.cavaleiro.setVelocity(0);this.physics.pause();
        const estado=progressoReino.carregar(),c=this.add.container(480,320).setScrollFactor(0).setDepth(150),g=this.add.graphics().fillStyle(0x15382f,.72).fillRect(-480,-320,960,640).fillStyle(0xfffdf3,1).fillRoundedRect(-410,-275,820,550,28).lineStyle(5,0xd8ae59).strokeRoundedRect(-410,-275,820,550,28);c.add([g,this.add.text(0,-242,'MAPA DA JORNADA',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'25px',fontStyle:'bold',color:'#386c5b'}).setOrigin(.5)]);
        REGIOES_REINO.forEach((r,i)=>{const x=-315+i*105,concluida=i<this.faseAtual,atual=i===this.faseAtual;c.add([this.add.circle(x,-190,22,concluida||atual?r.cor:0xbac3bf).setStrokeStyle(3,atual?0xffdc68:concluida?r.corDestaque:0x8c9994),this.add.text(x,-190,concluida?'✓':atual?'◆':'?',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5),this.add.text(x,-158,r.nome.split(' ')[0],{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'9px',color:'#536b62'}).setOrigin(.5)]);});
        const abertas=this.portas.filter(p=>p.aberta).length,missoes=MISSOES_REINO.map((m,i)=>`${(i===0?this.moedas>=m.alvo:i===1?abertas>=m.alvo:false)?'✓':'○'} ${m.texto}`).join('   ');c.add([this.add.text(0,-125,missoes,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'12px',fontStyle:'bold',color:'#526a61'}).setOrigin(.5),this.add.text(0,-98,`EQUIPAMENTOS  •  ${estado.equipamentos.length}/${EQUIPAMENTOS_REINO.length} itens  •  ${estado.moedas} moedas guardadas`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'13px',fontStyle:'bold',color:'#386c5b'}).setOrigin(.5)]);
        const fecharPainel=()=>{this.zonasPainel.forEach(z=>z.destroy());this.zonasPainel=[];c.destroy(true);this.physics.resume();this.bloqueado=false;};
        EQUIPAMENTOS_REINO.forEach((item,i)=>{const coluna=i%4,linha=Math.floor(i/4),x=-288+coluna*192,y=-52+linha*67,desbloqueado=estado.equipamentos.includes(item.id)&&item.preco<=estado.moedas,selecionado=estado.equipado.arma===item.id||estado.equipado.roupa===item.id||estado.equipado.companheiro===item.id,cor=item.tipo==='arma'?0xb47746:item.tipo==='roupa'?0x557fa3:0x7962a0,rotulo=desbloqueado?`${selecionado?'✓ ':''}${item.nome}`:`🔒 ${item.nome}\n${item.preco} moedas`,botao=this.add.container(x,y).setSize(174,55).setInteractive({useHandCursor:true});botao.add([this.add.graphics().fillStyle(desbloqueado?cor:0x9ca5a1,desbloqueado?1:.72).fillRoundedRect(-87,-27,174,54,13).lineStyle(selecionado?4:2,selecionado?0xffdc68:0xffffff,selecionado?1:.45).strokeRoundedRect(-87,-27,174,54,13),this.add.text(0,0,rotulo,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'10px',fontStyle:'bold',color:'#ffffff',align:'center',wordWrap:{width:158}}).setOrigin(.5)]);botao.on('pointerdown',()=>{if(!desbloqueado){this.mostrarAviso(`Ainda não desbloqueado — precisa de ${item.preco} moedas`);return;}const equipado={...estado.equipado};if(item.tipo==='arma')equipado.arma=item.id;else if(item.tipo==='roupa')equipado.roupa=equipado.roupa===item.id?undefined:item.id;else equipado.companheiro=equipado.companheiro===item.id?undefined:item.id;const skin=equipado.roupa?CORES_ROUPAS[equipado.roupa]??0xffffff:0xffffff;progressoReino.salvar({equipado,skin});this.cavaleiro.aplicarRoupa(skin);fecharPainel();});botao.on('pointerover',()=>botao.setScale(1.03));botao.on('pointerout',()=>botao.setScale(1));c.add(botao);const zona=this.add.zone(480+x,320+y,174,55).setScrollFactor(0).setDepth(155).setInteractive({useHandCursor:true});zona.on('pointerdown',()=>botao.emit('pointerdown')).on('pointerover',()=>botao.setScale(1.03)).on('pointerout',()=>botao.setScale(1));this.zonasPainel.push(zona);});
        c.add(this.add.text(0,126,'DIFICULDADE DA JORNADA',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'12px',fontStyle:'bold',color:'#386c5b'}).setOrigin(.5));
        let dificuldadeAtual=estado.dificuldade;const opcoes:{valor:typeof dificuldadeAtual;rotulo:string}[]=[{valor:'tranquilo',rotulo:'TRANQUILO'},{valor:'normal',rotulo:'NORMAL'},{valor:'aventura',rotulo:'AVENTURA'}],botoes:Phaser.GameObjects.Container[]=[];
        const atualizarBotoes=()=>botoes.forEach((botao,i)=>{const ativo=opcoes[i].valor===dificuldadeAtual;botao.removeAll(true);botao.add([this.add.graphics().fillStyle(ativo?0x4c9276:0x9aab9f,ativo?1:.72).fillRoundedRect(-72,-17,144,34,17).lineStyle(ativo?3:2,ativo?0xe4b75c:0xffffff,ativo?1:.5).strokeRoundedRect(-72,-17,144,34,17),this.add.text(0,0,`${ativo?'✓ ':''}${opcoes[i].rotulo}`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5)]);});
        opcoes.forEach((op,i)=>{const x=-168+i*168,botao=this.add.container(x,158).setSize(144,34).setInteractive({useHandCursor:true});botao.on('pointerdown',()=>{if(op.valor===dificuldadeAtual)return;dificuldadeAtual=op.valor;progressoReino.salvar({dificuldade:dificuldadeAtual});atualizarBotoes();this.mostrarAviso('Dificuldade salva! As vidas mudam no próximo recomeço/checkpoint.');});botao.on('pointerover',()=>botao.setScale(1.03));botao.on('pointerout',()=>botao.setScale(1));botoes.push(botao);c.add(botao);const zona=this.add.zone(480+x,478,144,34).setScrollFactor(0).setDepth(155).setInteractive({useHandCursor:true});zona.on('pointerdown',()=>botao.emit('pointerdown')).on('pointerover',()=>botao.setScale(1.03)).on('pointerout',()=>botao.setScale(1));this.zonasPainel.push(zona);});atualizarBotoes();
        c.add(this.add.text(0,185,'A dificuldade escolhida controla somente a quantidade de vidas.',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',color:'#687a73'}).setOrigin(.5));const fechar=this.botaoModal(0,232,190,48,'CONTINUAR',0x4c9276);c.add(fechar);const zonaFechar=this.add.zone(480,552,190,48).setScrollFactor(0).setDepth(155).setInteractive({useHandCursor:true});zonaFechar.on('pointerdown',fecharPainel);this.zonasPainel.push(zonaFechar);
    }
    private atualizarRegiao():void {const r=REGIOES_REINO[this.faseAtual];if(r.id!==this.regiaoAtual){this.regiaoAtual=r.id;this.textoRegiao.setText(`FASE ${this.faseAtual+1} • ${r.nome.toUpperCase()}`).setAlpha(0);this.tweens.add({targets:this.textoRegiao,alpha:1,duration:260});}const p=Phaser.Math.Clamp(this.cavaleiro.x/this.larguraMundo,0,1);this.barraProgresso.clear().fillStyle(0x173d34,.65).fillRoundedRect(330,55,300,9,5).fillStyle(r.corDestaque,1).fillRoundedRect(330,55,300*p,9,5);}
    private mostrarAviso(texto:string):void {const t=this.add.text(480,92,texto,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#315f51',padding:{x:18,y:9}}).setOrigin(.5).setScrollFactor(0).setDepth(180).setAlpha(0);this.tweens.add({targets:t,alpha:1,y:82,duration:180,yoyo:true,hold:1250,onComplete:()=>t.destroy()});}
    private alternarPausa():void {if(this.portaAtual)return;if(this.pausado){this.pausado=false;this.bloqueado=false;this.physics.resume();this.modal?.destroy(true);this.modal=undefined;return;}if(this.bloqueado)return;this.pausado=true;this.bloqueado=true;this.cavaleiro.setVelocity(0);this.physics.pause();const c=this.add.container(480,320).setScrollFactor(0).setDepth(160);this.modal=c;c.add([this.add.rectangle(0,0,960,640,0x17382f,.62),this.add.graphics().fillStyle(0xfffdf3,1).fillRoundedRect(-225,-115,450,230,28).lineStyle(5,0xd6ae61).strokeRoundedRect(-225,-115,450,230,28),this.add.text(0,-52,'JORNADA PAUSADA',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'27px',fontStyle:'bold',color:'#376a59'}).setOrigin(.5)]);const b=this.botaoModal(0,45,210,58,'CONTINUAR',0x4c9276);c.add(b);const z=this.add.zone(480,365,210,58).setScrollFactor(0).setDepth(165).setInteractive({useHandCursor:true});z.on('pointerdown',()=>{z.destroy();this.alternarPausa();});}
    private criarParticulas(x:number,y:number,cor:number,quantidade=14):void {for(let i=0;i<quantidade;i++){const p=this.add.circle(x,y,Phaser.Math.Between(3,7),i%3?cor:0xffffff).setDepth(90);this.tweens.add({targets:p,x:x+Phaser.Math.Between(-80,80),y:y+Phaser.Math.Between(-90,45),alpha:0,scale:.2,duration:Phaser.Math.Between(350,700),onComplete:()=>p.destroy()});}}
    private criarZonaDesafio(x:number,y:number,w:number,h:number):Phaser.GameObjects.Zone {const zona=this.add.zone(x,y,w,h).setScrollFactor(0).setDepth(110).setInteractive({useHandCursor:true});this.zonasDesafio.push(zona);return zona;}
    private limparZonasDesafio():void {this.zonasDesafio.forEach(zona=>zona.destroy());this.zonasDesafio=[];}
    private mostrarDicaInicial():void {const t=this.add.text(480,104,'◀ ▶  MOVA-SE    ↑  PULE    J  ATAQUE    X  ESCUDO',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'15px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#315f51',padding:{x:22,y:10}}).setOrigin(.5).setScrollFactor(0).setDepth(35).setAlpha(0);this.tweens.add({targets:t,alpha:1,duration:250});this.time.delayedCall(4500,()=>this.tweens.add({targets:t,alpha:0,duration:300,onComplete:()=>t.destroy()}));}
    private botaoTela(x:number,y:number,w:number,h:number,texto:string,cor:number):Phaser.GameObjects.Container {const c=this.add.container(x,y).setScrollFactor(0).setDepth(40).setSize(w,h),zona=this.add.zone(0,0,w,h).setInteractive({useHandCursor:true});c.add([this.add.graphics().fillStyle(cor,1).fillRoundedRect(-w/2,-h/2,w,h,h/2).lineStyle(2,0xffffff,.5).strokeRoundedRect(-w/2,-h/2,w,h,h/2),this.add.text(0,0,texto,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',color:'#ffffff'}).setOrigin(.5),zona]);zona.on('pointerdown',()=>c.emit('acao'));return c;}
    private botaoModal(x:number,y:number,w:number,h:number,texto:string,cor:number):Phaser.GameObjects.Container {const c=this.add.container(x,y).setSize(w,h).setInteractive({useHandCursor:true});c.add([this.add.graphics().fillStyle(0x244c40,.18).fillRoundedRect(-w/2,-h/2+5,w,h,18).fillStyle(cor,1).fillRoundedRect(-w/2,-h/2,w,h,18),this.add.text(0,0,texto,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:h>60?'28px':'14px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5)]);c.on('pointerdown',()=>c.emit('acao'));c.on('pointerover',()=>c.setScale(1.04));c.on('pointerout',()=>c.setScale(1));return c;}
}
