import * as Phaser from 'phaser';
import { servicoVoz } from '../../services/ServicoVoz';
import { criarDesafio, CategoriaDesafio, DesafioPorta } from '../dados/configuracaoReinoPortas';
import { CavaleiroReino } from '../entidades/CavaleiroReino';
import { SlimeReino } from '../entidades/SlimeReino';
import { audioJogo } from '../sistemas/SistemaAudio';
import { confirmarSaidaParaEducApp } from '../sistemas/ConfirmacaoSaida';
import { EQUIPAMENTOS_REINO, MISSOES_REINO, POSICOES_INIMIGOS, REGIOES_REINO } from '../dados/mundoReinoPortas';
import { progressoReino } from '../sistemas/ProgressoReino';

interface PortaReino {x:number;categoria:CategoriaDesafio;sprite:Phaser.Physics.Arcade.Sprite;aberta:boolean}

export class ReinoDasPortas extends Phaser.Scene {
    private readonly larguraMundo=4900;
    private cavaleiro!:CavaleiroReino;private plataformas!:Phaser.Physics.Arcade.StaticGroup;
    private slimes:SlimeReino[]=[];private portas:PortaReino[]=[];private moedas=0;private vidas=3;private checkpoint=120;
    private cursores!:Phaser.Types.Input.Keyboard.CursorKeys;private teclas!:Record<string,Phaser.Input.Keyboard.Key>;
    private esquerdaTouch=false;private direitaTouch=false;private bloqueado=false;private modal?:Phaser.GameObjects.Container;
    private ataquePendente=false;
    private zonasDesafio:Phaser.GameObjects.Zone[]=[];
    private textoMoedas!:Phaser.GameObjects.Text;private coracoes!:Phaser.GameObjects.Image[];private portaAtual?:PortaReino;
    private textoRegiao!:Phaser.GameObjects.Text;private barraProgresso!:Phaser.GameObjects.Graphics;private regiaoAtual='';private defesaTouch=false;
    private deslocamentoCamera=0;
    private errosPorta=0;private comboPortas=0;private primeiraTentativa=true;private pausado=false;
    private gamepadPuloAntes=false;private gamepadAtaqueAntes=false;private avisoPortalEm=0;
    private filtroEntardecer!:Phaser.GameObjects.Rectangle;

    constructor(){super('ReinoDasPortas');}
    create():void {
        this.physics.world.gravity.y=920;this.physics.world.setBounds(0,0,this.larguraMundo,640);
        this.criarCenario();this.criarAnimacoes();this.criarPlataformas();this.filtroEntardecer=this.add.rectangle(480,320,960,640,0x764873,0).setScrollFactor(0).setDepth(20);
        this.cavaleiro=new CavaleiroReino(this,120,450);this.physics.add.collider(this.cavaleiro,this.plataformas);
        this.criarMoedas();this.criarSlimes();this.criarPortas();this.criarSegredos();this.criarAmbiente();this.criarPortal();this.criarHUD();this.criarControlesTouch();
        this.cameras.main.setBounds(0,0,this.larguraMundo,640).startFollow(this.cavaleiro,true,.09,.09,0,45);
        const salvo=progressoReino.carregar();this.checkpoint=salvo.checkpointX;this.cavaleiro.x=this.checkpoint;this.cavaleiro.setTint(salvo.skin);this.portas.forEach((p,i)=>{if(i<salvo.portasAbertas){p.aberta=true;p.sprite.setFrame(1);p.sprite.disableBody();}});this.vidas=salvo.dificuldade==='tranquilo'?4:salvo.dificuldade==='aventura'?2:3;this.atualizarVidas();
        this.cursores=this.input.keyboard!.createCursorKeys();this.teclas=this.input.keyboard!.addKeys('A,D,S,Z,X,J,P,SHIFT,SPACE') as Record<string,Phaser.Input.Keyboard.Key>;
        this.input.keyboard!.on('keydown-Z',()=>this.atacar());this.input.keyboard!.on('keydown-X',()=>this.atacar());this.input.keyboard!.on('keydown-J',()=>this.atacar());
        this.input.keyboard!.on('keydown-SHIFT',()=>this.dash());this.input.keyboard!.on('keydown-P',()=>this.alternarPausa());
        this.input.keyboard!.on('keyup-UP',()=>this.cavaleiro.encerrarPulo());this.input.keyboard!.on('keyup-SPACE',()=>this.cavaleiro.encerrarPulo());
        this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>{servicoVoz.parar();audioJogo.pararMusicaReino();});
        audioJogo.iniciarMusicaReino();this.mostrarDicaInicial();
    }
    update():void {
        if(!this.cavaleiro||this.bloqueado)return;
        const esquerda=this.esquerdaTouch||this.cursores.left.isDown||this.teclas.A.isDown,direita=this.direitaTouch||this.cursores.right.isDown||this.teclas.D.isDown;
        const pad=this.input.gamepad?.getPad(0),eixo=pad?.axes[0]?.getValue()??0;this.cavaleiro.defender(this.defesaTouch||this.teclas.S.isDown||(pad?.L1??0)>0);this.cavaleiro.mover(this.cavaleiro.defendendo?0:Math.abs(eixo)>.25?Math.sign(eixo):esquerda?-1:direita?1:0,false);
        const gpPulo=!!pad?.buttons[0]?.pressed,gpAtaque=!!pad?.buttons[2]?.pressed;if(gpPulo&&!this.gamepadPuloAntes)this.pular();if(gpAtaque&&!this.gamepadAtaqueAntes)this.atacar();this.gamepadPuloAntes=gpPulo;this.gamepadAtaqueAntes=gpAtaque;
        if(Phaser.Input.Keyboard.JustDown(this.cursores.up)||Phaser.Input.Keyboard.JustDown(this.cursores.space)||Phaser.Input.Keyboard.JustDown(this.teclas.SPACE))this.pular();
        this.slimes.forEach(s=>s.atualizar());this.verificarPortas();this.atualizarRegiao();this.filtroEntardecer.setAlpha(Phaser.Math.Clamp((this.cavaleiro.x-3000)/1900,0,.16));this.deslocamentoCamera=Phaser.Math.Linear(this.deslocamentoCamera,-this.cavaleiro.olhando*72,.045);this.cameras.main.setFollowOffset(this.deslocamentoCamera,45);if(this.cavaleiro.y>620)this.reposicionar();
    }
    private criarCenario():void {
        this.add.tileSprite(this.larguraMundo/2,320,this.larguraMundo,640,'reino-panorama').setTileScale(.84).setDepth(-20);
        const ceu=this.add.graphics().setDepth(-11);for(let x=0;x<this.larguraMundo;x+=320){ceu.fillStyle(x%640?0x76ae67:0x6aa55f,.16).fillEllipse(x+150,550,390,210);}
        REGIOES_REINO.forEach((r,i)=>{this.add.text(r.inicio+150,350,r.nome.toUpperCase(),{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'19px',fontStyle:'bold',color:'#ffffff',stroke:'#31554b',strokeThickness:5}).setOrigin(.5).setDepth(2);if(i>0)this.add.rectangle(r.inicio,510,8,120,r.corDestaque,.45).setDepth(2);});
    }
    private criarAnimacoes():void {
        if(!this.anims.exists('reino-idle'))this.anims.create({key:'reino-idle',frames:[{key:'reino-cavaleiro',frame:0}],frameRate:1,repeat:-1});
        if(!this.anims.exists('reino-correr'))this.anims.create({key:'reino-correr',frames:this.anims.generateFrameNumbers('reino-cavaleiro',{frames:[2,3,4]}),frameRate:9,repeat:-1});
        if(!this.anims.exists('reino-atacar'))this.anims.create({key:'reino-atacar',frames:this.anims.generateFrameNumbers('reino-cavaleiro',{frames:[7,8,7]}),frameRate:14,repeat:0});
        if(!this.anims.exists('reino-slime-mover'))this.anims.create({key:'reino-slime-mover',frames:this.anims.generateFrameNumbers('reino-slime',{frames:[0,1,2]}),frameRate:5,repeat:-1});
    }
    private criarPlataformas():void {
        this.plataformas=this.physics.add.staticGroup();
        const plataforma=(x:number,y:number,w:number,h:number,cor=0x6e9b52)=>{const base=this.add.rectangle(x,y,w,h,cor).setDepth(3);base.setStrokeStyle(4,0x456f3b);const grama=this.add.rectangle(x,y-h/2+6,w-5,12,0x9bca62).setDepth(4);this.plataformas.add(base);(base.body as Phaser.Physics.Arcade.StaticBody).updateFromGameObject();return grama;};
        plataforma(2450,590,4900,100);[[690,485,180],[985,420,150],[1690,485,180],[2050,410,170],[2360,485,150],[3080,470,190],[3400,390,170],[3650,470,160],[4250,460,190],[4500,380,170]].forEach(([x,y,w])=>plataforma(x,y,w,26));
        for(let x=350;x<4700;x+=520){this.add.image(x,526,'reino-objetos',Phaser.Math.Between(6,9)).setDisplaySize(105,95).setDepth(2).setAlpha(.92);}
    }
    private criarMoedas():void {
        const pontos=[[360,475],[700,420],[985,355],[1580,500],[1710,420],[2050,345],[2320,420],[2950,500],[3100,405],[3400,325],[3650,405],[4180,500],[4280,395],[4500,315]];
        pontos.forEach(([x,y])=>{const moeda=this.physics.add.sprite(x,y,'reino-objetos',2).setDisplaySize(46,46).setDepth(6);const body=moeda.body as Phaser.Physics.Arcade.Body;body.setAllowGravity(false).setCircle(120,55,100);this.tweens.add({targets:moeda,y:y-10,angle:360,yoyo:true,repeat:-1,duration:650+Phaser.Math.Between(0,250)});const brilho=this.add.circle(x,y,28,0xffed91,.12).setDepth(5);this.tweens.add({targets:brilho,scale:1.45,alpha:0,yoyo:true,repeat:-1,duration:700});this.physics.add.overlap(this.cavaleiro,moeda,()=>{if(!moeda.active)return;brilho.destroy();moeda.disableBody(true,true);this.moedas++;this.textoMoedas?.setText(`${this.moedas}`);audioJogo.efeito('moeda');this.criarParticulas(moeda.x,moeda.y,0xffd85a);});});
    }
    private criarSlimes():void {
        POSICOES_INIMIGOS.forEach(({x,tipo})=>{const s=new SlimeReino(this,x,500,tipo);this.slimes.push(s);this.physics.add.collider(s,this.plataformas);this.physics.add.overlap(this.cavaleiro,s,()=>this.dano(s));});
    }
    private criarPortas():void {
        ([{x:1320,categoria:'matematica'},{x:2700,categoria:'letras'},{x:3900,categoria:'silabas'}] as Array<{x:number;categoria:CategoriaDesafio}>).forEach(d=>{
            const sprite=this.physics.add.staticSprite(d.x,469,'reino-objetos',0).setDisplaySize(132,190).setDepth(6);const body=sprite.body as Phaser.Physics.Arcade.StaticBody;body.setSize(100,180).setOffset(130,230);this.physics.add.collider(this.cavaleiro,sprite);this.portas.push({...d,sprite,aberta:false});const poste=this.add.rectangle(d.x-82,475,7,105,0x6c4b32).setDepth(5),bandeira=this.add.triangle(d.x-55,435,0,0,52,17,0,34,0xe7b84e).setDepth(5);this.tweens.add({targets:bandeira,scaleX:.9,yoyo:true,repeat:-1,duration:700});void poste;
        });
    }
    private criarSegredos():void {[[1120,510],[2220,510],[3520,510],[4435,510]].forEach(([x,y],i)=>{const bau=this.add.container(x,y).setDepth(6),g=this.add.graphics().fillStyle(0x6d452b,1).fillRoundedRect(-28,-18,56,36,8).fillStyle(0xe0af43,1).fillRect(-28,-5,56,7).fillCircle(0,2,5);bau.add(g);const zona=this.physics.add.staticImage(x,y,'reino-objetos',2).setVisible(false).setSize(62,44);this.physics.add.overlap(this.cavaleiro,zona,()=>{if(!zona.active)return;zona.disableBody(true,true);this.tweens.add({targets:bau,y:y-18,alpha:0,duration:300,onComplete:()=>bau.destroy(true)});this.moedas+=3;this.textoMoedas?.setText(`${this.moedas}`);audioJogo.efeito('moeda');this.criarParticulas(x,y,REGIOES_REINO[i+1].corDestaque,20);});});}
    private criarAmbiente():void {for(let i=0;i<45;i++){const x=Phaser.Math.Between(0,this.larguraMundo),y=Phaser.Math.Between(80,500),p=this.add.circle(x,y,Phaser.Math.Between(2,4),i%3?0xffffff:0xffdc75,Phaser.Math.FloatBetween(.18,.5)).setDepth(1);this.tweens.add({targets:p,y:y-Phaser.Math.Between(25,70),x:x+Phaser.Math.Between(-18,18),alpha:0,yoyo:true,repeat:-1,duration:Phaser.Math.Between(1800,4200)});}}
    private criarPortal():void {
        const portal=this.physics.add.staticSprite(4750,465,'reino-objetos',4).setDisplaySize(150,190).setDepth(5);(portal.body as Phaser.Physics.Arcade.StaticBody).setSize(160,250).setOffset(95,170);this.tweens.add({targets:portal,alpha:.72,yoyo:true,repeat:-1,duration:800});for(let i=0;i<10;i++){const p=this.add.circle(4750+Phaser.Math.Between(-48,48),470+Phaser.Math.Between(-70,70),Phaser.Math.Between(2,5),0x9df5df,.7).setDepth(7);this.tweens.add({targets:p,y:p.y-55,alpha:0,yoyo:true,repeat:-1,duration:900+i*95});}this.physics.add.overlap(this.cavaleiro,portal,()=>{const faltam=this.portas.filter(p=>!p.aberta).length;if(faltam){if(this.time.now>this.avisoPortalEm){this.avisoPortalEm=this.time.now+2200;this.mostrarAviso(`Ainda falta abrir ${faltam} porta${faltam>1?'s':''}!`);}return;}if(!this.bloqueado)this.concluir();});
    }
    private criarHUD():void {
        const hud=this.add.container(0,0).setScrollFactor(0).setDepth(30);hud.add(this.add.graphics().fillStyle(0x173d34,.76).fillRoundedRect(16,14,270,58,18).lineStyle(2,0xffffff,.35).strokeRoundedRect(16,14,270,58,18));
        this.coracoes=[0,1,2,3].map(i=>this.add.image(42+i*38,43,'reino-objetos',3).setDisplaySize(31,31));this.textoMoedas=this.add.text(244,43,'0',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'22px',fontStyle:'bold',color:'#fff3b0'}).setOrigin(.5);hud.add([...this.coracoes,this.add.image(208,43,'reino-objetos',2).setDisplaySize(32,32),this.textoMoedas]);
        this.textoRegiao=this.add.text(480,34,'BOSQUE DOS NÚMEROS',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'15px',fontStyle:'bold',color:'#ffffff',stroke:'#244d42',strokeThickness:4}).setOrigin(.5).setScrollFactor(0).setDepth(35);this.barraProgresso=this.add.graphics().setScrollFactor(0).setDepth(35);
        this.botaoTela(884,42,118,42,'‹ EDUCAPP',0x376e61);const areaSair=this.add.zone(884,42,118,42).setScrollFactor(0).setDepth(42).setInteractive({useHandCursor:true});areaSair.on('pointerdown',()=>confirmarSaidaParaEducApp(this,{aoAbrir:()=>{this.bloqueado=true;this.cavaleiro.setVelocity(0);this.physics.pause();},aoCancelar:()=>{this.physics.resume();this.bloqueado=false;}}));this.botaoTela(748,42,112,42,'☰ JORNADA',0x557f9c);this.add.zone(748,42,112,42).setScrollFactor(0).setDepth(42).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.abrirPainelJornada());this.botaoTela(665,42,42,42,'Ⅱ',0x9a7048);this.add.zone(665,42,42,42).setScrollFactor(0).setDepth(42).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.alternarPausa());
    }
    private criarControlesTouch():void {
        const pressionavel=(x:number,y:number,rotulo:string,cor:number,down:()=>void,up?:()=>void)=>{const c=this.add.container(x,y).setScrollFactor(0).setDepth(40).setSize(72,72).setInteractive({useHandCursor:true});c.add([this.add.circle(0,4,34,0x173d34,.25),this.add.circle(0,0,34,cor,.72).setStrokeStyle(3,0xffffff,.65),this.add.text(0,0,rotulo,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'25px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5)]);c.on('pointerdown',()=>{c.setScale(.92);down();});const soltar=()=>{c.setScale(1);up?.();};c.on('pointerup',soltar);c.on('pointerout',soltar);return c;};
        pressionavel(72,555,'◀',0x3f8271,()=>this.esquerdaTouch=true,()=>this.esquerdaTouch=false);pressionavel(150,555,'▶',0x3f8271,()=>this.direitaTouch=true,()=>this.direitaTouch=false);pressionavel(640,555,'➜',0x8667a7,()=>this.dash());pressionavel(720,555,'◆',0x507fa4,()=>this.defesaTouch=true,()=>this.defesaTouch=false);pressionavel(805,555,'↑',0x4d82aa,()=>this.pular(),()=>this.cavaleiro.encerrarPulo());pressionavel(886,555,'⚔',0xb77b43,()=>this.atacar());
    }
    private verificarPortas():void {const porta=this.portas.find(p=>!p.aberta&&Math.abs(this.cavaleiro.x-p.x)<105);if(porta&&!this.portaAtual)this.abrirDesafio(porta);}
    private abrirDesafio(porta:PortaReino):void {
        this.limparZonasDesafio();
        this.errosPorta=0;this.primeiraTentativa=true;
        this.portaAtual=porta;this.bloqueado=true;this.cavaleiro.setVelocity(0);this.physics.pause();const desafio=criarDesafio(porta.categoria);
        const c=this.add.container(480,320).setScrollFactor(0).setDepth(100);this.modal=c;c.add(this.add.rectangle(0,0,960,640,0x12372e,.55));
        c.add(this.add.graphics().fillStyle(0x183d34,.2).fillRoundedRect(-308,-191,616,402,28).fillStyle(0xfffdf3,1).fillRoundedRect(-308,-201,616,402,28).lineStyle(5,0xe4b75c,1).strokeRoundedRect(-308,-201,616,402,28));
        const titulo=desafio.categoria==='matematica'?'PORTA DOS NÚMEROS':desafio.categoria==='letras'?'PORTA DAS LETRAS':'PORTA DAS PARTES';c.add(this.add.text(0,-160,titulo,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'20px',fontStyle:'bold',color:'#92662e'}).setOrigin(.5));
        c.add(this.add.text(0,-72,desafio.pergunta,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:desafio.pergunta.length>22?'27px':'38px',fontStyle:'bold',color:'#315f51',align:'center',wordWrap:{width:530}}).setOrigin(.5));
        const ouvir=this.botaoModal(0,-10,70,44,'🔊',0x4b8e7b);c.add(ouvir);const zonaOuvir=this.criarZonaDesafio(480,310,70,44);zonaOuvir.on('pointerdown',()=>servicoVoz.falar(desafio.palavra??desafio.pergunta));
        desafio.alternativas.forEach((valor,i)=>{const xLocal=-170+i*170,b=this.botaoModal(xLocal,85,130,74,`${valor}`,0x4a9078);c.add(b);const zona=this.criarZonaDesafio(480+xLocal,405,130,74);zona.on('pointerover',()=>b.setScale(1.04));zona.on('pointerout',()=>b.setScale(1));zona.on('pointerdown',()=>{this.responderDesafio(b,valor,desafio,porta);if(valor!==desafio.resposta&&this.errosPorta>=2){zona.disableInteractive();b.setAlpha(.32);}});});
        c.setAlpha(0).setScale(.9);this.tweens.add({targets:c,alpha:1,scale:1,duration:220,ease:'Back.Out'});servicoVoz.falar(desafio.palavra??desafio.pergunta);
    }
    private responderDesafio(botao:Phaser.GameObjects.Container,valor:number,desafio:DesafioPorta,porta:PortaReino):void {
        if(valor!==desafio.resposta){this.errosPorta++;this.primeiraTentativa=false;this.comboPortas=0;audioJogo.efeito('erro');this.tweens.add({targets:botao,x:botao.x-7,yoyo:true,repeat:3,duration:50});const dica=this.add.text(480,505,this.errosPorta===1?'Quase lá! Tente outra resposta.':desafio.explicacao,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',color:'#5b6e67',backgroundColor:'#fffdf3',padding:{x:16,y:9},align:'center',wordWrap:{width:520}}).setOrigin(.5).setScrollFactor(0).setDepth(115);this.time.delayedCall(2600,()=>dica.destroy());if(this.errosPorta>1)servicoVoz.falar(desafio.explicacao);return;}
        if(this.primeiraTentativa){this.comboPortas++;this.moedas+=this.comboPortas;this.mostrarAviso(`COMBO ${this.comboPortas}! +${this.comboPortas} moeda${this.comboPortas>1?'s':''}`);}this.limparZonasDesafio();audioJogo.efeito('porta');this.criarParticulas(porta.x,410,0xffd867);porta.aberta=true;porta.sprite.setFrame(1);porta.sprite.disableBody();this.checkpoint=porta.x+125;progressoReino.salvar({checkpointX:this.checkpoint,portasAbertas:this.portas.filter(p=>p.aberta).length});
        this.modal?.disableInteractive();this.tweens.add({targets:this.modal,alpha:0,scale:1.05,duration:300,onComplete:()=>{this.modal?.destroy(true);this.modal=undefined;this.portaAtual=undefined;this.physics.resume();this.bloqueado=false;this.cavaleiro.x=porta.x+115;}});
    }
    private atacar():void {if(this.bloqueado||this.cavaleiro.defendendo)return;if(this.cavaleiro.atacando){this.ataquePendente=true;return;}this.cavaleiro.atacar();audioJogo.efeito('espada');this.time.delayedCall(95,()=>this.slimes.forEach(s=>{const dx=(s.x-this.cavaleiro.x)*this.cavaleiro.olhando;if(!s.derrotado&&dx>0&&dx<135&&Math.abs(s.y-this.cavaleiro.y)<95){const derrotado=s.atingir();audioJogo.efeito('acerto');this.criarParticulas(s.x,s.y,derrotado?0xa5ef73:0xffffff);if(derrotado&&Math.random()<.7)this.soltarMoeda(s.x,s.y-25);}}));this.time.delayedCall(230,()=>{if(this.ataquePendente&&!this.bloqueado){this.ataquePendente=false;this.atacar();}});}
    private dash():void {if(this.bloqueado)return;if(this.cavaleiro.dash()){audioJogo.efeito('espada');this.cameras.main.shake(90,.002);}}
    private pular():void {if(this.bloqueado)return;if(this.cavaleiro.pular())audioJogo.efeito('pulo');}
    private dano(slime:SlimeReino):void {if(this.bloqueado||this.cavaleiro.invulneravel||slime.derrotado||this.cavaleiro.atacando)return;if(this.cavaleiro.defendendo){this.cavaleiro.invulneravel=true;audioJogo.efeito('acerto');this.cavaleiro.setVelocityX((this.cavaleiro.x<slime.x?-1:1)*80);this.time.delayedCall(280,()=>this.cavaleiro.invulneravel=false);return;}this.vidas--;audioJogo.efeito('dano');this.cameras.main.shake(150,.008);this.cameras.main.flash(90,255,120,100);this.cavaleiro.levarDano(slime.x);this.atualizarVidas();if(this.vidas<=0)this.time.delayedCall(450,()=>this.reposicionar());}
    private atualizarVidas():void {this.coracoes.forEach((c,i)=>c.setAlpha(i<this.vidas?1:.18));}
    private reposicionar():void {this.vidas=3;this.atualizarVidas();this.cavaleiro.setPosition(this.checkpoint,430).setVelocity(0).setAlpha(1);this.cavaleiro.invulneravel=true;this.time.delayedCall(900,()=>this.cavaleiro.invulneravel=false);}
    private soltarMoeda(x:number,y:number):void {const m=this.physics.add.sprite(x,y,'reino-objetos',2).setDisplaySize(42,42).setVelocityY(-220).setDepth(7);this.physics.add.collider(m,this.plataformas);this.physics.add.overlap(this.cavaleiro,m,()=>{if(!m.active)return;m.disableBody(true,true);this.moedas++;this.textoMoedas.setText(`${this.moedas}`);audioJogo.efeito('moeda');});}
    private concluir():void {this.bloqueado=true;this.physics.pause();const estado=progressoReino.concluir(this.moedas);audioJogo.efeito('conclusao');this.criarParticulas(this.cavaleiro.x,this.cavaleiro.y,0x72e4d2,35);const c=this.add.container(480,320).setScrollFactor(0).setDepth(120);c.add([this.add.rectangle(0,0,960,640,0x173c33,.56),this.add.graphics().fillStyle(0xfffdf3,1).fillRoundedRect(-300,-150,600,300,30).lineStyle(5,0x67b895).strokeRoundedRect(-300,-150,600,300,30),this.add.text(0,-88,'REINO DESBLOQUEADO!',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'31px',fontStyle:'bold',color:'#34745c'}).setOrigin(.5),this.add.text(0,-28,`Moedas nesta jornada: ${this.moedas}\nMelhor resultado: ${estado.melhorMoedas}  •  Jornadas: ${estado.conclusoes}`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',color:'#61776c',align:'center',lineSpacing:8}).setOrigin(.5)]);const novamente=this.botaoModal(-105,82,180,52,'JOGAR DE NOVO',0x4c9a72),menu=this.botaoModal(110,82,180,52,'EDUCAPP',0x557f9c);c.add([novamente,menu]);const zNovo=this.add.zone(375,402,180,52).setScrollFactor(0).setDepth(130).setInteractive({useHandCursor:true}),zMenu=this.add.zone(590,402,180,52).setScrollFactor(0).setDepth(130).setInteractive({useHandCursor:true});zNovo.on('pointerdown',()=>{progressoReino.salvar({checkpointX:120,portasAbertas:0});this.scene.restart();});zMenu.on('pointerdown',()=>confirmarSaidaParaEducApp(this));}
    private abrirPainelJornada():void {if(this.bloqueado)return;this.bloqueado=true;this.cavaleiro.setVelocity(0);this.physics.pause();const estado=progressoReino.carregar(),c=this.add.container(480,320).setScrollFactor(0).setDepth(150),g=this.add.graphics().fillStyle(0x15382f,.72).fillRect(-480,-320,960,640).fillStyle(0xfffdf3,1).fillRoundedRect(-390,-245,780,490,28).lineStyle(5,0xd8ae59).strokeRoundedRect(-390,-245,780,490,28);c.add([g,this.add.text(0,-205,'MAPA DA JORNADA',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'27px',fontStyle:'bold',color:'#386c5b'}).setOrigin(.5)]);REGIOES_REINO.forEach((r,i)=>{const x=-315+i*105,aberta=this.cavaleiro.x>=r.inicio;c.add([this.add.circle(x,-120,28,aberta?r.cor:0xbac3bf).setStrokeStyle(3,aberta?r.corDestaque:0x8c9994),this.add.text(x,-120,aberta?'✓':'?',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'20px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5),this.add.text(x,-78,r.nome.split(' ')[0],{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'10px',color:'#536b62'}).setOrigin(.5)]);});const abertas=this.portas.filter(p=>p.aberta).length,missoes=MISSOES_REINO.map((m,i)=>`${(i===0?this.moedas>=m.alvo:i===1?abertas>=m.alvo:false)?'✓':'○'} ${m.texto}`).join('\n');c.add([this.add.text(-330,-22,`MISSÕES\n${missoes}`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'15px',fontStyle:'bold',color:'#526a61',lineSpacing:9}),this.add.text(40,-22,`COLEÇÃO\n${estado.equipamentos.length}/${EQUIPAMENTOS_REINO.length} itens\n${estado.moedas} moedas guardadas\n${estado.conclusoes} jornadas completas`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'15px',fontStyle:'bold',color:'#526a61',lineSpacing:9})]);const fechar=this.botaoModal(0,175,190,52,'CONTINUAR',0x4c9276);c.add(fechar);const zona=this.add.zone(480,495,190,52).setScrollFactor(0).setDepth(155).setInteractive({useHandCursor:true});zona.on('pointerdown',()=>{zona.destroy();c.destroy(true);this.physics.resume();this.bloqueado=false;});}
    private atualizarRegiao():void {const r=REGIOES_REINO.find(item=>this.cavaleiro.x>=item.inicio&&this.cavaleiro.x<item.fim)??REGIOES_REINO[REGIOES_REINO.length-1];if(r.id!==this.regiaoAtual){this.regiaoAtual=r.id;this.textoRegiao.setText(r.nome.toUpperCase()).setAlpha(0);this.tweens.add({targets:this.textoRegiao,alpha:1,duration:260});}const p=Phaser.Math.Clamp(this.cavaleiro.x/this.larguraMundo,0,1);this.barraProgresso.clear().fillStyle(0x173d34,.65).fillRoundedRect(330,55,300,9,5).fillStyle(r.corDestaque,1).fillRoundedRect(330,55,300*p,9,5);}
    private mostrarAviso(texto:string):void {const t=this.add.text(480,92,texto,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#315f51',padding:{x:18,y:9}}).setOrigin(.5).setScrollFactor(0).setDepth(140).setAlpha(0);this.tweens.add({targets:t,alpha:1,y:82,duration:180,yoyo:true,hold:1250,onComplete:()=>t.destroy()});}
    private alternarPausa():void {if(this.portaAtual)return;if(this.pausado){this.pausado=false;this.bloqueado=false;this.physics.resume();this.modal?.destroy(true);this.modal=undefined;return;}if(this.bloqueado)return;this.pausado=true;this.bloqueado=true;this.cavaleiro.setVelocity(0);this.physics.pause();const c=this.add.container(480,320).setScrollFactor(0).setDepth(160);this.modal=c;c.add([this.add.rectangle(0,0,960,640,0x17382f,.62),this.add.graphics().fillStyle(0xfffdf3,1).fillRoundedRect(-225,-115,450,230,28).lineStyle(5,0xd6ae61).strokeRoundedRect(-225,-115,450,230,28),this.add.text(0,-52,'JORNADA PAUSADA',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'27px',fontStyle:'bold',color:'#376a59'}).setOrigin(.5)]);const b=this.botaoModal(0,45,210,58,'CONTINUAR',0x4c9276);c.add(b);const z=this.add.zone(480,365,210,58).setScrollFactor(0).setDepth(165).setInteractive({useHandCursor:true});z.on('pointerdown',()=>{z.destroy();this.alternarPausa();});}
    private criarParticulas(x:number,y:number,cor:number,quantidade=14):void {for(let i=0;i<quantidade;i++){const p=this.add.circle(x,y,Phaser.Math.Between(3,7),i%3?cor:0xffffff).setDepth(90);this.tweens.add({targets:p,x:x+Phaser.Math.Between(-80,80),y:y+Phaser.Math.Between(-90,45),alpha:0,scale:.2,duration:Phaser.Math.Between(350,700),onComplete:()=>p.destroy()});}}
    private criarZonaDesafio(x:number,y:number,w:number,h:number):Phaser.GameObjects.Zone {const zona=this.add.zone(x,y,w,h).setScrollFactor(0).setDepth(110).setInteractive({useHandCursor:true});this.zonasDesafio.push(zona);return zona;}
    private limparZonasDesafio():void {this.zonasDesafio.forEach(zona=>zona.destroy());this.zonasDesafio=[];}
    private mostrarDicaInicial():void {const t=this.add.text(480,104,'◀ ▶  MOVA-SE    ↑  PULE    Z  ATAQUE    S  ESCUDO',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'15px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#315f51',padding:{x:22,y:10}}).setOrigin(.5).setScrollFactor(0).setDepth(35).setAlpha(0);this.tweens.add({targets:t,alpha:1,duration:250});this.time.delayedCall(4500,()=>this.tweens.add({targets:t,alpha:0,duration:300,onComplete:()=>t.destroy()}));}
    private botaoTela(x:number,y:number,w:number,h:number,texto:string,cor:number):Phaser.GameObjects.Container {const c=this.add.container(x,y).setScrollFactor(0).setDepth(40).setSize(w,h),zona=this.add.zone(0,0,w,h).setInteractive({useHandCursor:true});c.add([this.add.graphics().fillStyle(cor,1).fillRoundedRect(-w/2,-h/2,w,h,h/2).lineStyle(2,0xffffff,.5).strokeRoundedRect(-w/2,-h/2,w,h,h/2),this.add.text(0,0,texto,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',color:'#ffffff'}).setOrigin(.5),zona]);zona.on('pointerdown',()=>c.emit('acao'));return c;}
    private botaoModal(x:number,y:number,w:number,h:number,texto:string,cor:number):Phaser.GameObjects.Container {const c=this.add.container(x,y).setSize(w,h).setInteractive({useHandCursor:true});c.add([this.add.graphics().fillStyle(0x244c40,.18).fillRoundedRect(-w/2,-h/2+5,w,h,18).fillStyle(cor,1).fillRoundedRect(-w/2,-h/2,w,h,18),this.add.text(0,0,texto,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:h>60?'28px':'14px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5)]);c.on('pointerdown',()=>c.emit('acao'));c.on('pointerover',()=>c.setScale(1.04));c.on('pointerout',()=>c.setScale(1));return c;}
}
