import * as Phaser from 'phaser';
import { servicoVoz } from '../../services/ServicoVoz';
import { DISCIPLINA_DESAFIO, escolherTiposDaJornada, SessaoDesafiosReino, validarRespostaDesafio, type InstanciaDesafio, type TipoDesafio } from '../sistemas/DesafiosReino';
import { renderizarDesafioReino } from '../sistemas/RenderizadorDesafioReino';
import { CavaleiroReino } from '../entidades/CavaleiroReino';
import { InimigoReino } from '../entidades/InimigoReino';
import { SlimeReino } from '../entidades/SlimeReino';
import { MorcegoReino } from '../entidades/MorcegoReino';
import { ArqueiroReino } from '../entidades/ArqueiroReino';
import { CogumeloSaltadorReino } from '../entidades/CogumeloSaltadorReino';
import { FuracaoFolhasReino } from '../entidades/FuracaoFolhasReino';
import { CavaleiroEspantalhoReino } from '../entidades/CavaleiroEspantalhoReino';
import { GoblinReino } from '../entidades/GoblinReino';
import { InimigoFogoReino } from '../entidades/InimigoFogoReino';
import { PlantaReino } from '../entidades/PlantaReino';
import { MimicoPortaReino } from '../entidades/MimicoPortaReino';
import { audioJogo } from '../sistemas/SistemaAudio';
import { confirmarSaidaParaEducApp } from '../sistemas/ConfirmacaoSaida';
import { EQUIPAMENTOS_REINO, INIMIGOS_POR_REGIAO, MISSOES_REINO, REGIOES_REINO } from '../dados/mundoReinoPortas';
import { progressoReino } from '../sistemas/ProgressoReino';
import { assentarTerrestre, criarSuperficie, criarSuperficieMovel, superficieAbaixo, type SuperficieMovelReino } from '../sistemas/TerrestreReino';
import { AVENTURAS_REINO, gerarNivelReino, sobrepoeGap, validarNivelReino, type AventuraReino, type NivelReino } from '../sistemas/LevelReino';

interface PortaReino {x:number;tipo:TipoDesafio;sprite:Phaser.Physics.Arcade.Sprite;emblema:Phaser.GameObjects.Container;aberta:boolean}
type TipoPocao='veloz'|'salto'|'escudo';
interface PocaoConfig {cor:number;corClara:number;texto:string;nome:string;duracao:number}
type FormatoParticula='circulo'|'respingo'|'farrapo'|'fumaca'|'folha'|'lasca'|'esporo'|'redemoinho';
const CORES_ROUPAS:Record<string,number>={'armadura-verde':0x79c879,'armadura-azul':0x75bdf0,'capa-mago':0xc28be8};
const POCOES:Record<TipoPocao,PocaoConfig>={veloz:{cor:0x20cce5,corClara:0xb8f7ff,texto:'VELOCIDADE!',nome:'POÇÃO VELOZ',duracao:9000},salto:{cor:0xb8db38,corClara:0xf3ff9a,texto:'SALTO ALTO!',nome:'POÇÃO DE SALTO',duracao:9000},escudo:{cor:0x9b63d5,corClara:0xffd66b,texto:'ESCUDO!',nome:'POÇÃO DE ESCUDO',duracao:9000}};
const POSICOES_PORTAS=[1600,3300,5000];

export class ReinoDasPortas extends Phaser.Scene {
    private readonly larguraMundo=6200;private faseAtual=0;
    private cavaleiro!:CavaleiroReino;private plataformas!:Phaser.Physics.Arcade.StaticGroup;
    private nivel!:NivelReino;private ultimaPosicaoSegura={x:120,y:420};private ultimoSeguroEm=0;private retornandoDaQueda=false;
    private plataformasEspeciais:{corpo:Phaser.Physics.Arcade.Body|Phaser.Physics.Arcade.StaticBody;tipo:'quebravel'|'impulso';ativa?:boolean}[]=[];
    private plataformasMoveis!:Phaser.Physics.Arcade.Group;private perigos!:Phaser.Physics.Arcade.StaticGroup;private barreirasInimigos!:Phaser.Physics.Arcade.StaticGroup;
    private movimentosPlataformas:(SuperficieMovelReino&{eixo:'x'|'y';inicio:number;fim:number;velocidade:number;ultimo:number})[]=[];
    private inimigos:InimigoReino[]=[];private portas:PortaReino[]=[];private moedas=0;private vidas=4;private checkpoint=120;
    private cursores!:Phaser.Types.Input.Keyboard.CursorKeys;private teclas!:Record<string,Phaser.Input.Keyboard.Key>;
    private esquerdaTouch=false;private direitaTouch=false;private bloqueado=false;private transicionando=false;private modal?:Phaser.GameObjects.Container;
    private ataquePendente=false;
    private readonly sessaoDesafios=new SessaoDesafiosReino();
    private zonasPainel:Phaser.GameObjects.Zone[]=[];
    private textoMoedas!:Phaser.GameObjects.Text;private textoInimigos!:Phaser.GameObjects.Text;private coracoes!:Phaser.GameObjects.Image[];private portaAtual?:PortaReino;
    private textoRegiao!:Phaser.GameObjects.Text;private barraProgresso!:Phaser.GameObjects.Graphics;private regiaoAtual='';private defesaTouch=false;
    private deslocamentoCamera=0;
    private errosPorta=0;private comboPortas=0;private primeiraTentativa=true;private pausado=false;
    private gamepadPuloAntes=false;private gamepadAtaqueAntes=false;private avisoPortalEm=0;
    private filtroEntardecer!:Phaser.GameObjects.Rectangle;
    private portalVisual?:Phaser.GameObjects.Container;private portalSprite?:Phaser.Physics.Arcade.Sprite;private portalPronto=false;
    private pocaoAtiva?:TipoPocao;private pocaoAte=0;private auraPocao?:Phaser.GameObjects.Arc;private hudPocao?:Phaser.GameObjects.Container;private barraPocao?:Phaser.GameObjects.Graphics;private textoPocao?:Phaser.GameObjects.Text;
    private aventura!:AventuraReino;private eventosAventura=new Set<string>();private textoObjetivo?:Phaser.GameObjects.Text;private bloqueioAventura?:{x:number;corpo:Phaser.Physics.Arcade.StaticBody;visual:Phaser.GameObjects.Container};private mecanismosAventura:{x:number;y:number;evento:string;acao:()=>void}[]=[];private caixaAventura?:Phaser.Physics.Arcade.Image;private caixaInicio?:{x:number;y:number};private placaAventuraX=0;private ponteAventuraCriada=false;

    constructor(){super('ReinoDasPortas');}
    init(dados?:{fase?:number}):void {this.faseAtual=Phaser.Math.Clamp(dados?.fase??progressoReino.carregar().faseAtual,0,REGIOES_REINO.length-1);}
    create():void {
        this.physics.resume();
        this.cameras.main.fadeIn(650,18,35,31);
        this.inimigos=[];this.portas=[];this.zonasPainel=[];this.movimentosPlataformas=[];this.plataformasEspeciais=[];this.moedas=0;this.vidas=4;this.checkpoint=120;this.portaAtual=undefined;this.modal=undefined;this.bloqueado=false;this.transicionando=false;this.pausado=false;this.esquerdaTouch=false;this.direitaTouch=false;this.defesaTouch=false;this.ataquePendente=false;this.comboPortas=0;this.regiaoAtual='';this.portalVisual=undefined;this.portalSprite=undefined;this.portalPronto=false;this.pocaoAtiva=undefined;this.pocaoAte=0;this.auraPocao=undefined;this.hudPocao=undefined;this.retornandoDaQueda=false;this.ultimoSeguroEm=0;this.eventosAventura=new Set();this.mecanismosAventura=[];this.bloqueioAventura=undefined;this.caixaAventura=undefined;this.caixaInicio=undefined;this.textoObjetivo=undefined;this.placaAventuraX=0;this.ponteAventuraCriada=false;
        this.physics.world.gravity.y=920;this.physics.world.setBounds(0,0,this.larguraMundo,720);this.physics.world.setBoundsCollision(true,true,true,false);
        this.criarCenario();this.criarAnimacoes();this.criarPlataformas();this.filtroEntardecer=this.add.rectangle(480,320,960,640,0x764873,0).setScrollFactor(0).setDepth(20);
        this.cavaleiro=new CavaleiroReino(this,120,this.pisoAbaixo(120,0)-100);this.cavaleiro.definirCorPoeira(this.corPoeiraRegiao());this.physics.add.collider(this.cavaleiro,this.plataformas,undefined,this.podeApoiarCavaleiro,this);this.physics.add.collider(this.cavaleiro,this.plataformasMoveis,undefined,this.podeApoiarCavaleiro,this);this.plataformasEspeciais.forEach(p=>this.configurarPlataformaEspecial(p.corpo,p.tipo));this.physics.add.overlap(this.cavaleiro,this.perigos,(_c,perigo)=>this.danoCenario((perigo as Phaser.GameObjects.GameObject&{x:number}).x));this.criarCheckpoints();
        this.criarMoedas();this.criarPocoes();this.criarInimigos();this.criarPortas();this.criarAventura();this.criarSegredos();this.criarColecionaveis();this.criarComposicoesCenario();this.criarAmbiente();this.criarPortal();this.criarHUD();this.criarControlesTouch();
        this.cameras.main.setBounds(0,0,this.larguraMundo,640).startFollow(this.cavaleiro,true,.09,.09,0,45);this.cameras.main.roundPixels=true;
        const salvo=progressoReino.carregar(),checkpointValido=salvo.checkpointLevel===this.faseAtual&&salvo.checkpointX<this.larguraMundo-300;this.checkpoint=checkpointValido?salvo.checkpointX:120;this.cavaleiro.x=this.checkpoint;this.ultimaPosicaoSegura={x:this.checkpoint,y:this.pisoAbaixo(this.checkpoint,0)-120};if(checkpointValido){this.cavaleiro.invulneravel=true;this.time.delayedCall(900,()=>this.cavaleiro.invulneravel=false);}this.cavaleiro.aplicarRoupa(salvo.skin);this.cavaleiro.aplicarEquipamento(salvo.equipado);this.portas.forEach((p,i)=>{if(checkpointValido&&i<salvo.portasAbertas){p.aberta=true;p.sprite.setFrame(1);p.sprite.disableBody();}});this.vidas=salvo.dificuldade==='aventura'?2:4;this.atualizarVidas();
        this.cursores=this.input.keyboard!.createCursorKeys();this.teclas=this.input.keyboard!.addKeys('A,D,S,Z,X,J,P,SHIFT,SPACE') as Record<string,Phaser.Input.Keyboard.Key>;
        this.input.keyboard!.on('keydown-Z',()=>this.atacar());this.input.keyboard!.on('keydown-J',()=>this.atacar());
        this.input.keyboard!.on('keydown-SHIFT',()=>this.dash());this.input.keyboard!.on('keydown-P',()=>this.alternarPausa());
        this.input.keyboard!.on('keyup-UP',()=>this.cavaleiro.encerrarPulo());this.input.keyboard!.on('keyup-SPACE',()=>this.cavaleiro.encerrarPulo());
        this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>{servicoVoz.parar();audioJogo.pararMusicaReino();});
        audioJogo.iniciarMusicaReino();this.mostrarDicaInicial();this.time.delayedCall(900,()=>this.mostrarAviso(`${this.aventura.icone} ${this.aventura.instrucao}`));
    }
    update():void {
        if(!this.cavaleiro||this.bloqueado)return;
        const esquerda=this.esquerdaTouch||this.cursores.left.isDown||this.teclas.A.isDown,direita=this.direitaTouch||this.cursores.right.isDown||this.teclas.D.isDown;
        const pad=this.input.gamepad?.getPad(0),eixo=pad?.axes[0]?.getValue()??0,defendendo=this.defesaTouch||this.teclas.X.isDown||this.teclas.S.isDown||this.cursores.down.isDown||(pad?.L1??0)>0;this.cavaleiro.agachar(false,false);this.cavaleiro.defender(defendendo);this.cavaleiro.mover(this.cavaleiro.defendendo?0:Math.abs(eixo)>.25?Math.sign(eixo):esquerda?-1:direita?1:0,false);
        const gpPulo=!!pad?.buttons[0]?.pressed,gpAtaque=!!pad?.buttons[2]?.pressed;if(gpPulo&&!this.gamepadPuloAntes)this.pular();if(gpAtaque&&!this.gamepadAtaqueAntes)this.atacar();this.gamepadPuloAntes=gpPulo;this.gamepadAtaqueAntes=gpAtaque;
        if(Phaser.Input.Keyboard.JustDown(this.cursores.up)||Phaser.Input.Keyboard.JustDown(this.cursores.space)||Phaser.Input.Keyboard.JustDown(this.teclas.SPACE))this.pular();
        this.cavaleiro.sustentarPulo(this.cursores.up.isDown||this.cursores.space.isDown||this.teclas.SPACE.isDown||gpPulo);
        this.atualizarPocao();this.atualizarPlataformasMoveis();this.atualizarPlataformasEspeciais();this.atualizarAventura();this.atualizarPosicaoSegura();this.inimigos.forEach(inimigo=>{inimigo.atualizar();if(inimigo.corpoColisao.y>650)inimigo.derrotar();});this.verificarPortas();this.atualizarEstadoPortal();this.atualizarRegiao();const inicioEntardecer=this.larguraMundo*.65,extensaoEntardecer=this.larguraMundo*.32;this.filtroEntardecer.setAlpha(Phaser.Math.Clamp((this.cavaleiro.x-inicioEntardecer)/extensaoEntardecer,0,1)*.16);this.deslocamentoCamera=Phaser.Math.Linear(this.deslocamentoCamera,-this.cavaleiro.olhando*72,.045);this.cameras.main.setFollowOffset(this.deslocamentoCamera,45);if(this.cavaleiro.y>620)this.cairNoAbismo();
    }
    private criarCenario():void {
        const tema=REGIOES_REINO[this.faseAtual];
        this.add.image(480,320,`reino-fundo-${tema.id}`).setDisplaySize(1138,640).setScrollFactor(0).setDepth(-30);
    }
    private criarAnimacoes():void {
        if(!this.anims.exists('reino-idle'))this.anims.create({key:'reino-idle',frames:this.anims.generateFrameNumbers('reino-cavaleiro',{frames:[0]}),frameRate:1,repeat:-1});
        if(!this.anims.exists('reino-correr'))this.anims.create({key:'reino-correr',frames:this.anims.generateFrameNumbers('reino-cavaleiro',{frames:[2,3,4]}),frameRate:9,repeat:-1});
        if(!this.anims.exists('reino-atacar'))this.anims.create({key:'reino-atacar',frames:this.anims.generateFrameNumbers('reino-cavaleiro',{frames:[7,8,7]}),frameRate:14,repeat:0});
        ['espada-rapida','lanca','martelo','arco'].forEach(tipo=>{if(!this.anims.exists(`reino-cavaleiro-${tipo}-idle`))this.anims.create({key:`reino-cavaleiro-${tipo}-idle`,frames:this.anims.generateFrameNumbers(`reino-cavaleiro-${tipo}`,{frames:[0]}),frameRate:1,repeat:-1});if(!this.anims.exists(`reino-cavaleiro-${tipo}-correr`))this.anims.create({key:`reino-cavaleiro-${tipo}-correr`,frames:this.anims.generateFrameNumbers(`reino-cavaleiro-${tipo}`,{frames:[2,3,4]}),frameRate:9,repeat:-1});if(!this.anims.exists(`reino-cavaleiro-${tipo}-atacar`))this.anims.create({key:`reino-cavaleiro-${tipo}-atacar`,frames:this.anims.generateFrameNumbers(`reino-cavaleiro-${tipo}`,{frames:[7,8,7]}),frameRate:14,repeat:0});});
        if(!this.anims.exists('reino-slime-mover'))this.anims.create({key:'reino-slime-mover',frames:this.anims.generateFrameNumbers('reino-slime',{frames:[0,1,2]}),frameRate:5,repeat:-1});
    }
    private criarPlataformas():void {
        this.plataformas=this.physics.add.staticGroup();
        this.plataformasMoveis=this.physics.add.group({allowGravity:false,immovable:true});this.perigos=this.physics.add.staticGroup();this.barreirasInimigos=this.physics.add.staticGroup();
        const estado=progressoReino.carregar(),frame=this.faseAtual;this.nivel=gerarNivelReino(this.faseAtual,estado.levelSeed);const erros=validarNivelReino(this.nivel);if(erros.length)throw new Error(`Nível inválido: ${erros.join(', ')}`);
        this.nivel.terrenos.forEach(t=>criarSuperficie(this,this.plataformas,t.x,t.topo+48,t.largura,96,76,'reino-terrenos-biomas',frame));
        this.nivel.gaps.forEach(g=>[g.inicio-6,g.fim+6].forEach(x=>this.barreirasInimigos.add(this.add.rectangle(x,470,12,180,0xffffff,0))));
        this.nivel.plataformas.forEach(p=>{if(p.movel){const superficie=criarSuperficieMovel(this,this.plataformasMoveis,p.x,p.topo+22,p.largura,44,26,'reino-terrenos-biomas',frame),corpo=superficie.corpo.body as Phaser.Physics.Arcade.Body,vertical=p.movel==='y',amplitude=vertical?52:68,velocidade=48,valor=vertical?superficie.corpo.y:superficie.corpo.x;superficie.corpo.setData('atravessavel',true);corpo.setVelocity(vertical?0:velocidade,vertical?-velocidade:0);this.movimentosPlataformas.push({...superficie,eixo:p.movel,inicio:valor-amplitude,fim:valor+amplitude,velocidade,ultimo:valor});}else {const corpo=criarSuperficie(this,this.plataformas,p.x,p.topo+22,p.largura,44,26,'reino-terrenos-biomas',frame);(corpo.gameObject as Phaser.GameObjects.GameObject).setData('atravessavel',true);if(p.especial)this.plataformasEspeciais.push({corpo,tipo:p.especial});}});
        this.criarPerigosCenario();
    }
    private configurarPlataformaEspecial(corpo:Phaser.Physics.Arcade.Body|Phaser.Physics.Arcade.StaticBody,tipo:'quebravel'|'impulso'):void {const objeto=corpo.gameObject as Phaser.GameObjects.Rectangle,visual=objeto.getData('visual') as Phaser.GameObjects.TileSprite;visual.setTint(tipo==='impulso'?0x9ce66d:0xc9a47a);const plataforma=this.plataformasEspeciais.find(p=>p.corpo===corpo);if(plataforma)plataforma.ativa=true;}
    private atualizarPlataformasEspeciais():void {const corpoCavaleiro=this.cavaleiro.body as Phaser.Physics.Arcade.Body;if(!corpoCavaleiro.blocked.down)return;const plataforma=this.plataformasEspeciais.find(p=>p.ativa!==false&&p.corpo.enable&&corpoCavaleiro.right>p.corpo.left+4&&corpoCavaleiro.left<p.corpo.right-4&&Math.abs(corpoCavaleiro.bottom-p.corpo.top)<6);if(!plataforma)return;const objeto=plataforma.corpo.gameObject as Phaser.GameObjects.Rectangle,visual=objeto.getData('visual') as Phaser.GameObjects.TileSprite;if(plataforma.tipo==='impulso'){this.cavaleiro.setVelocityY(-680);audioJogo.efeito('pulo');this.tweens.add({targets:visual,scaleY:.72,duration:90,yoyo:true});return;}plataforma.ativa=false;this.tweens.add({targets:visual,x:visual.x+5,duration:45,yoyo:true,repeat:4,onComplete:()=>{plataforma.corpo.enable=false;visual.setVisible(false);this.time.delayedCall(1800,()=>{visual.setVisible(true);plataforma.corpo.enable=true;plataforma.corpo.updateFromGameObject();plataforma.ativa=true;});}});}
    private podeApoiarCavaleiro(_cavaleiro:Phaser.Types.Physics.Arcade.GameObjectWithBody|Phaser.Physics.Arcade.Body|Phaser.Physics.Arcade.StaticBody|Phaser.Tilemaps.Tile,plataforma:Phaser.Types.Physics.Arcade.GameObjectWithBody|Phaser.Physics.Arcade.Body|Phaser.Physics.Arcade.StaticBody|Phaser.Tilemaps.Tile):boolean {const objeto=('gameObject' in plataforma?plataforma.gameObject:plataforma) as Phaser.GameObjects.GameObject;if(!objeto.getData?.('atravessavel'))return true;const heroi=this.cavaleiro.body as Phaser.Physics.Arcade.Body,apoio=('body' in plataforma?plataforma.body:plataforma) as Phaser.Physics.Arcade.Body;return heroi.velocity.y>=0&&heroi.prev.y+heroi.height<=apoio.top+10;}
    private pisoAbaixo(x:number,y:number):number {const superficie=superficieAbaixo(x,y,[this.plataformas,this.plataformasMoveis]);if(!superficie)throw new Error(`Nenhuma superfície abaixo de (${x}, ${y})`);return superficie.top;}
    private pisoOpcional(x:number,y=0):number|undefined {return superficieAbaixo(x,y,[this.plataformas,this.plataformasMoveis])?.top;}
    private criarPerigosCenario():void {
        const tema=REGIOES_REINO[this.faseAtual].id,espinhosBase=[820,1730,3380,4930];
        const espinhos=(tema==='fogo'||tema==='castelo'?[...espinhosBase,1320,4380]:espinhosBase).filter(x=>!POSICOES_PORTAS.some(porta=>Math.abs(x-porta)<280));
        const lavas=tema==='fogo'?[1180,2260,3540,4620,5350]:[];
        const adicionarZona=(x:number,y:number,w:number,h:number)=>{const zona=this.add.rectangle(x,y,w,h,0xffffff,0);this.perigos.add(zona);(zona.body as Phaser.Physics.Arcade.StaticBody).updateFromGameObject();};
        espinhos.forEach(x=>{const largura=tema==='fogo'?72:60,piso=this.pisoOpcional(x);if(piso===undefined)return;assentarTerrestre(this.add.image(x,piso,'reino-espinhos').setDisplaySize(largura,32).setDepth(5),piso);adicionarZona(x,piso-9,largura-8,18);});
        if(tema==='fogo')this.nivel.gaps.forEach((gap,i)=>{const x=(gap.inicio+gap.fim)/2,largura=gap.fim-gap.inicio+18,base=this.add.image(x,594,'reino-lava').setDisplaySize(largura,38).setDepth(2);this.tweens.add({targets:base,alpha:.72,duration:700+i*45,yoyo:true,repeat:-1,ease:'Sine.InOut'});});
        lavas.forEach((x,i)=>{const largura=tema==='fogo'?112:92,piso=this.pisoOpcional(x);if(piso===undefined)return;const base=assentarTerrestre(this.add.image(x,piso,'reino-lava').setDisplaySize(largura,35).setDepth(5),piso);this.tweens.add({targets:base,alpha:.72,duration:700+i*70,yoyo:true,repeat:-1,ease:'Sine.InOut'});adicionarZona(x,piso-9,largura-10,17);});
    }
    private atualizarPlataformasMoveis():void {this.movimentosPlataformas.forEach(m=>{const corpo=m.corpo.body as Phaser.Physics.Arcade.Body,corpoCavaleiro=this.cavaleiro.body as Phaser.Physics.Arcade.Body,valor=m.eixo==='x'?m.corpo.x:m.corpo.y,delta=valor-m.ultimo,sobre=corpoCavaleiro.blocked.down&&corpoCavaleiro.right>corpo.left+5&&corpoCavaleiro.left<corpo.right-5&&Math.abs(corpoCavaleiro.bottom-corpo.top)<9;if(sobre){if(m.eixo==='x')this.cavaleiro.x+=delta;else this.cavaleiro.y+=delta;}m.ultimo=valor;if(valor<=m.inicio){if(m.eixo==='x')corpo.setVelocityX(m.velocidade);else corpo.setVelocityY(m.velocidade);}else if(valor>=m.fim){if(m.eixo==='x')corpo.setVelocityX(-m.velocidade);else corpo.setVelocityY(-m.velocidade);}});}
    private criarMoedas():void {
        const pontos=this.nivel.moedas.map(({x,y})=>[x,y] as [number,number]);
        pontos.forEach(([x,y])=>{const moeda=this.physics.add.sprite(x,y,'reino-objetos',2).setDisplaySize(46,46).setDepth(6);const body=moeda.body as Phaser.Physics.Arcade.Body;body.setAllowGravity(false).setSize(190,190).setOffset(82,126);this.tweens.add({targets:moeda,y:y-3,angle:4,yoyo:true,repeat:-1,duration:1300+Phaser.Math.Between(0,300),ease:'Sine.InOut'});const brilho=this.add.circle(x,y,25,0xffed91,.1).setDepth(5);this.tweens.add({targets:brilho,scale:1.18,alpha:.03,yoyo:true,repeat:-1,duration:1200});this.physics.add.overlap(this.cavaleiro,moeda,()=>{if(!moeda.active)return;brilho.destroy();moeda.disableBody(true,true);this.adicionarMoedas(1);audioJogo.efeito('moeda');this.criarParticulas(moeda.x,moeda.y,0xffd85a,12);});});
    }
    private adicionarMoedas(quantidade:number):void {this.moedas+=quantidade;const estado=progressoReino.carregar(),total=estado.moedas+quantidade;progressoReino.salvar({moedas:total});this.textoMoedas?.setText(`${total}`);}
    private criarPocoes():void {
        const pantano=REGIOES_REINO[this.faseAtual].id==='pantano',pontos:[number,number,TipoPocao][]=pantano?[[520,492,'veloz'],[1220,492,'salto'],[2420,492,'escudo'],[3760,492,'veloz'],[4680,492,'salto'],[5480,492,'escudo']]:[[1180,492,(this.faseAtual%3===0?'veloz':this.faseAtual%3===1?'salto':'escudo')],[4380,492,(this.faseAtual%3===0?'escudo':this.faseAtual%3===1?'veloz':'salto')]];
        const frames:Record<TipoPocao,number>={veloz:1,salto:2,escudo:3};pontos.forEach(([x,y,tipo])=>{const cfg=POCOES[tipo],pocao=this.physics.add.sprite(x,y,'reino-itens-magicos',frames[tipo]).setDisplaySize(52,58).setDepth(6),body=pocao.body as Phaser.Physics.Arcade.Body;body.setAllowGravity(false).setSize(280,330).setOffset(116,95);const brilho=this.add.circle(x,y,28,cfg.cor,.14).setDepth(5);this.tweens.add({targets:[pocao,brilho],y:y-5,duration:1100+Phaser.Math.Between(0,180),yoyo:true,repeat:-1,ease:'Sine.InOut'});this.tweens.add({targets:brilho,scale:1.25,alpha:.03,duration:900,yoyo:true,repeat:-1});this.physics.add.overlap(this.cavaleiro,pocao,()=>{if(!pocao.active)return;pocao.disableBody(true,true);brilho.destroy();this.ativarPocao(tipo,pocao.x,pocao.y);});});
    }
    private ativarPocao(tipo:TipoPocao,x:number,y:number):void {const cfg=POCOES[tipo];this.pocaoAtiva=tipo;this.pocaoAte=this.time.now+cfg.duracao;this.cavaleiro.definirEfeitoPocao(tipo==='veloz'?1.48:1,tipo==='salto'?1.28:1);this.auraPocao?.destroy();this.auraPocao=this.add.circle(this.cavaleiro.x,this.cavaleiro.y,52,cfg.cor,.12).setStrokeStyle(4,cfg.corClara,.78).setDepth(7);this.tweens.add({targets:this.auraPocao,scale:1.16,alpha:.25,duration:480,yoyo:true,repeat:-1,ease:'Sine.InOut'});this.criarParticulas(x,y,cfg.cor,28);audioJogo.efeito('moeda');const texto=this.add.text(x,y-45,cfg.texto,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'19px',fontStyle:'bold',color:`#${cfg.corClara.toString(16).padStart(6,'0')}`,stroke:'#244d42',strokeThickness:5}).setOrigin(.5).setDepth(95);this.tweens.add({targets:texto,y:y-105,alpha:0,duration:1100,ease:'Cubic.Out',onComplete:()=>texto.destroy()});this.atualizarVisualHudPocao();}
    private atualizarPocao():void {if(!this.pocaoAtiva)return;if(this.time.now>=this.pocaoAte){this.encerrarPocao();return;}this.auraPocao?.setPosition(this.cavaleiro.x,this.cavaleiro.y);const cfg=POCOES[this.pocaoAtiva],restante=this.pocaoAte-this.time.now,progresso=Phaser.Math.Clamp(restante/cfg.duracao,0,1);this.barraPocao?.clear().fillStyle(0x173d34,.72).fillRoundedRect(0,27,176,7,4).fillStyle(cfg.cor,1).fillRoundedRect(0,27,176*progresso,7,4);this.textoPocao?.setText(`${cfg.nome}  ${Math.ceil(restante/1000)}s`);}
    private encerrarPocao():void {this.pocaoAtiva=undefined;this.pocaoAte=0;this.cavaleiro.definirEfeitoPocao();this.auraPocao?.destroy();this.auraPocao=undefined;this.hudPocao?.setVisible(false);}
    private atualizarVisualHudPocao():void {if(!this.pocaoAtiva||!this.hudPocao)return;const cfg=POCOES[this.pocaoAtiva],icone=this.hudPocao.getByName('icone') as Phaser.GameObjects.Image|undefined,frames:Record<TipoPocao,number>={veloz:1,salto:2,escudo:3};icone?.setTexture('reino-itens-magicos',frames[this.pocaoAtiva]);this.textoPocao?.setColor(`#${cfg.corClara.toString(16).padStart(6,'0')}`);this.hudPocao.setVisible(true);}
    private criarInimigos():void {
        INIMIGOS_POR_REGIAO[REGIOES_REINO[this.faseAtual].id].filter(({x,tipo})=>x<5250||tipo==='morcego').filter(({x,tipo})=>tipo==='morcego'||tipo==='furacao'||!sobrepoeGap(this.nivel,x,60)&&this.pisoOpcional(x)!==undefined).forEach(({x,y,tipo})=>{let inimigo:InimigoReino;if(tipo!=='morcego'&&tipo!=='furacao')y=this.pisoAbaixo(x,0)-120;
            if(tipo==='morcego')inimigo=new MorcegoReino(this,x,y,this.cavaleiro);
            else if(tipo==='cogumelo')inimigo=new CogumeloSaltadorReino(this,x,y,this.cavaleiro);
            else if(tipo==='furacao')inimigo=new FuracaoFolhasReino(this,x,y);
            else if(tipo==='arqueiro')inimigo=new ArqueiroReino(this,x,y,this.cavaleiro,()=>this.dano(inimigo));
            else if(tipo==='espantalho')inimigo=new CavaleiroEspantalhoReino(this,x,y,this.cavaleiro);
            else if(tipo==='goblin')inimigo=new GoblinReino(this,x,y,this.cavaleiro,()=>this.dano(inimigo));
            else if(tipo==='golem-lava'||tipo==='diabrete-fogo')inimigo=new InimigoFogoReino(this,x,y,tipo);
            else if(tipo==='planta')inimigo=new PlantaReino(this,x,this.pisoAbaixo(x,0));
            else inimigo=new SlimeReino(this,x,y);
            this.inimigos.push(inimigo);if(inimigo.colideComPlataformas){this.physics.add.collider(inimigo.corpoColisao,this.plataformas);this.physics.add.collider(inimigo.corpoColisao,this.plataformasMoveis);this.physics.add.collider(inimigo.corpoColisao,this.barreirasInimigos);}this.physics.add.overlap(this.cavaleiro,inimigo.corpoColisao,()=>this.dano(inimigo));
        });
        const mimico=new MimicoPortaReino(this,5520,480,this.cavaleiro,Math.floor(this.faseAtual/2),REGIOES_REINO[this.faseAtual].id);this.inimigos.push(mimico);this.physics.add.collider(mimico,this.plataformas);this.physics.add.overlap(this.cavaleiro,mimico,()=>this.dano(mimico));
    }
    private criarPortas():void {
        const tipos=escolherTiposDaJornada(progressoReino.carregar().challenges,POSICOES_PORTAS.length);
        POSICOES_PORTAS.forEach((x,i)=>{const d={x,tipo:tipos[i]};
            const piso=this.pisoAbaixo(d.x,0),sprite=this.physics.add.staticSprite(d.x,piso-81,'reino-objetos',0).setDisplaySize(132,190).setDepth(6),emblema=this.criarEmblemaCategoria(d.tipo,d.x,piso-213,1).setDepth(8);const body=sprite.body as Phaser.Physics.Arcade.StaticBody;body.setSize(100,180).setOffset(130,230);this.physics.add.collider(this.cavaleiro,sprite);this.tweens.add({targets:emblema,y:emblema.y-9,scale:1.06,duration:900+i*130,yoyo:true,repeat:-1,ease:'Sine.InOut'});this.portas.push({...d,sprite,emblema,aberta:false});
        });
    }
    private criarAventura():void {
        this.aventura=AVENTURAS_REINO[this.faseAtual];const salvo=progressoReino.carregar(),compativel=salvo.aventura.fase===this.faseAtual&&salvo.aventura.seed===salvo.levelSeed;this.eventosAventura=new Set(compativel?salvo.aventura.eventos:[]);
        if(this.aventura.tipo==='chave'){this.criarBloqueioAventura(this.aventura.bloqueio!,'portao-ambiental');this.criarColetavelAventura(this.aventura.posicoes[0],'chave-obtida','🔑',0xffd65b);}
        else if(this.aventura.tipo==='placa')this.criarPuzzlePlaca();
        else if(this.aventura.tipo==='cristais')this.aventura.posicoes.forEach((x,i)=>this.criarColetavelAventura(x,`cristal-${i+1}`,'◆',0x68e5ef));
        else if(this.aventura.tipo==='paginas')this.aventura.posicoes.forEach((x,i)=>this.criarColetavelAventura(x,`pagina-${i+1}`,'▤',0xf5d987));
        else if(this.aventura.tipo==='resgate')this.criarResgateAventura(this.aventura.posicoes[0]);
        else if(this.aventura.tipo==='alavanca')this.criarMecanismoPonte(this.aventura.posicoes[0],false);
        else if(this.aventura.tipo==='corda')this.criarMecanismoPonte(this.aventura.posicoes[0],true);
        else if(this.eventosAventura.has('guardiao-derrotado'))this.inimigos.find(i=>i instanceof MimicoPortaReino&&!i.derrotado)?.derrotar();
    }
    private criarColetavelAventura(x:number,evento:string,icone:string,cor:number):void {if(this.eventosAventura.has(evento))return;const piso=this.pisoAbaixo(x,0),c=this.add.container(x,piso-72).setDepth(8),halo=this.add.circle(0,0,28,cor,.17),simbolo=this.add.text(0,0,icone,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'30px',fontStyle:'bold',color:'#ffffff',stroke:`#${cor.toString(16).padStart(6,'0')}`,strokeThickness:5}).setOrigin(.5);c.add([halo,simbolo]);this.tweens.add({targets:c,y:c.y-9,duration:720,yoyo:true,repeat:-1,ease:'Sine.InOut'});this.tweens.add({targets:halo,scale:1.35,alpha:.04,duration:620,yoyo:true,repeat:-1});const zona=this.physics.add.staticImage(x,piso-72,'reino-objetos',2).setVisible(false).setSize(58,72);this.physics.add.overlap(this.cavaleiro,zona,()=>{if(!zona.active)return;zona.disableBody(true,true);if(!this.registrarEventoAventura(evento))return;audioJogo.efeito('moeda');this.criarParticulas(x,piso-72,cor,24);this.tweens.add({targets:c,y:c.y-35,alpha:0,scale:1.4,duration:320,onComplete:()=>c.destroy(true)});});}
    private criarBloqueioAventura(x:number,evento:string):void {if(this.eventosAventura.has(evento))return;const piso=this.pisoAbaixo(x,0),visual=this.add.container(x,piso-80).setDepth(7),g=this.add.graphics().fillStyle(0x596670,.96).fillRoundedRect(-39,-82,78,164,10).lineStyle(5,0xd6ba69,.9).strokeRoundedRect(-39,-82,78,164,10);for(let dx=-24;dx<=24;dx+=16)g.lineStyle(6,0x303a42,.9).lineBetween(dx,-72,dx,70);visual.add([g,this.add.text(0,-18,'🔒',{fontFamily:'Arial',fontSize:'25px'}).setOrigin(.5)]);const objeto=this.add.rectangle(x,piso-80,78,164,0xffffff,0);this.plataformas.add(objeto);const corpo=objeto.body as Phaser.Physics.Arcade.StaticBody;corpo.updateFromGameObject();this.bloqueioAventura={x,corpo,visual};}
    private abrirBloqueioAventura(evento:string):void {if(!this.registrarEventoAventura(evento))return;const bloqueio=this.bloqueioAventura;if(!bloqueio)return;bloqueio.corpo.enable=false;audioJogo.efeito('porta');this.criarParticulas(bloqueio.x,bloqueio.visual.y,0xffd86b,30);this.tweens.add({targets:bloqueio.visual,y:bloqueio.visual.y-145,alpha:0,duration:650,ease:'Back.In',onComplete:()=>bloqueio.visual.destroy(true)});this.bloqueioAventura=undefined;}
    private criarPuzzlePlaca():void {if(this.eventosAventura.has('placa-ativada'))return;const [xCaixa,xPlaca]=this.aventura.posicoes;this.criarBloqueioAventura(this.aventura.bloqueio!,'placa-ativada');const pisoCaixa=this.pisoAbaixo(xCaixa,0),pisoPlaca=this.pisoAbaixo(xPlaca,0),placa=this.add.rectangle(xPlaca,pisoPlaca-5,92,10,0xd7a84d,1).setStrokeStyle(3,0xffe89b,.9).setDepth(5);this.tweens.add({targets:placa,alpha:.65,duration:550,yoyo:true,repeat:-1});const caixa=this.physics.add.image(xCaixa,pisoCaixa-48,'reino-prop-bau-tonel').setDisplaySize(68,52).setDepth(8).setDragX(120).setMaxVelocity(150,650);const corpo=caixa.body as Phaser.Physics.Arcade.Body;corpo.setSize(55,48).setBounce(0);this.physics.add.collider(caixa,this.plataformas);this.physics.add.collider(this.cavaleiro,caixa);this.caixaAventura=caixa;this.caixaInicio={x:xCaixa,y:pisoCaixa-48};this.placaAventuraX=xPlaca;}
    private criarResgateAventura(x:number):void {const piso=this.pisoAbaixo(x,0);if(this.eventosAventura.has('amigo-liberto')){this.add.sprite(x,piso,'reino-companheiro-raposa-mover',0).setDisplaySize(66,48).setOrigin(.5,1).setDepth(6).play('reino-companheiro-raposa-mover');return;}const c=this.add.container(x,piso-52).setDepth(7),amigo=this.add.sprite(0,34,'reino-companheiro-raposa-mover',0).setDisplaySize(58,42).setOrigin(.5,1).play('reino-companheiro-raposa-mover'),grade=this.add.graphics().lineStyle(6,0x596670,.95).strokeRoundedRect(-38,-48,76,96,8);for(let dx=-24;dx<=24;dx+=16)grade.lineBetween(dx,-43,dx,43);c.add([amigo,grade]);const zona=this.physics.add.staticImage(x,piso-52,'reino-objetos',2).setVisible(false).setSize(90,110);this.physics.add.overlap(this.cavaleiro,zona,()=>{if(!zona.active)return;zona.disableBody(true,true);if(!this.registrarEventoAventura('amigo-liberto'))return;audioJogo.efeito('porta');this.criarParticulas(x,piso-65,0x9ce89b,32);this.tweens.add({targets:grade,alpha:0,y:grade.y-70,duration:450,onComplete:()=>grade.destroy()});this.tweens.add({targets:amigo,x:85,duration:650,ease:'Sine.InOut'});});}
    private criarMecanismoPonte(x:number,corda:boolean):void {const evento=corda?'corda-cortada':'ponte-ativada';if(this.eventosAventura.has(evento)){this.criarPonteAventura();return;}const piso=this.pisoAbaixo(x,0),visual=this.add.container(x,piso-78).setDepth(7),g=this.add.graphics();if(corda){const rocha=[new Phaser.Math.Vector2(-31,-125),new Phaser.Math.Vector2(-18,-151),new Phaser.Math.Vector2(12,-156),new Phaser.Math.Vector2(34,-136),new Phaser.Math.Vector2(27,-109),new Phaser.Math.Vector2(-7,-98),new Phaser.Math.Vector2(-29,-108)];g.fillStyle(0x59636b).fillPoints(rocha,true).lineStyle(4,0x89949a,.9).strokePoints(rocha,true).fillStyle(0x3f484f,.55).fillCircle(-10,-130,7).fillCircle(15,-117,5).lineStyle(7,0xb9905b).lineBetween(0,-101,0,25);}else g.fillStyle(0x5b6670).fillRoundedRect(-10,-8,20,75,7).lineStyle(10,0xd5a34e).lineBetween(0,-5,27,-42);visual.add([g,this.add.text(0,corda?-42:-75,corda?'✂':'⚙',{fontFamily:'Arial',fontSize:'24px',color:'#fff4b8',stroke:'#30473f',strokeThickness:4}).setOrigin(.5)]);const acao=()=>{if(!this.registrarEventoAventura(evento))return;audioJogo.efeito('porta');this.cameras.main.shake(180,.006);this.criarParticulas(x,piso-75,corda?0xd9b77c:0xffd86b,28);if(corda)this.tweens.add({targets:visual,y:piso+30,angle:18,alpha:0,duration:520,onComplete:()=>visual.destroy(true)});else this.tweens.add({targets:visual,angle:28,duration:180,yoyo:true,onComplete:()=>visual.setAngle(28)});this.time.delayedCall(280,()=>this.criarPonteAventura());};this.mecanismosAventura.push({x,y:piso-78,evento,acao});}
    private criarPonteAventura():void {if(this.ponteAventuraCriada)return;this.ponteAventuraCriada=true;const gap=this.nivel.gaps[1]??this.nivel.gaps[0];if(!gap)return;const largura=(gap.fim-gap.inicio+36)/3;for(let i=0;i<3;i++){const x=gap.inicio-18+largura*(i+.5),corpo=criarSuperficie(this,this.plataformas,x,520,largura-5,44,26,'reino-terrenos-biomas',this.faseAtual),objeto=corpo.gameObject as Phaser.GameObjects.Rectangle,visual=objeto.getData('visual') as Phaser.GameObjects.Image;objeto.setData('atravessavel',true);visual.setAlpha(0).setY(visual.y-65);this.tweens.add({targets:visual,y:visual.y+65,alpha:1,duration:360+i*90,ease:'Back.Out'});}}
    private atualizarAventura():void {if(this.aventura.tipo==='chave'&&this.eventosAventura.has('chave-obtida')&&!this.eventosAventura.has('portao-ambiental')&&this.bloqueioAventura&&Math.abs(this.cavaleiro.x-this.bloqueioAventura.x)<125)this.abrirBloqueioAventura('portao-ambiental');const caixa=this.caixaAventura;if(!caixa||!this.caixaInicio||this.eventosAventura.has('placa-ativada'))return;const corpo=caixa.body as Phaser.Physics.Arcade.Body;if(caixa.y>620||caixa.x<this.caixaInicio.x-230||caixa.x>this.placaAventuraX+150)caixa.setPosition(this.caixaInicio.x,this.caixaInicio.y).setVelocity(0);else if(Math.abs(caixa.x-this.placaAventuraX)<46&&corpo.blocked.down)this.abrirBloqueioAventura('placa-ativada');}
    private acionarMecanismoProximo(alcance:number):void {const mecanismo=this.mecanismosAventura.find(m=>{const dx=(m.x-this.cavaleiro.x)*this.cavaleiro.olhando;return !this.eventosAventura.has(m.evento)&&dx>-20&&dx<alcance&&Math.abs(m.y-this.cavaleiro.y)<130;});mecanismo?.acao();}
    private registrarEventoAventura(evento:string):boolean {if(this.eventosAventura.has(evento))return false;const concluidoAntes=this.objetivoAventuraConcluido();this.eventosAventura.add(evento);progressoReino.salvar({aventura:{fase:this.faseAtual,seed:progressoReino.carregar().levelSeed,eventos:[...this.eventosAventura]}});this.atualizarHudObjetivo();if(!concluidoAntes&&this.objetivoAventuraConcluido()){this.mostrarAviso(`✓ ${this.aventura.nome} concluído!`);this.criarParticulas(this.cavaleiro.x,this.cavaleiro.y-35,REGIOES_REINO[this.faseAtual].corDestaque,30);}return true;}
    private objetivoAventuraConcluido():boolean {return !!this.aventura&&this.aventura.eventos.every(e=>this.eventosAventura.has(e));}
    private atualizarHudObjetivo():void {if(!this.textoObjetivo||!this.aventura)return;const feitos=this.aventura.eventos.filter(e=>this.eventosAventura.has(e)).length,completo=feitos===this.aventura.eventos.length,progresso=this.aventura.eventos.length>1?` ${feitos}/${this.aventura.eventos.length}`:'';this.textoObjetivo.setText(`${completo?'✓':this.aventura.icone} ${this.aventura.nome}${progresso}`).setColor(completo?'#bff3be':'#fff4c2');}
    private corCategoria(tipo:TipoDesafio):number {return DISCIPLINA_DESAFIO[tipo]==='matematica'?0xf29b38:0x7569d8;}
    private criarEmblemaCategoria(tipo:TipoDesafio,x:number,y:number,escala=1):Phaser.GameObjects.Container {
        const cor=this.corCategoria(tipo),c=this.add.container(x,y).setScale(escala),halo=this.add.circle(0,0,34,cor,.18),g=this.add.graphics();g.fillStyle(0xfff9e9,1).fillCircle(0,0,27).lineStyle(5,cor,1).strokeCircle(0,0,27).fillStyle(cor,.16).fillCircle(0,0,20);const rotulo=DISCIPLINA_DESAFIO[tipo]==='matematica'?'123':'Aa',t=this.add.text(0,0,rotulo,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'18px',fontStyle:'bold',color:`#${cor.toString(16).padStart(6,'0')}`}).setOrigin(.5);c.add([halo,g,t]);this.tweens.add({targets:halo,alpha:.04,scale:1.28,duration:760,yoyo:true,repeat:-1,ease:'Sine.InOut'});return c;
    }
    private criarSegredos():void {[[2250,0],[2850,0],[4250,0],[5650,0]].forEach(([x,y])=>{const piso=this.pisoAbaixo(x,y),bau=assentarTerrestre(this.add.image(x,piso,'reino-prop-bau-tonel').setDisplaySize(72,54).setDepth(6),piso),zona=this.physics.add.staticImage(x,piso-22,'reino-objetos',2).setVisible(false).setSize(62,44);this.physics.add.overlap(this.cavaleiro,zona,()=>{if(!zona.active)return;zona.disableBody(true,true);this.tweens.add({targets:bau,y:bau.y-18,alpha:0,duration:300,onComplete:()=>bau.destroy()});this.adicionarMoedas(3);audioJogo.efeito('moeda');this.criarParticulas(x,piso-22,this.regiaoEm(x).corDestaque,20);});});}
    private criarColecionaveis():void {
        const tema=REGIOES_REINO[this.faseAtual],id=tema.id,estado=progressoReino.carregar();
        const posicoesGemas:[[number,number],[number,number],[number,number],[number,number],[number,number],[number,number],[number,number],[number,number]]=[[1050,345],[650,415],[2050,335],[3100,310],[4200,330],[4750,410],[5250,315],[5700,400]];
        const posicoesPergaminhos:[[number,number],[number,number],[number,number],[number,number],[number,number],[number,number],[number,number],[number,number]]=[[350,505],[1450,415],[2550,405],[3650,400],[4750,415],[5250,315],[5900,505],[250,505]];
        const fatos=[
            '“Número” vem do latim numerus: contar também conta histórias!',
            'Palavras são formadas por sílabas, como VI-LA.',
            'Um eco repete o som: leia em voz alta e escute!',
            'Triângulos têm 3 lados; quadrados têm 4.',
            'Poção rima com coração: as duas terminam em “ão”.',
            'Biblioteca é um lugar cheio de livros e descobertas.',
            'Rei e reino pertencem à mesma família de palavras.',
            'Chama pode ser fogo ou o verbo chamar!'
        ];
        if(!estado.gemasColetadas.includes(id)){
            const [x,y]=posicoesGemas[this.faseAtual],gema=this.add.container(x,y).setDepth(7),halo=this.add.circle(0,0,27,0x72e7ff,.2),g=this.add.graphics().fillStyle(0x65d9ef,1).fillTriangle(0,-25,19,-7,12,21).fillTriangle(0,-25,-19,-7,-12,21).fillStyle(0xcaf8ff,.9).fillTriangle(0,-20,0,14,-13,-6).lineStyle(3,0xffdf72,1).strokePoints([new Phaser.Math.Vector2(0,-25),new Phaser.Math.Vector2(19,-7),new Phaser.Math.Vector2(12,21),new Phaser.Math.Vector2(-12,21),new Phaser.Math.Vector2(-19,-7)],true);gema.add([halo,g]);this.tweens.add({targets:g,y:-7,duration:720,yoyo:true,repeat:-1,ease:'Sine.InOut'});this.tweens.add({targets:halo,scale:1.35,alpha:.05,duration:620,yoyo:true,repeat:-1});
            const zona=this.physics.add.staticImage(x,y,'reino-objetos',2).setVisible(false).setSize(54,62);this.physics.add.overlap(this.cavaleiro,zona,()=>{if(!zona.active)return;zona.disableBody(true,true);const atual=progressoReino.carregar();if(atual.gemasColetadas.includes(id))return;progressoReino.salvar({gemas:atual.gemas+1,gemasColetadas:[...atual.gemasColetadas,id]});audioJogo.efeito('moeda');this.criarParticulas(x,y,0x65d9ef,30);this.criarParticulas(x,y,0xffdf72,18);this.mostrarAviso('💎 Gema secreta encontrada!');this.tweens.add({targets:gema,y:y-30,alpha:0,scale:1.5,duration:380,onComplete:()=>gema.destroy(true)});});
        }
        if(!estado.pergaminhosColetados.includes(id)){
            const [x,y]=posicoesPergaminhos[this.faseAtual],rolo=this.add.container(x,y).setDepth(7),g=this.add.graphics().fillStyle(0xf3d58b,1).fillRoundedRect(-19,-24,38,48,5).lineStyle(3,0x8f6236,1).strokeRoundedRect(-19,-24,38,48,5).fillStyle(0xd2a55b,1).fillEllipse(0,-23,43,10).fillEllipse(0,23,43,10).lineStyle(2,0x9d713e,.7).lineBetween(-10,-9,11,-9).lineBetween(-10,-1,8,-1).lineBetween(-10,7,12,7);rolo.add(g);this.tweens.add({targets:rolo,angle:4,y:y-6,duration:850,yoyo:true,repeat:-1,ease:'Sine.InOut'});
            const zona=this.physics.add.staticImage(x,y,'reino-objetos',2).setVisible(false).setSize(56,66);this.physics.add.overlap(this.cavaleiro,zona,()=>{if(!zona.active)return;zona.disableBody(true,true);const atual=progressoReino.carregar();if(atual.pergaminhosColetados.includes(id))return;progressoReino.salvar({pergaminhos:atual.pergaminhos+1,pergaminhosColetados:[...atual.pergaminhosColetados,id]});audioJogo.efeito('moeda');this.criarParticulas(x,y,0xf3d58b,24,'farrapo');this.mostrarAviso(`📜 ${fatos[this.faseAtual]}`);this.tweens.add({targets:rolo,y:y-28,alpha:0,angle:18,duration:360,onComplete:()=>rolo.destroy(true)});});
        }
    }
    private criarComposicoesCenario():void {
        const tema=REGIOES_REINO[this.faseAtual].id;
        const apoiar=(x:number,textura:string,w:number,h:number,depth:number)=>{const piso=this.decoracaoLivre(x,w)?this.pisoOpcional(x):undefined;if(piso!==undefined)assentarTerrestre(this.add.image(x,piso,textura).setDisplaySize(w,h).setDepth(depth),piso);};
        if(tema==='bosque'||tema==='vila'){[780,2360,4100,5420].forEach(x=>apoiar(x,'reino-chao-flores',155,92,4));[1180,3800].forEach(x=>apoiar(x,'reino-arvore-colmeia',220,250,3));}if(tema==='bosque')[1320,3150,4900].forEach(x=>apoiar(x,'reino-floresta-prop',230,150,3));if(tema==='vila')[1120,2940,4600].forEach(x=>apoiar(x,'reino-fazenda-prop',195,130,3));if(tema==='caverna')[920,2620,4380].forEach(x=>apoiar(x,'reino-caverna-prop',210,145,3));
    }
    private criarAmbiente():void {
        this.criarParticulasRegionais();
    }
    private decoracaoLivre(x:number,largura:number):boolean {return !sobrepoeGap(this.nivel,x,largura)&&!this.nivel.plataformas.some(p=>Math.abs(p.x-x)<(p.largura+largura)/2+18);}
    private criarParticulasRegionais():void {
        const tema=REGIOES_REINO[this.faseAtual],xs=(n:number)=>Array.from({length:n},(_,i)=>220+i*(this.larguraMundo-440)/Math.max(1,n-1));
        if(tema.id==='bosque'){
            xs(6).filter(x=>this.decoracaoLivre(x,110)).forEach(x=>{const piso=this.pisoOpcional(x);if(piso!==undefined)assentarTerrestre(this.add.image(x,piso,'reino-chao-flores').setDisplaySize(110,65).setDepth(3),piso);});
            xs(7).forEach((x,i)=>{const b=this.add.image(x,250+i%3*55,'reino-borboletas').setDisplaySize(44,32).setDepth(4);this.tweens.add({targets:b,x:x+90,y:b.y-35,duration:1800+i*170,yoyo:true,repeat:-1,ease:'Sine.InOut'});});
        }else if(tema.id==='vila'){
            xs(5).filter(x=>this.decoracaoLivre(x,92)).forEach(x=>{const piso=this.pisoOpcional(x);if(piso!==undefined)assentarTerrestre(this.add.sprite(x,piso,'reino-galinhas-mover').setDisplaySize(92,58).setDepth(4).play('reino-galinhas-mover'),piso);});
        }else if(tema.id==='caverna'){
            xs(8).filter(x=>this.decoracaoLivre(x,140)).forEach(x=>{const piso=this.pisoOpcional(x);if(piso!==undefined)assentarTerrestre(this.add.image(x,piso,'reino-caverna-cristais').setDisplaySize(140,82).setDepth(3),piso);});
            xs(5).forEach(x=>this.add.image(x,0,'reino-caverna-estalactites').setDisplaySize(230,155).setOrigin(.5,0).setDepth(2));
            xs(12).forEach((x,i)=>{const p=this.add.circle(x,Phaser.Math.Between(180,500),3,i%2?0x9df5df:0xffeb8a,.8).setDepth(4);this.tweens.add({targets:p,alpha:.15,scale:2,x:x+25,y:p.y-35,duration:800+i*90,yoyo:true,repeat:-1,ease:'Sine.InOut'});});
        }else if(tema.id==='montanha'){
            xs(12).filter(x=>this.decoracaoLivre(x,30)).forEach((x,i)=>this.add.ellipse(x,545-(i%2)*12,18,8,0x6e8297,.32).setAngle(i%2?22:-22).setDepth(3));
        }else if(tema.id==='pantano'){
            xs(10).filter(x=>this.decoracaoLivre(x,50)).forEach((x,i)=>this.add.ellipse(x,548,34+i%3*8,13,0x91b85c,.6).setAngle(i%2?12:-12).setDepth(3));
            xs(14).forEach((x,i)=>{const bolha=this.add.circle(x,545,3+i%3,0xb9e6a2,.18).setStrokeStyle(1,0xdaf5bd,.6).setDepth(4);this.tweens.add({targets:bolha,y:490-i%4*8,alpha:0,scale:1.8,duration:900+i*85,repeat:-1,delay:i*120});});
        }else if(tema.id==='biblioteca'){
            xs(14).forEach((x,i)=>{const poeira=this.add.circle(x,Phaser.Math.Between(120,520),2,0xffefd1,.5).setDepth(3);this.tweens.add({targets:poeira,y:poeira.y-45,x:x+18,alpha:0,duration:1400+i*80,yoyo:true,repeat:-1});});
        }else if(tema.id==='fogo'){
            xs(11).filter(x=>this.decoracaoLivre(x,80)).forEach((x,i)=>{const lava=this.add.container(x,544).setDepth(3),poca=this.add.ellipse(0,0,62+i%3*9,14,0xe94b25,.72).setStrokeStyle(3,0xffa62b,.9),brilho=this.add.ellipse(0,-1,35+i%2*8,5,0xffdf67,.8);lava.add([poca,brilho]);this.tweens.add({targets:brilho,alpha:.35,duration:720+i%4*70,yoyo:true,repeat:-1,ease:'Sine.InOut'});});
            xs(18).forEach((x,i)=>{const brasa=this.add.circle(x,Phaser.Math.Between(390,535),2+i%3,i%3?0xff8a2a:0xffdd62,.9).setDepth(4);this.tweens.add({targets:brasa,y:brasa.y-Phaser.Math.Between(90,190),x:x+Phaser.Math.Between(-28,28),alpha:0,scale:.35,duration:900+i%5*130,delay:i*75,repeat:-1,ease:'Sine.Out'});});
            xs(7).forEach((x,i)=>{const fumaca=this.add.ellipse(x,445+i%3*24,28+i%2*10,17+i%3*5,0x4a3b3c,.22).setDepth(3);this.tweens.add({targets:fumaca,y:fumaca.y-105,x:x+(i%2?28:-28),scale:1.8,alpha:0,duration:1900+i*140,repeat:-1,delay:i*170,ease:'Sine.Out'});});
        }else{
            xs(10).filter(x=>this.decoracaoLivre(x,42)).forEach((x,i)=>{const piso=this.pisoOpcional(x);if(piso===undefined)return;const tocha=assentarTerrestre(this.add.image(x,piso,'reino-itens-magicos',4).setDisplaySize(46,112).setDepth(4),piso);this.tweens.add({targets:tocha,alpha:.82,duration:650+i%3*70,yoyo:true,repeat:-1});});
            xs(9).forEach((x,i)=>{const bandeira=this.add.triangle(x,175+i%2*35,0,0,55,12,0,30,i%2?0xb34f5e:0x6d68a8,.9).setOrigin(0,.5).setDepth(3);this.tweens.add({targets:bandeira,scaleX:.82,skewY:.12,duration:600+i*45,yoyo:true,repeat:-1,ease:'Sine.InOut'});});
        }
    }
    private regiaoEm(_x:number){return REGIOES_REINO[this.faseAtual];}
    private corPoeiraRegiao():number {
        const cores:Record<string,number>={bosque:0x78985d,vila:0xb4875f,caverna:0x71838a,montanha:0xe4edf2,pantano:0x687a4d,biblioteca:0x9b795a,castelo:0xa8825d,fogo:0x70423b};
        return cores[REGIOES_REINO[this.faseAtual].id]??REGIOES_REINO[this.faseAtual].cor;
    }
    private misturarCor(a:number,b:number,proporcao:number):number {const t=Phaser.Math.Clamp(proporcao,0,1),ar=(a>>16)&255,ag=(a>>8)&255,ab=a&255,br=(b>>16)&255,bg=(b>>8)&255,bb=b&255;return (Math.round(ar+(br-ar)*t)<<16)|(Math.round(ag+(bg-ag)*t)<<8)|Math.round(ab+(bb-ab)*t);}
    private criarPortal():void {
        const xPortal=this.larguraMundo-250,tema=REGIOES_REINO[this.faseAtual],visual=this.add.container(xPortal,455).setDepth(6),halo=this.add.ellipse(0,5,132,174,tema.corDestaque,.12),anelExterno=this.add.graphics().lineStyle(5,tema.corDestaque,.72).strokeEllipse(-70,-91,140,182),anelInterno=this.add.graphics().lineStyle(3,0xffffff,.62).strokeEllipse(-57,-76,114,152);visual.add([halo,anelExterno,anelInterno]);
        this.tweens.add({targets:anelExterno,angle:360,duration:5200,repeat:-1,ease:'Linear'});this.tweens.add({targets:anelInterno,angle:-360,duration:3600,repeat:-1,ease:'Linear'});this.tweens.add({targets:halo,scale:1.12,alpha:.22,duration:950,yoyo:true,repeat:-1,ease:'Sine.InOut'});
        for(let i=0;i<12;i++){const orbita=this.add.container(0,5).setAngle(i*30),luz=this.add.circle(0,-82-(i%3)*7,2+i%3, i%3?tema.corDestaque:0xffffff,.82);orbita.add(luz);visual.add(orbita);this.tweens.add({targets:orbita,angle:orbita.angle+360,duration:2400+i*105,repeat:-1,ease:'Linear'});this.tweens.add({targets:luz,alpha:.22,scale:1.65,duration:420+i*30,yoyo:true,repeat:-1});}
        const portal=this.physics.add.staticSprite(xPortal,465,'reino-objetos',4).setDisplaySize(150,190).setDepth(7).setTint(this.misturarCor(tema.cor,0x8a9b96,.5));(portal.body as Phaser.Physics.Arcade.StaticBody).setSize(160,250).setOffset(95,170);this.tweens.add({targets:portal,alpha:.68,yoyo:true,repeat:-1,duration:1050,ease:'Sine.InOut'});visual.setAlpha(.48).setScale(.92);this.portalVisual=visual;this.portalSprite=portal;
        this.physics.add.overlap(this.cavaleiro,portal,()=>{const faltam=this.portas.filter(p=>!p.aberta).length,guardiao=this.inimigos.some(i=>i instanceof MimicoPortaReino&&!i.derrotado),objetivo=!this.objetivoAventuraConcluido();if(faltam||guardiao||objetivo){if(this.time.now>this.avisoPortalEm){this.avisoPortalEm=this.time.now+2200;this.mostrarAviso(objetivo?`${this.aventura.icone} ${this.aventura.instrucao}`:faltam?`Ainda falta abrir ${faltam} porta${faltam>1?'s':''}!`:'Derrote o Mímico da Porta para liberar o portal!');}return;}if(!this.bloqueado)this.concluir();});
    }
    private atualizarEstadoPortal():void {const guardiaoVivo=this.inimigos.some(i=>i instanceof MimicoPortaReino&&!i.derrotado),pronto=this.portas.length>0&&this.portas.every(p=>p.aberta)&&!guardiaoVivo&&this.objetivoAventuraConcluido();if(pronto===this.portalPronto)return;this.portalPronto=pronto;const visual=this.portalVisual,portal=this.portalSprite;if(!visual||!portal)return;const tema=REGIOES_REINO[this.faseAtual];portal.setTint(pronto?tema.corDestaque:this.misturarCor(tema.cor,0x8a9b96,.5));this.tweens.add({targets:visual,alpha:pronto?1:.48,scale:pronto?1.08:.92,duration:380,ease:'Back.Out'});this.tweens.add({targets:portal,alpha:pronto?1:.68,scaleX:pronto?portal.scaleX*1.05:portal.scaleX,scaleY:pronto?portal.scaleY*1.05:portal.scaleY,duration:320,yoyo:pronto,repeat:pronto?1:0,ease:'Sine.InOut'});if(pronto){this.criarParticulas(portal.x,portal.y-25,tema.corDestaque,28);this.cameras.main.flash(180,tema.corDestaque>>16,(tema.corDestaque>>8)&255,tema.corDestaque&255,false);}}
    private criarHUD():void {
        const hud=this.add.container(0,0).setScrollFactor(0).setDepth(30);hud.add(this.add.graphics().fillStyle(0x173d34,.76).fillRoundedRect(16,14,270,58,18).lineStyle(2,0xffffff,.35).strokeRoundedRect(16,14,270,58,18));
        this.coracoes=[0,1,2,3].map(i=>this.add.image(42+i*38,43,'reino-objetos',3).setDisplaySize(31,31));this.textoMoedas=this.add.text(244,43,`${progressoReino.carregar().moedas}`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'22px',fontStyle:'bold',color:'#fff3b0'}).setOrigin(.5);hud.add([...this.coracoes,this.add.image(208,43,'reino-objetos',2).setDisplaySize(32,32),this.textoMoedas]);
        this.textoRegiao=this.add.text(480,34,'BOSQUE DOS NÚMEROS',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'15px',fontStyle:'bold',color:'#ffffff',stroke:'#244d42',strokeThickness:4}).setOrigin(.5).setScrollFactor(0).setDepth(35);this.barraProgresso=this.add.graphics().setScrollFactor(0).setDepth(35);
        this.textoInimigos=this.add.text(480,79,'',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',fontStyle:'bold',color:'#fff4b8',stroke:'#244d42',strokeThickness:3}).setOrigin(.5).setScrollFactor(0).setDepth(35);
        this.barraPocao=this.add.graphics();this.textoPocao=this.add.text(43,10,'',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',fontStyle:'bold',color:'#ffffff'});const icone=this.add.image(21,18,'reino-itens-magicos',1).setDisplaySize(30,33).setName('icone');this.hudPocao=this.add.container(330,91,[this.add.graphics().fillStyle(0x173d34,.82).fillRoundedRect(0,0,220,39,12).lineStyle(2,0xffffff,.28).strokeRoundedRect(0,0,220,39,12),icone,this.textoPocao,this.barraPocao]).setScrollFactor(0).setDepth(35).setVisible(false);
        this.textoObjetivo=this.add.text(151,92,'',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',fontStyle:'bold',color:'#fff4c2',backgroundColor:'rgba(23,61,52,0.82)',padding:{x:12,y:7},fixedWidth:270,align:'center'}).setOrigin(.5,0).setScrollFactor(0).setDepth(35);this.atualizarHudObjetivo();
        this.botaoTela(884,42,118,42,'‹ EDUCAPP',0x376e61);const areaSair=this.add.zone(884,42,118,42).setScrollFactor(0).setDepth(42).setInteractive({useHandCursor:true});areaSair.on('pointerdown',()=>confirmarSaidaParaEducApp(this,{aoAbrir:()=>{this.bloqueado=true;this.cavaleiro.setVelocity(0);this.physics.pause();},aoCancelar:()=>{this.physics.resume();this.bloqueado=false;}}));this.botaoTela(748,42,112,42,'☰ JORNADA',0x557f9c);this.add.zone(748,42,112,42).setScrollFactor(0).setDepth(42).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.abrirPainelJornada());this.botaoTela(665,42,42,42,'Ⅱ',0x9a7048);this.add.zone(665,42,42,42).setScrollFactor(0).setDepth(42).setInteractive({useHandCursor:true}).on('pointerdown',()=>this.alternarPausa());
    }
    private criarControlesTouch():void {
        if(!window.matchMedia('(pointer: coarse)').matches)return;
        const pressionavel=(x:number,y:number,rotulo:string,cor:number,down:()=>void,up?:()=>void)=>{const c=this.add.container(x,y).setScrollFactor(0).setDepth(40).setSize(72,72).setInteractive({useHandCursor:true});c.add([this.add.circle(0,4,34,0x173d34,.25),this.add.circle(0,0,34,cor,.72).setStrokeStyle(3,0xffffff,.65),this.add.text(0,0,rotulo,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:rotulo==='DASH'?'13px':'25px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5)]);c.on('pointerdown',()=>{c.setScale(.92);down();});const soltar=()=>{c.setScale(1);up?.();};c.on('pointerup',soltar);c.on('pointerout',soltar);return c;};
        pressionavel(72,555,'◀',0x3f8271,()=>this.esquerdaTouch=true,()=>this.esquerdaTouch=false);pressionavel(150,555,'▶',0x3f8271,()=>this.direitaTouch=true,()=>this.direitaTouch=false);pressionavel(640,555,'DASH',0x8667a7,()=>this.dash());pressionavel(720,555,'◆',0x507fa4,()=>this.defesaTouch=true,()=>this.defesaTouch=false);pressionavel(805,555,'↑',0x4d82aa,()=>this.pular(),()=>this.cavaleiro.encerrarPulo());pressionavel(886,555,'⚔',0xb77b43,()=>this.atacar());
    }
    private verificarPortas():void {const porta=this.portas.find(p=>!p.aberta&&Math.abs(this.cavaleiro.x-p.x)<105);if(porta&&!this.portaAtual)this.abrirDesafio(porta);}
    private abrirDesafio(porta:PortaReino):void {
        this.errosPorta=0;this.primeiraTentativa=true;
        this.portaAtual=porta;this.bloqueado=true;this.cavaleiro.setVelocity(0);this.physics.pause();const estado=progressoReino.carregar(),cfg=estado.challenges[porta.tipo],desafio=this.sessaoDesafios.gerar(porta.tipo,cfg.difficulty,estado.faixaSoma),renderizado=renderizarDesafioReino(this,desafio,this.corCategoria(porta.tipo),(resposta,botao)=>this.responderDesafio(botao,resposta,desafio,porta),()=>servicoVoz.falar(desafio.word?.palavra??desafio.prompt));this.modal=renderizado.container;servicoVoz.falar(desafio.word?.palavra??desafio.prompt);
    }
    private responderDesafio(botao:Phaser.GameObjects.Container,resposta:string[],desafio:InstanciaDesafio,porta:PortaReino):boolean {
        if(!validarRespostaDesafio(desafio,resposta)){this.errosPorta++;this.primeiraTentativa=false;this.comboPortas=0;audioJogo.efeito('erro');this.tweens.add({targets:botao,x:botao.x-7,yoyo:true,repeat:3,duration:50});this.tweens.add({targets:botao,scale:.96,alpha:.78,duration:110,yoyo:true,ease:'Sine.InOut'});const dica=this.add.text(480,535,this.errosPorta===1?'Quase lá! Tente outra resposta.':desafio.explanation,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',color:'#5b6e67',backgroundColor:'#fffdf3',padding:{x:16,y:9},align:'center',wordWrap:{width:620}}).setOrigin(.5).setScrollFactor(0).setDepth(115);this.time.delayedCall(2400,()=>dica.destroy());if(this.errosPorta>1)servicoVoz.falar(desafio.explanation);return false;}
        if(this.primeiraTentativa){this.comboPortas++;this.adicionarMoedas(this.comboPortas);this.mostrarAviso(`COMBO ${this.comboPortas}! +${this.comboPortas} moeda${this.comboPortas>1?'s':''}`);}audioJogo.efeito('porta');this.animarAberturaPorta(porta);porta.aberta=true;porta.sprite.disableBody();this.checkpoint=porta.x+125;const estado=progressoReino.carregar();progressoReino.salvar({faseAtual:Math.max(estado.faseAtual,this.faseAtual),selectedLevel:this.faseAtual,checkpointLevel:this.faseAtual,checkpointX:this.checkpoint,portasAbertas:this.portas.filter(p=>p.aberta).length});
        const modal=this.modal;if(modal){const cor=this.corCategoria(porta.tipo),celebracao=this.add.container(0,0);celebracao.add([this.add.circle(0,15,55,cor,.16),this.add.text(0,15,'✓',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'86px',fontStyle:'bold',color:`#${cor.toString(16).padStart(6,'0')}`}).setOrigin(.5)]);for(let i=0;i<10;i++){const estrela=this.add.star(Phaser.Math.Between(-260,260),-180,5,3,7,i%2?cor:0xffd85a,1);celebracao.add(estrela);this.tweens.add({targets:estrela,y:Phaser.Math.Between(-30,160),angle:Phaser.Math.Between(-120,120),alpha:0,duration:Phaser.Math.Between(280,430)});}celebracao.setScale(.35).setAlpha(0);modal.add(celebracao);this.tweens.add({targets:[celebracao,botao],scale:1.12,alpha:1,duration:150,ease:'Back.Out'});}
        modal?.disableInteractive();this.time.delayedCall(260,()=>this.tweens.add({targets:modal,alpha:0,scale:1.05,duration:220,onComplete:()=>{modal?.destroy(true);if(this.modal===modal)this.modal=undefined;this.portaAtual=undefined;this.physics.resume();this.bloqueado=false;this.cavaleiro.x=porta.x+115;this.cavaleiro.invulneravel=true;this.time.delayedCall(900,()=>this.cavaleiro.invulneravel=false);}}));
        return true;
    }
    private animarAberturaPorta(porta:PortaReino):void {const sprite=porta.sprite,cor=this.corCategoria(porta.tipo),luz=this.add.circle(porta.x,425,42,cor,.08).setDepth(7);this.tweens.add({targets:sprite,x:sprite.x+4,angle:1.5,duration:45,yoyo:true,repeat:2,onComplete:()=>{sprite.setPosition(porta.x,469).setAngle(0).setFrame(1);this.tweens.add({targets:sprite,scaleX:sprite.scaleX*1.09,scaleY:sprite.scaleY*1.06,duration:105,yoyo:true,ease:'Back.Out'});this.criarParticulas(porta.x,410,cor,34);}});this.tweens.add({targets:luz,scale:2.5,alpha:.75,duration:150,yoyo:true,hold:40,onComplete:()=>luz.destroy()});this.tweens.add({targets:porta.emblema,scale:1.28,alpha:.35,duration:170,yoyo:true});}
    private atacar():void {if(this.bloqueado||this.cavaleiro.defendendo)return;if(this.cavaleiro.atacando){this.ataquePendente=true;return;}const arma=progressoReino.carregar().equipado.arma,duracao=arma==='espada-rapida'?155:arma==='martelo'?280:220,alcance=arma==='martelo'?112:arma==='lanca'?145:82;this.cavaleiro.atacar(duracao);this.acionarMecanismoProximo(alcance);audioJogo.efeito('espada');if(arma==='arco')this.dispararFlecha();else this.time.delayedCall(95,()=>this.inimigos.forEach(inimigo=>{const dx=(inimigo.x-this.cavaleiro.x)*this.cavaleiro.olhando;if(!inimigo.derrotado&&dx>0&&dx<alcance&&Math.abs(inimigo.y-this.cavaleiro.y)<82)this.acertarInimigo(inimigo,arma==='martelo');}));this.time.delayedCall(duracao+10,()=>{if(this.ataquePendente&&!this.bloqueado){this.ataquePendente=false;this.atacar();}});}
    private acertarInimigo(inimigo:InimigoReino,forcarDerrota=false):void {const derrotado=forcarDerrota?(inimigo.derrotar(),true):inimigo.atingir();audioJogo.efeito('acerto');if(derrotado){this.criarEfeitoDerrota(inimigo);this.cameras.main.shake(95,.0045);if(inimigo instanceof MimicoPortaReino)this.recompensarGuardiao(inimigo.x,inimigo.y);else if(Math.random()<.7)this.soltarMoeda(inimigo.x,inimigo.y-25);}else this.criarParticulas(inimigo.x,inimigo.y,0xc9f5a8,18);}
    private recompensarGuardiao(x:number,y:number):void {const premio=4,tema=REGIOES_REINO[this.faseAtual];if(this.aventura.tipo==='guardiao')this.registrarEventoAventura('guardiao-derrotado');this.adicionarMoedas(premio);audioJogo.efeito('moeda');this.criarParticulas(x,y-30,tema.corDestaque,48);this.cameras.main.flash(180,255,220,105,false);const texto=this.add.text(x,y-105,`RECOMPENSA DO GUARDIÃO!  +${premio} MOEDAS`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'18px',fontStyle:'bold',color:'#fff4b8',stroke:'#5b3b20',strokeThickness:5}).setOrigin(.5).setDepth(95).setAlpha(0).setScale(.75);this.tweens.add({targets:texto,y:y-145,alpha:1,scale:1,duration:260,ease:'Back.Out',yoyo:true,hold:1150,onComplete:()=>texto.destroy()});}
    private criarEfeitoDerrota(inimigo:InimigoReino):void {
        let cor=0x89968f,formato:FormatoParticula='fumaca';
        if(inimigo instanceof SlimeReino){cor=0x75d96b;formato='respingo';}
        else if(inimigo instanceof MorcegoReino){cor=0x4f425f;formato='farrapo';}
        else if(inimigo instanceof PlantaReino){cor=0x4fae58;formato='folha';}
        else if(inimigo instanceof CogumeloSaltadorReino){cor=0xd78275;formato='esporo';}
        else if(inimigo instanceof FuracaoFolhasReino){cor=0x91ba52;formato='redemoinho';}
        else if(inimigo instanceof ArqueiroReino){cor=0xc49a62;formato='lasca';}
        else if(inimigo instanceof GoblinReino){cor=0x82907e;formato='fumaca';}
        else if(inimigo instanceof CavaleiroEspantalhoReino){cor=0xb7aa82;formato='lasca';}
        this.criarParticulas(inimigo.x,inimigo.y,cor,22,formato);
    }
    private dispararFlecha():void {const direcao=this.cavaleiro.olhando,inicioX=this.cavaleiro.x+direcao*45,projetil=this.add.ellipse(inicioX,this.cavaleiro.y-5,30,7,0xffd75e,1).setStrokeStyle(3,0xfff2a6,.8).setDepth(10),distancia=280;let tween!:Phaser.Tweens.Tween;tween=this.tweens.add({targets:projetil,x:inicioX+direcao*distancia,duration:500,ease:'Linear',onUpdate:()=>{if(!projetil.active)return;const alvo=this.inimigos.find(inimigo=>!inimigo.derrotado&&Math.abs(inimigo.x-projetil.x)<28&&Math.abs(inimigo.y-projetil.y)<95);if(alvo){this.acertarInimigo(alvo);tween.stop();projetil.destroy();}},onComplete:()=>projetil.destroy()});}
    private dash():void {if(this.bloqueado)return;if(this.cavaleiro.dash()){audioJogo.efeito('espada');this.cameras.main.shake(90,.002);this.mostrarAviso('DASH!');}}
    private pular():void {if(this.bloqueado)return;if(this.cavaleiro.pular())audioJogo.efeito('pulo');}
    private dano(inimigo:InimigoReino):void {if(inimigo.derrotado||this.cavaleiro.atacando)return;const corpo=this.cavaleiro.body as Phaser.Physics.Arcade.Body,corpoInimigo=inimigo.corpoColisao.body as Phaser.Physics.Arcade.Body;if(corpo.velocity.y>120&&corpo.bottom<=corpoInimigo.center.y+12){this.acertarInimigo(inimigo);this.cavaleiro.setVelocityY(-390);return;}if(this.cavaleiro.defendendo)corpoInimigo.setVelocityX((inimigo.x<this.cavaleiro.x?-1:1)*270);this.aplicarDano(inimigo.x);}
    private danoCenario(origemX:number):void {this.aplicarDano(origemX);}
    private aplicarDano(origemX:number):void {if(this.bloqueado||this.cavaleiro.invulneravel)return;if(this.pocaoAtiva==='escudo'){audioJogo.efeito('acerto');this.criarParticulas(this.cavaleiro.x,this.cavaleiro.y,POCOES.escudo.corClara,7);return;}if(progressoReino.carregar().invencivel){this.cavaleiro.invulneravel=true;audioJogo.efeito('acerto');this.criarParticulas(this.cavaleiro.x,this.cavaleiro.y,0x9df5df,5);this.time.delayedCall(350,()=>this.cavaleiro.invulneravel=false);return;}if(this.cavaleiro.defendendo){this.cavaleiro.invulneravel=true;audioJogo.efeito('acerto');this.cavaleiro.setVelocityX(0);this.time.delayedCall(280,()=>this.cavaleiro.invulneravel=false);return;}this.vidas--;audioJogo.efeito('dano');this.cameras.main.shake(320,.014);this.cameras.main.flash(120,255,90,90);this.criarParticulas(this.cavaleiro.x,this.cavaleiro.y,0xff7048,8);this.cavaleiro.levarDano(origemX);this.atualizarVidas();if(this.vidas<=0)this.time.delayedCall(450,()=>this.reposicionar());}
    private atualizarVidas():void {this.coracoes.forEach((c,i)=>c.setAlpha(i<this.vidas?1:.18));}
    private criarCheckpoints():void {const ativados=new Set<number>();this.nivel.checkpoints.forEach(x=>{const piso=this.pisoAbaixo(x,0),runa=assentarTerrestre(this.add.image(x,piso,'reino-itens-magicos',0).setDisplaySize(82,108).setDepth(5),piso);this.tweens.add({targets:runa,alpha:.78,duration:950,yoyo:true,repeat:-1});const zona=this.physics.add.staticImage(x,piso-45,'reino-objetos',2).setVisible(false).setSize(72,90);this.physics.add.overlap(this.cavaleiro,zona,()=>{if(ativados.has(x))return;ativados.add(x);this.checkpoint=x;this.ultimaPosicaoSegura={x,y:piso-120};progressoReino.salvar({checkpointX:x,checkpointLevel:this.faseAtual,portasAbertas:this.portas.filter(p=>p.aberta).length});audioJogo.efeito('moeda');this.criarParticulas(x,piso-48,0x72e4d2,20);this.tweens.add({targets:runa,scale:1.15,duration:180,yoyo:true});this.mostrarAviso('CHECKPOINT ATIVADO — você volta aqui se cair');});});}
    private atualizarPosicaoSegura():void {if(this.time.now<this.ultimoSeguroEm+280)return;const corpo=this.cavaleiro.body as Phaser.Physics.Arcade.Body;if(!corpo.blocked.down||Math.abs(corpo.velocity.y)>5)return;const superficie=superficieAbaixo(this.cavaleiro.x,corpo.bottom-12,[this.plataformas]);if(!superficie||this.cavaleiro.x<superficie.left+55||this.cavaleiro.x>superficie.right-55)return;this.ultimoSeguroEm=this.time.now;this.ultimaPosicaoSegura={x:this.cavaleiro.x,y:superficie.top-120};}
    private cairNoAbismo():void {if(this.retornandoDaQueda)return;this.retornandoDaQueda=true;this.bloqueado=true;const estado=progressoReino.carregar();if(!estado.invencivel)this.vidas--;if(this.vidas<=0)this.vidas=estado.dificuldade==='aventura'?2:4;this.atualizarVidas();audioJogo.efeito('dano');this.cameras.main.fadeOut(180,18,35,42);const corpo=this.cavaleiro.body as Phaser.Physics.Arcade.Body;corpo.setAllowGravity(false);this.cavaleiro.setVelocity(0);this.time.delayedCall(230,()=>{this.cavaleiro.resetarEstado();this.cavaleiro.setPosition(this.ultimaPosicaoSegura.x,this.ultimaPosicaoSegura.y).setVelocity(0).setAlpha(1);(this.cavaleiro.body as Phaser.Physics.Arcade.Body).setAllowGravity(true);this.cavaleiro.invulneravel=true;this.cameras.main.fadeIn(180,18,35,42);this.time.delayedCall(900,()=>this.cavaleiro.invulneravel=false);this.retornandoDaQueda=false;this.bloqueado=false;});}
    private reposicionar():void {const dificuldade=progressoReino.carregar().dificuldade;this.vidas=dificuldade==='aventura'?2:4;this.atualizarVidas();this.cavaleiro.resetarEstado();this.cavaleiro.setPosition(this.checkpoint,this.pisoAbaixo(this.checkpoint,0)-120).setVelocity(0).setAlpha(1);this.cavaleiro.invulneravel=true;this.time.delayedCall(900,()=>this.cavaleiro.invulneravel=false);}
    private soltarMoeda(x:number,y:number):void {const m=this.physics.add.sprite(x,y,'reino-objetos',2).setDisplaySize(42,42).setVelocityY(-220).setDepth(7);this.physics.add.collider(m,this.plataformas);this.physics.add.overlap(this.cavaleiro,m,()=>{if(!m.active)return;m.disableBody(true,true);this.moedas++;this.textoMoedas.setText(`${this.moedas}`);audioJogo.efeito('moeda');this.criarParticulas(m.x,m.y,0xffd85a,12);});}
    private concluir():void {
        this.bloqueado=true;this.physics.pause();const ultima=this.faseAtual>=REGIOES_REINO.length-1,proxima=ultima?0:this.faseAtual+1,estado=progressoReino.concluir(this.moedas),regiaoSeguinte=REGIOES_REINO[proxima];progressoReino.salvar({faseAtual:Math.max(estado.faseAtual,proxima),checkpointX:120,portasAbertas:0});audioJogo.efeito('conclusao');this.criarParticulas(this.cavaleiro.x,this.cavaleiro.y,0x72e4d2,ultima?60:35);this.add.rectangle(480,320,960,640,0x173c33,.68).setScrollFactor(0).setDepth(118);this.criarConfete(ultima?100:58,[0xffd85a,0x72e4d2,regiaoSeguinte.cor,regiaoSeguinte.corDestaque,0xf08bad]);if(ultima){this.criarParticulas(480,175,0xffdc75,70);this.cameras.main.flash(320,255,220,117,false);}
        const c=this.add.container(480,320).setScrollFactor(0).setDepth(120),painel=this.add.graphics().fillStyle(0xfffdf3,1).fillRoundedRect(-325,-185,650,370,32).lineStyle(6,ultima?0xd8ae59:0x67b895).strokeRoundedRect(-325,-185,650,370,32),faixa=this.add.graphics().fillStyle(regiaoSeguinte.cor,1).fillRoundedRect(-245,27,490,53,18).lineStyle(3,regiaoSeguinte.corDestaque,1).strokeRoundedRect(-245,27,490,53,18),coroa=this.criarCoroa(-262,-125,ultima?1.18:.88),estrelas=this.add.container(0,-67);
        for(let i=0;i<3;i++){const estrela=this.add.star((i-1)*52,0,5,8,18,i===1?0xffdc75:regiaoSeguinte.corDestaque,1).setStrokeStyle(3,0xffffff,.9);estrelas.add(estrela);this.tweens.add({targets:estrela,scale:1.15,angle:i===1?12:-10,duration:520+i*110,yoyo:true,repeat:-1,ease:'Sine.InOut'});}
        c.add([painel,coroa,this.add.text(0,-126,ultima?'REINO DESBLOQUEADO!':'FASE CONCLUÍDA!',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:ultima?'34px':'31px',fontStyle:'bold',color:ultima?'#9a6b25':'#34745c'}).setOrigin(.5),estrelas,this.add.text(0,-25,`Moedas nesta fase: ${this.moedas}   •   Melhor resultado: ${estado.melhorMoedas}`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',fontStyle:'bold',color:'#526a61'}).setOrigin(.5),faixa,this.add.text(0,53,ultima?'A aventura recomeça em':'PRÓXIMO DESTINO',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5,1),this.add.text(0,59,regiaoSeguinte.nome.toUpperCase(),{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'17px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5,0)]);
        const botoes=[this.botaoModal(-210,132,180,52,ultima?'RECOMEÇAR REINO':'PRÓXIMA FASE',0xc28c3d),this.botaoModal(0,132,180,52,'ESCOLHER FASE',0x4c9a72),this.botaoModal(210,132,180,52,'EDUCAPP',0x557f9c)],destaques=botoes.map((_,i)=>this.add.rectangle(-210+i*210,132,184,56,0xffffff,0).setStrokeStyle(4,0xffdc68).setAlpha(i?0:1));c.add([...botoes,...destaques]);c.setAlpha(0);this.tweens.add({targets:c,alpha:1,duration:160});const zonas=[270,480,690].map(x=>this.add.zone(x,452,180,52).setScrollFactor(0).setDepth(130).setInteractive({useHandCursor:true}));let escolha=0;const atualizarEscolha=()=>destaques.forEach((d,i)=>d.setAlpha(i===escolha?1:0)),confirmar=()=>zonas[escolha].emit('pointerdown'),esquerda=()=>{escolha=Math.max(0,escolha-1);atualizarEscolha();},direita=()=>{escolha=Math.min(2,escolha+1);atualizarEscolha();},teclado=this.input.keyboard!;teclado.on('keydown-LEFT',esquerda);teclado.on('keydown-RIGHT',direita);teclado.on('keydown-Z',confirmar);teclado.on('keydown-ENTER',confirmar);this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>{teclado.off('keydown-LEFT',esquerda);teclado.off('keydown-RIGHT',direita);teclado.off('keydown-Z',confirmar);teclado.off('keydown-ENTER',confirmar);});zonas[0].on('pointerdown',()=>this.iniciarFase(proxima));zonas[1].on('pointerdown',()=>this.scene.start('ConfiguracaoReino',{tela:'fases'}));zonas[2].on('pointerdown',()=>confirmarSaidaParaEducApp(this));
    }
    private iniciarFase(fase:number):void {if(this.transicionando)return;this.transicionando=true;this.bloqueado=true;const seed=Date.now()>>>0;progressoReino.salvar({selectedLevel:fase,checkpointLevel:fase,checkpointX:120,portasAbertas:0,levelSeed:seed,aventura:{fase,seed,eventos:[]}});this.cameras.main.fadeOut(650,18,35,31);this.cameras.main.once(Phaser.Cameras.Scene2D.Events.FADE_OUT_COMPLETE,()=>{this.physics.resume();this.scene.start('ReinoDasPortas',{fase});});}
    private criarIconeEquipamento(tipo:string,id:string,apagado=false):Phaser.GameObjects.Container {
        const g=this.add.graphics(),c=this.add.container(0,0,[g]),alpha=apagado?.38:1;
        if(tipo==='companheiro'){c.add(this.add.image(0,0,`reino-companheiro-${id}-mover`,0).setDisplaySize(44,44).setAlpha(alpha));return c.setSize(52,46);}
        if(tipo==='roupa'){
            const cor=CORES_ROUPAS[id]??0xdddddd;
            if(id==='capa-mago')g.fillStyle(cor,alpha).fillTriangle(-14,-15,14,-15,20,17).fillTriangle(-14,-15,-20,17,20,17).fillStyle(0xffd86b,alpha).fillCircle(0,-12,4).lineStyle(2,0xffffff,alpha*.7).strokeTriangle(-14,-15,14,-15,20,17);
            else {g.fillStyle(cor,alpha).fillRoundedRect(-15,-13,30,29,5).fillTriangle(-15,-10,-25,1,-15,7).fillTriangle(15,-10,25,1,15,7).lineStyle(3,id==='armadura-verde'?0xe3d47a:0xccecff,alpha).lineBetween(-9,-6,9,10).lineBetween(9,-6,-9,10);}
        }else if(id==='espada-cristal')g.lineStyle(7,0x7a542e,alpha).lineBetween(-18,20,-8,10).lineStyle(5,0xffd85a,alpha).lineBetween(-18,5,-3,20).fillStyle(0x68def2,alpha).fillTriangle(-7,8,22,-26,13,2).fillStyle(0xd5fbff,alpha).fillTriangle(-4,5,22,-26,7,-2).lineStyle(2,0xffdf72,alpha).strokeTriangle(-7,8,22,-26,13,2);
        else if(id==='martelo')g.lineStyle(5,0x70452f,alpha).lineBetween(-13,14,12,-10).fillStyle(0x71818c,alpha).fillRoundedRect(5,-20,27,18,4).lineStyle(2,0xe2eef2,alpha).strokeRoundedRect(5,-20,27,18,4);
        else if(id==='lanca')g.lineStyle(4,0x8b5b35,alpha).lineBetween(-25,17,24,-17).fillStyle(0xe8edf0,alpha).fillTriangle(21,-22,37,-25,27,-10);
        else if(id==='arco')g.lineStyle(4,0x9b6538,alpha).beginPath().arc(-3,0,25,-1.15,1.15).strokePath().lineStyle(2,0xf3e0b8,alpha).lineBetween(7,-23,7,23).fillStyle(0xffdc67,alpha).fillTriangle(10,-2,22,0,10,3);
        else {const rapida=id==='espada-rapida';g.lineStyle(rapida?3:5,rapida?0xb8f5ff:0xdce8ed,alpha).lineBetween(-14,14,18,-19).lineStyle(4,0x8a613c,alpha).lineBetween(-19,19,-8,8).lineStyle(5,rapida?0x62d9ed:0xd5a642,alpha).lineBetween(-16,8,-3,21);if(rapida)g.lineStyle(2,0x7eeeff,alpha*.7).lineBetween(-3,2,27,-28);}
        return c.setSize(52,46);
    }
    private criarPreviewEquipado(equipado:{arma:string;roupa?:string;companheiro?:string}):Phaser.GameObjects.Container {
        const c=this.add.container(0,0),cor=equipado.roupa?CORES_ROUPAS[equipado.roupa]??0xffffff:0xffffff,g=this.add.graphics();
        g.fillStyle(0x315f51,.1).fillRoundedRect(-57,-43,114,86,15).lineStyle(2,0xd8ae59,.65).strokeRoundedRect(-57,-43,114,86,15).fillStyle(cor,1).fillRoundedRect(-13,-13,26,35,8).fillStyle(0xf1c9a5,1).fillCircle(0,-21,11).fillStyle(0x5d7180,1).fillTriangle(-12,-27,0,-39,12,-27).fillStyle(0x6d4b32,1).fillRect(-11,21,9,13).fillRect(3,21,9,13);
        const arma=this.criarIconeEquipamento('arma',equipado.arma).setPosition(24,-1).setScale(.72),companheiro=equipado.companheiro?this.criarIconeEquipamento('companheiro',equipado.companheiro).setPosition(-36,15).setScale(.72):undefined;
        c.add([g,arma]);if(companheiro)c.add(companheiro);return c;
    }
    private abrirPainelJornada():void {
        if(this.bloqueado)return;this.bloqueado=true;this.cavaleiro.setVelocity(0);this.physics.pause();
        let estado=progressoReino.carregar();const c=this.add.container(480,320).setScrollFactor(0).setDepth(150),g=this.add.graphics().fillStyle(0x15382f,.72).fillRect(-480,-320,960,640).fillStyle(0xfffdf3,1).fillRoundedRect(-410,-275,820,550,28).lineStyle(5,0xd8ae59).strokeRoundedRect(-410,-275,820,550,28);c.add([g,this.add.text(0,-242,'MAPA DA JORNADA',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'25px',fontStyle:'bold',color:'#386c5b'}).setOrigin(.5)]);
        const trilha=this.add.graphics();for(let i=0;i<REGIOES_REINO.length-1;i++){const x1=-315+i*105,x2=x1+105,y1=-190+(i%2?5:-5),y2=-190+((i+1)%2?5:-5),percorrida=i<this.faseAtual,curva=new Phaser.Curves.QuadraticBezier(new Phaser.Math.Vector2(x1,y1),new Phaser.Math.Vector2((x1+x2)/2,-190+(i%2?-13:13)),new Phaser.Math.Vector2(x2,y2)),pontos=curva.getPoints(24);trilha.lineStyle(9,percorrida?0x6baa72:0xc8cfcb,1).strokePoints(pontos,false,false);trilha.lineStyle(2,percorrida?0xe1f1a5:0xffffff,.7).strokePoints(pontos,false,false);}c.add(trilha);
        const nosFases:{x:number;y:number;fase:number}[]=[];REGIOES_REINO.forEach((r,i)=>{const x=-315+i*105,y=-190+(i%2?5:-5),concluida=i<this.faseAtual,atual=i===this.faseAtual;c.add([this.add.circle(x,y,22,concluida||atual?r.cor:0xbac3bf).setStrokeStyle(3,atual?0xffdc68:concluida?r.corDestaque:0x8c9994),this.add.text(x,y,concluida?'✓':atual?'◆':'?',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5),this.add.text(x,-153,r.nome.split(' ')[0],{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'9px',color:'#536b62'}).setOrigin(.5)]);if(i<=estado.faseAtual)nosFases.push({x,y,fase:i});});
        const abertas=this.portas.filter(p=>p.aberta).length,missoes=MISSOES_REINO.map((m,i)=>`${(i===0?this.moedas>=m.alvo:i===1?abertas>=m.alvo:false)?'✓':'○'} ${m.texto}`).join('   '),textoRecursos=this.add.text(0,-101,`💰 ${estado.moedas} moedas     💎 ${estado.gemas} gemas     📜 ${estado.pergaminhos}/8 pergaminhos`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'13px',fontStyle:'bold',color:'#386c5b'}).setOrigin(.5),textoEquipamentos=this.add.text(0,-78,`EQUIPAMENTOS  •  ${estado.equipamentos.length}/${EQUIPAMENTOS_REINO.length} itens`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',fontStyle:'bold',color:'#687a73'}).setOrigin(.5);c.add([this.add.text(0,-125,missoes,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'12px',fontStyle:'bold',color:'#526a61'}).setOrigin(.5),textoRecursos,textoEquipamentos]);
        const fecharPainel=()=>{this.zonasPainel.forEach(z=>z.destroy());this.zonasPainel=[];c.destroy(true);const atual=progressoReino.carregar();this.cavaleiro.aplicarRoupa(atual.skin);this.cavaleiro.aplicarEquipamento(atual.equipado);this.physics.resume();this.bloqueado=false;};
        nosFases.forEach(no=>{const zona=this.add.zone(480+no.x,320+no.y,54,54).setScrollFactor(0).setDepth(155).setInteractive({useHandCursor:true});zona.on('pointerdown',()=>{if(no.fase===this.faseAtual){this.mostrarAviso('Você já está nesta fase.');return;}const regiao=REGIOES_REINO[no.fase];if(!window.confirm(`Ir agora para a fase ${no.fase+1} — ${regiao.nome}?`))return;this.zonasPainel.forEach(z=>z.destroy());this.zonasPainel=[];c.destroy(true);this.iniciarFase(no.fase);});this.zonasPainel.push(zona);});
        let preview=this.criarPreviewEquipado(estado.equipado).setPosition(338,165);const tituloPreview=this.add.text(338,112,'EQUIPADO',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'10px',fontStyle:'bold',color:'#386c5b'}).setOrigin(.5);c.add([tituloPreview,preview]);
        const dicaEquipamento=this.add.text(0,106,'',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',fontStyle:'bold',color:'#315f51',backgroundColor:'#fffdf3',padding:{x:12,y:7},align:'center',wordWrap:{width:390}}).setOrigin(.5).setVisible(false);c.add(dicaEquipamento);const mostrarDica=(item:typeof EQUIPAMENTOS_REINO[number])=>{dicaEquipamento.setText(`${item.nome}\n${item.descricao}`).setVisible(true);c.bringToTop(dicaEquipamento);};
        const botoesEquipamento:Phaser.GameObjects.Container[]=[];const desenharBotao=(botao:Phaser.GameObjects.Container,item:typeof EQUIPAMENTOS_REINO[number])=>{const lendario=item.precoGemas!==undefined,desbloqueado=estado.equipamentos.includes(item.id),selecionado=estado.equipado.arma===item.id||estado.equipado.roupa===item.id||estado.equipado.companheiro===item.id,cor=lendario?0x3e9fb5:item.tipo==='arma'?0xb47746:item.tipo==='roupa'?0x557fa3:0x7962a0,rotulo=desbloqueado?`${selecionado?'✓ ':''}${item.nome}`:`🔒 ${item.nome}\n${lendario?`💎 ${item.precoGemas} gema${item.precoGemas===1?'':'s'}`:`💰 ${item.preco}`}`;botao.removeAll(true);botao.add([this.add.graphics().fillStyle(desbloqueado?cor:0x9ca5a1,desbloqueado?1:.72).fillRoundedRect(-71,-27,142,54,13).lineStyle(selecionado?4:2,selecionado?0xffdc68:lendario?0x65d9ef:0xffffff,selecionado?1:.55).strokeRoundedRect(-71,-27,142,54,13),this.criarIconeEquipamento(item.tipo,item.id,!desbloqueado).setPosition(-48,0).setScale(.7),this.add.text(15,0,rotulo,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'9px',fontStyle:'bold',color:'#ffffff',align:'center',wordWrap:{width:88}}).setOrigin(.5)]);};
        const atualizarEquipamentos=()=>{botoesEquipamento.forEach((botao,i)=>desenharBotao(botao,EQUIPAMENTOS_REINO[i]));textoRecursos.setText(`💰 ${estado.moedas} moedas     💎 ${estado.gemas} gemas     📜 ${estado.pergaminhos}/8 pergaminhos`);textoEquipamentos.setText(`EQUIPAMENTOS  •  ${estado.equipamentos.length}/${EQUIPAMENTOS_REINO.length} itens`);preview.destroy(true);preview=this.criarPreviewEquipado(estado.equipado).setPosition(338,165);c.add(preview);};
        EQUIPAMENTOS_REINO.forEach((item,i)=>{const coluna=i%5,linha=Math.floor(i/5),x=-308+coluna*154,y=-45+linha*62,botao=this.add.container(x,y).setSize(142,55).setInteractive({useHandCursor:true});desenharBotao(botao,item);botao.on('pointerdown',()=>{const lendario=item.precoGemas!==undefined,possui=estado.equipamentos.includes(item.id);if(!possui){if(lendario){const preco=item.precoGemas!;if(estado.gemas<preco){this.mostrarAviso(`Faltam ${preco-estado.gemas} gema${preco-estado.gemas===1?'':'s'} para o item lendário!`);return;}estado=progressoReino.salvar({gemas:estado.gemas-preco,equipamentos:[...estado.equipamentos,item.id]});this.mostrarAviso('💎 Item lendário adquirido!');}else {if(estado.moedas<item.preco){this.mostrarAviso(`Faltam ${item.preco-estado.moedas} moedas para comprar!`);return;}estado=progressoReino.salvar({moedas:estado.moedas-item.preco,equipamentos:[...estado.equipamentos,item.id]});this.mostrarAviso(`💰 ${item.nome} comprado!`);}audioJogo.efeito('moeda');}const equipado={...estado.equipado};if(item.tipo==='arma')equipado.arma=item.id;else if(item.tipo==='roupa')equipado.roupa=equipado.roupa===item.id?undefined:item.id;else equipado.companheiro=equipado.companheiro===item.id?undefined:item.id;const skin=equipado.roupa?CORES_ROUPAS[equipado.roupa]??0xffffff:0xffffff;estado=progressoReino.salvar({equipado,skin});this.textoMoedas.setText(`${estado.moedas}`);this.cavaleiro.aplicarRoupa(skin);this.cavaleiro.aplicarEquipamento(equipado);atualizarEquipamentos();});botao.on('pointerover',()=>{botao.setScale(1.03);mostrarDica(item);});botao.on('pointerout',()=>{botao.setScale(1);dicaEquipamento.setVisible(false);});botoesEquipamento.push(botao);c.add(botao);const zona=this.add.zone(480+x,320+y,142,55).setScrollFactor(0).setDepth(155).setInteractive({useHandCursor:true});zona.on('pointerdown',()=>botao.emit('pointerdown')).on('pointerover',()=>{botao.setScale(1.03);mostrarDica(item);}).on('pointerout',()=>{botao.setScale(1);dicaEquipamento.setVisible(false);});this.zonasPainel.push(zona);});
        c.add(this.add.text(0,126,'DIFICULDADE DA JORNADA',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'12px',fontStyle:'bold',color:'#386c5b'}).setOrigin(.5));
        let dificuldadeAtual=estado.dificuldade;const opcoes:{valor:typeof dificuldadeAtual;rotulo:string}[]=[{valor:'tranquilo',rotulo:'TRANQUILO'},{valor:'normal',rotulo:'NORMAL'},{valor:'aventura',rotulo:'AVENTURA'}],botoes:Phaser.GameObjects.Container[]=[];
        const atualizarBotoes=()=>botoes.forEach((botao,i)=>{const ativo=opcoes[i].valor===dificuldadeAtual;botao.removeAll(true);botao.add([this.add.graphics().fillStyle(ativo?0x4c9276:0x9aab9f,ativo?1:.72).fillRoundedRect(-72,-17,144,34,17).lineStyle(ativo?3:2,ativo?0xe4b75c:0xffffff,ativo?1:.5).strokeRoundedRect(-72,-17,144,34,17),this.add.text(0,0,`${ativo?'✓ ':''}${opcoes[i].rotulo}`,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5)]);});
        opcoes.forEach((op,i)=>{const x=-168+i*168,botao=this.add.container(x,158).setSize(144,34).setInteractive({useHandCursor:true});botao.on('pointerdown',()=>{if(op.valor===dificuldadeAtual)return;dificuldadeAtual=op.valor;progressoReino.salvar({dificuldade:dificuldadeAtual});atualizarBotoes();this.mostrarAviso('Dificuldade salva! As vidas mudam no próximo recomeço/checkpoint.');});botao.on('pointerover',()=>botao.setScale(1.03));botao.on('pointerout',()=>botao.setScale(1));botoes.push(botao);c.add(botao);const zona=this.add.zone(480+x,478,144,34).setScrollFactor(0).setDepth(155).setInteractive({useHandCursor:true});zona.on('pointerdown',()=>botao.emit('pointerdown')).on('pointerover',()=>botao.setScale(1.03)).on('pointerout',()=>botao.setScale(1));this.zonasPainel.push(zona);});atualizarBotoes();
        c.add(this.add.text(0,185,'A dificuldade escolhida controla somente a quantidade de vidas.',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',color:'#687a73'}).setOrigin(.5));const fechar=this.botaoModal(0,232,190,48,'CONTINUAR',0x4c9276);c.add(fechar);const zonaFechar=this.add.zone(480,552,190,48).setScrollFactor(0).setDepth(155).setInteractive({useHandCursor:true});zonaFechar.on('pointerdown',fecharPainel);this.zonasPainel.push(zonaFechar);
    }
    private atualizarRegiao():void {const r=REGIOES_REINO[this.faseAtual];if(r.id!==this.regiaoAtual){this.regiaoAtual=r.id;this.textoRegiao.setText(`FASE ${this.faseAtual+1} • ${r.nome.toUpperCase()}`).setAlpha(0);this.tweens.add({targets:this.textoRegiao,alpha:1,duration:260});}const p=Phaser.Math.Clamp(this.cavaleiro.x/this.larguraMundo,0,1),restantes=this.inimigos.filter(i=>!i.derrotado).length;this.textoInimigos.setText(restantes?`AMEAÇAS RESTANTES: ${restantes}`:'CAMINHO SEGURO!');this.barraProgresso.clear().fillStyle(0x173d34,.65).fillRoundedRect(330,55,300,9,5).fillStyle(r.corDestaque,1).fillRoundedRect(330,55,300*p,9,5);}
    private mostrarAviso(texto:string):void {const t=this.add.text(480,92,texto,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'16px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#315f51',padding:{x:18,y:9}}).setOrigin(.5).setScrollFactor(0).setDepth(180).setAlpha(0);this.tweens.add({targets:t,alpha:1,y:82,duration:180,yoyo:true,hold:1250,onComplete:()=>t.destroy()});}
    private alternarPausa():void {if(this.portaAtual)return;if(this.pausado){this.pausado=false;this.bloqueado=false;this.physics.resume();this.modal?.destroy(true);this.modal=undefined;return;}if(this.bloqueado)return;this.pausado=true;this.bloqueado=true;this.cavaleiro.setVelocity(0);this.physics.pause();const c=this.add.container(480,320).setScrollFactor(0).setDepth(160);this.modal=c;c.add([this.add.rectangle(0,0,960,640,0x17382f,.62),this.add.graphics().fillStyle(0xfffdf3,1).fillRoundedRect(-225,-115,450,230,28).lineStyle(5,0xd6ae61).strokeRoundedRect(-225,-115,450,230,28),this.add.text(0,-52,'JORNADA PAUSADA',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'27px',fontStyle:'bold',color:'#376a59'}).setOrigin(.5)]);const b=this.botaoModal(0,45,210,58,'CONTINUAR',0x4c9276);c.add(b);const z=this.add.zone(480,365,210,58).setScrollFactor(0).setDepth(165).setInteractive({useHandCursor:true});z.on('pointerdown',()=>{z.destroy();this.alternarPausa();});}
    private criarCoroa(x:number,y:number,escala=1):Phaser.GameObjects.Container {const c=this.add.container(x,y).setScale(escala),brilho=this.add.circle(0,0,42,0xffdc75,.16),g=this.add.graphics().fillStyle(0xffcf4d,1).fillTriangle(-34,20,-30,-22,-12,4).fillTriangle(-18,20,0,-31,18,20).fillTriangle(12,20,31,-22,34,20).fillRoundedRect(-34,12,68,22,6).lineStyle(4,0xa96e20,1).strokeRoundedRect(-34,12,68,22,6).fillStyle(0xffffff,.8).fillCircle(0,17,4).fillCircle(-22,18,3).fillCircle(22,18,3);c.add([brilho,g]);this.tweens.add({targets:brilho,scale:1.35,alpha:.04,duration:680,yoyo:true,repeat:-1,ease:'Sine.InOut'});this.tweens.add({targets:c,angle:4,duration:850,yoyo:true,repeat:-1,ease:'Sine.InOut'});return c;}
    private criarConfete(quantidade:number,cores:number[]):void {for(let i=0;i<quantidade;i++){const x=Phaser.Math.Between(18,942),y=Phaser.Math.Between(-220,-20),confete=this.add.rectangle(x,y,Phaser.Math.Between(5,10),Phaser.Math.Between(11,21),cores[i%cores.length],.92).setScrollFactor(0).setDepth(119).setAngle(Phaser.Math.Between(0,180));this.tweens.add({targets:confete,x:x+Phaser.Math.Between(-90,90),y:Phaser.Math.Between(655,790),angle:confete.angle+Phaser.Math.Between(240,760),duration:Phaser.Math.Between(1800,3400),delay:Phaser.Math.Between(0,900),ease:'Sine.In',onComplete:()=>confete.destroy()});}}
    private criarParticulas(x:number,y:number,cor:number,quantidade=14,formato:FormatoParticula='circulo'):void {for(let i=0;i<quantidade;i++){const tom=formato==='circulo'?(i%3?cor:0xffffff):(i%4?cor:0xffffff);let p:Phaser.GameObjects.Shape;if(formato==='respingo')p=this.add.ellipse(x,y,Phaser.Math.Between(5,11),Phaser.Math.Between(3,6),tom);else if(formato==='farrapo')p=this.add.triangle(x,y,-6,4,0,-5,6,4,tom).setAngle(Phaser.Math.Between(-45,45));else if(formato==='fumaca')p=this.add.circle(x,y,Phaser.Math.Between(5,9),tom,.68);else if(formato==='folha')p=this.add.ellipse(x,y,Phaser.Math.Between(8,14),Phaser.Math.Between(3,5),tom).setAngle(Phaser.Math.Between(-70,70));else if(formato==='lasca')p=this.add.rectangle(x,y,Phaser.Math.Between(3,6),Phaser.Math.Between(9,15),tom).setAngle(Phaser.Math.Between(-55,55));else if(formato==='esporo')p=this.add.circle(x,y,Phaser.Math.Between(3,7),tom,.82);else if(formato==='redemoinho')p=this.add.ellipse(x,y,Phaser.Math.Between(10,17),Phaser.Math.Between(2,4),tom).setAngle(Phaser.Math.Between(-35,35));else p=this.add.circle(x,y,Phaser.Math.Between(3,7),tom);p.setDepth(90);const lateral=formato==='redemoinho'?Phaser.Math.Between(-115,115):Phaser.Math.Between(-80,80),queda=formato==='fumaca'?Phaser.Math.Between(-105,-35):Phaser.Math.Between(-90,45);this.tweens.add({targets:p,x:x+lateral,y:y+queda,angle:p.angle+Phaser.Math.Between(-160,160),alpha:0,scale:formato==='fumaca'?1.7:.2,duration:Phaser.Math.Between(350,700),onComplete:()=>p.destroy()});}}
    private mostrarDicaInicial():void {const t=this.add.text(480,104,'◀ ▶  MOVA-SE    ↑  PULE    J  ATAQUE    X  ESCUDO',{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'15px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#315f51',padding:{x:22,y:10}}).setOrigin(.5).setScrollFactor(0).setDepth(35).setAlpha(0);this.tweens.add({targets:t,alpha:1,duration:250});this.time.delayedCall(4500,()=>this.tweens.add({targets:t,alpha:0,duration:300,onComplete:()=>t.destroy()}));}
    private botaoTela(x:number,y:number,w:number,h:number,texto:string,cor:number):Phaser.GameObjects.Container {const c=this.add.container(x,y).setScrollFactor(0).setDepth(40).setSize(w,h),zona=this.add.zone(0,0,w,h).setInteractive({useHandCursor:true});c.add([this.add.graphics().fillStyle(cor,1).fillRoundedRect(-w/2,-h/2,w,h,h/2).lineStyle(2,0xffffff,.5).strokeRoundedRect(-w/2,-h/2,w,h,h/2),this.add.text(0,0,texto,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:'11px',color:'#ffffff'}).setOrigin(.5),zona]);zona.on('pointerdown',()=>c.emit('acao'));return c;}
    private botaoModal(x:number,y:number,w:number,h:number,texto:string,cor:number):Phaser.GameObjects.Container {const c=this.add.container(x,y).setSize(w,h).setInteractive({useHandCursor:true});c.add([this.add.graphics().fillStyle(0x244c40,.18).fillRoundedRect(-w/2,-h/2+5,w,h,18).fillStyle(cor,1).fillRoundedRect(-w/2,-h/2,w,h,18),this.add.text(0,0,texto,{fontFamily:'Arial Rounded MT Bold, Arial',fontSize:h>60?'28px':'14px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5)]);c.on('pointerdown',()=>c.emit('acao'));c.on('pointerover',()=>c.setScale(1.04));c.on('pointerout',()=>c.setScale(1));return c;}
}
