import * as Phaser from 'phaser';
import type { DadosBalancaReino, InstanciaDesafio } from './DesafiosReino';

const FONTE='Arial Rounded MT Bold, Arial Black, Arial',TAMANHO_BLOCO=62,MEIA_VIGA=218,COMPRIMENTO_CORRENTE=72,ANGULO_MAXIMO=10;
type Lado='left'|'right';
interface EstadoBloco {valor:number;origemX:number;origemY:number;slot?:number;slotInicial?:number;arrastando:boolean;inicioX:number;inicioY:number}
interface Prato {grupo:Phaser.GameObjects.Container;zona:Phaser.GameObjects.Zone;realce:Phaser.GameObjects.Graphics;slots:Phaser.GameObjects.Graphics[];posicoesX:number[];fixos:number[]}

export const criarMiniJogoBalancaReino=(cena:Phaser.Scene,pai:Phaser.GameObjects.Container,desafio:InstanciaDesafio,aoResponder:(resposta:string[],bloco:Phaser.GameObjects.Container)=>boolean):{destruir:()=>void}=>{
    const dados=desafio.payload as unknown as DadosBalancaReino,pivoY=-60,estadoVisual={angulo:0},ocupacao:(Phaser.GameObjects.Container|undefined)[]=Array(dados.slots),estados=new Map<Phaser.GameObjects.Container,EstadoBloco>(),blocos:Phaser.GameObjects.Container[]=[];
    let concluido=false,tweenBalanca:Phaser.Tweens.Tween|undefined;
    pai.add(cena.add.text(0,-169,'Toque nos blocos até os dois lados ficarem com o mesmo peso.',{fontFamily:FONTE,fontSize:'15px',fontStyle:'bold',color:'#567068'}).setOrigin(.5));
    const pratoEsquerdo=criarPrato('left',dados.left,dados.dropSide==='left'?dados.slots:0),pratoDireito=criarPrato('right',dados.right,dados.dropSide==='right'?dados.slots:0),pratos:Record<Lado,Prato>={left:pratoEsquerdo,right:pratoDireito};
    const suporte=cena.add.graphics().setPosition(0,33),contorno=[new Phaser.Math.Vector2(-44,72),new Phaser.Math.Vector2(-20,-47),new Phaser.Math.Vector2(20,-47),new Phaser.Math.Vector2(44,72)];suporte.fillStyle(0x263b32,.2).fillEllipse(0,92,164,19).fillStyle(0x7f3e20).fillRoundedRect(-78,72,156,24,9).lineStyle(5,0x472215).strokeRoundedRect(-78,72,156,24,9).fillStyle(0x8f4924).fillPoints(contorno,true).lineStyle(6,0x512615).strokePoints(contorno,true).fillStyle(0xe9aa61,.28).fillTriangle(-26,64,-13,-35,2,-35).lineStyle(4,0x5e2d19,.6).lineBetween(-28,45,28,5).lineBetween(-23,65,34,21).fillStyle(0x718085).fillRoundedRect(-31,-51,62,15,5).lineStyle(4,0x30393d).strokeRoundedRect(-31,-51,62,15,5).fillStyle(0xefad5b,.7).fillRoundedRect(-63,77,126,5,3);const viga=cena.add.container(0,pivoY).setName('balanca-viga'),madeira=cena.add.graphics();madeira.fillStyle(0x3c2418,.28).fillRoundedRect(-231,-7,462,31,10).fillStyle(0x7a3c1d).fillRoundedRect(-232,-15,464,28,10).lineStyle(4,0x492413).strokeRoundedRect(-232,-15,464,28,10).fillStyle(0xc77a39).fillRoundedRect(-220,-11,440,7,4).lineStyle(3,0x29373b).strokeCircle(-212,0,7).strokeCircle(212,0,7).fillStyle(0xd1dad8).fillCircle(-212,0,4).fillCircle(212,0,4);for(const x of [-155,-82,82,155])madeira.fillStyle(0xe0ae58).fillCircle(x,0,3);viga.add(madeira);
    const eixo=cena.add.graphics().fillStyle(0x29363a).fillCircle(0,pivoY,22).lineStyle(5,0xc69b4e).strokeCircle(0,pivoY,22).fillStyle(0xcbd3d2).fillCircle(0,pivoY,12).fillStyle(0x6f3b21).fillCircle(0,pivoY,6);
    pai.add([pratoEsquerdo.grupo,pratoDireito.grupo,suporte,viga,eixo]);
    const status=cena.add.text(0,114,'TOQUE EM UM BLOCO PARA COLOCÁ-LO NO ESPAÇO VAZIO',{fontFamily:FONTE,fontSize:'11px',fontStyle:'bold',color:'#7b674c'}).setOrigin(.5),totalOpcoes=desafio.options.length,espaco=82,inicio=-(totalOpcoes-1)*espaco/2;pai.add(status);
    desafio.options.forEach((opcao,i)=>{const bloco=criarBloco(Number(opcao),true).setPosition(inicio+i*espaco,177).setScrollFactor(0),estado:EstadoBloco={valor:Number(opcao),origemX:bloco.x,origemY:bloco.y,arrastando:false,inicioX:0,inicioY:0};estados.set(bloco,estado);blocos.push(bloco);pai.add(bloco);cena.input.setDraggable(bloco);bloco.on('pointerdown',(pointer:Phaser.Input.Pointer)=>{estado.inicioX=pointer.x;estado.inicioY=pointer.y;});bloco.on('pointerup',(pointer:Phaser.Input.Pointer)=>{if(concluido||estado.arrastando||Phaser.Math.Distance.Between(pointer.x,pointer.y,estado.inicioX,estado.inicioY)>12)return;if(estado.slotInicial!==undefined)voltar(bloco);else encaixar(bloco);estado.slotInicial=undefined;});bloco.on('dragstart',()=>{if(concluido)return;estado.arrastando=true;estado.slotInicial=estado.slot;if(estado.slot!==undefined)removerDoPrato(bloco);pai.bringToTop(bloco);cena.tweens.add({targets:bloco,scale:1.1,duration:100,ease:'Back.Out'});});bloco.on('drag',(_pointer:Phaser.Input.Pointer,x:number,y:number)=>{if(!concluido)bloco.setPosition(x,y);});bloco.on('dragenter',(_pointer:Phaser.Input.Pointer,zona:Phaser.GameObjects.Zone)=>{if(zona===pratos[dados.dropSide].zona)destacarPrato(true);});bloco.on('dragleave',()=>destacarPrato(false));bloco.on('drop',(_pointer:Phaser.Input.Pointer,zona:Phaser.GameObjects.Zone)=>{destacarPrato(false);if(zona===pratos[dados.dropSide].zona)encaixar(bloco);});bloco.on('dragend',(pointer:Phaser.Input.Pointer,_x:number,_y:number,solto:boolean)=>{estado.arrastando=false;cena.tweens.add({targets:bloco,scale:1,duration:100});if(!solto&&estado.slot===undefined&&Phaser.Math.Distance.Between(pointer.x,pointer.y,estado.inicioX,estado.inicioY)>12)voltar(bloco);if(solto||Phaser.Math.Distance.Between(pointer.x,pointer.y,estado.inicioX,estado.inicioY)>12)cena.time.delayedCall(0,()=>estado.slotInicial=undefined);});});
    aplicarGeometria();atualizarBalanca(false);

    function criarPrato(_lado:Lado,fixos:number[],quantidadeSlots:number):Prato {
        const grupo=cena.add.container().setName(`balanca-prato-${_lado}`),g=cena.add.graphics(),largura=190;
        g.lineStyle(4,0x667579);for(const x of [-72,72])for(let y=4;y<COMPRIMENTO_CORRENTE-8;y+=9)g.strokeEllipse(x,y,8,12);
        g.fillStyle(0x28383c,.2).fillEllipse(0,COMPRIMENTO_CORRENTE+10,largura,18).fillStyle(0x9b612f).fillRoundedRect(-largura/2,COMPRIMENTO_CORRENTE-3,largura,19,7).lineStyle(4,0x50301e).strokeRoundedRect(-largura/2,COMPRIMENTO_CORRENTE-3,largura,19,7).fillStyle(0xe2a454).fillRoundedRect(-largura/2+8,COMPRIMENTO_CORRENTE,largura-16,5,3).lineStyle(3,0x9da9a9).lineBetween(-82,COMPRIMENTO_CORRENTE-3,-72,COMPRIMENTO_CORRENTE-16).lineBetween(82,COMPRIMENTO_CORRENTE-3,72,COMPRIMENTO_CORRENTE-16);
        const realce=cena.add.graphics().fillStyle(0xffdc75,.22).fillRoundedRect(-99,COMPRIMENTO_CORRENTE-74,198,82,16).lineStyle(4,0xffcf55,.8).strokeRoundedRect(-99,COMPRIMENTO_CORRENTE-74,198,82,16).setAlpha(0);grupo.add([g,realce]);
        const total=fixos.length+quantidadeSlots,passo=60,posicoesX=Array.from({length:total},(_,i)=>(i-(total-1)/2)*passo),slots:Phaser.GameObjects.Graphics[]=[];
        fixos.forEach((valor,i)=>grupo.add(criarBloco(valor,false).setPosition(posicoesX[i],COMPRIMENTO_CORRENTE-34)));
        for(let i=0;i<quantidadeSlots;i++){const x=posicoesX[fixos.length+i],slot=cena.add.graphics().fillStyle(0xfff0bd,.14).fillRoundedRect(-TAMANHO_BLOCO/2,-TAMANHO_BLOCO/2,TAMANHO_BLOCO,TAMANHO_BLOCO,12).lineStyle(3,0xe2bb64,.75).strokeRoundedRect(-TAMANHO_BLOCO/2,-TAMANHO_BLOCO/2,TAMANHO_BLOCO,TAMANHO_BLOCO,12).fillStyle(0xe2bb64,.55).fillCircle(0,0,4).setPosition(x,COMPRIMENTO_CORRENTE-34);slots.push(slot);grupo.add(slot);}
        const zona=cena.add.zone(0,COMPRIMENTO_CORRENTE-34,200,86).setName(`balanca-drop-${_lado}`).setRectangleDropZone(200,86).setScrollFactor(0);grupo.add(zona);return {grupo,zona,realce,slots,posicoesX,fixos};
    }
    function criarBloco(valor:number,interativo:boolean):Phaser.GameObjects.Container {const c=cena.add.container().setName(`balanca-bloco-${interativo?'movel':'fixo'}-${valor}`).setSize(TAMANHO_BLOCO,TAMANHO_BLOCO),g=cena.add.graphics();g.fillStyle(0x2e261f,.22).fillRoundedRect(-29,-25,58,62,12).fillStyle(interativo?0xb96b32:0x8d5932).fillRoundedRect(-31,-31,62,62,12).lineStyle(4,0x58311d).strokeRoundedRect(-31,-31,62,62,12).fillStyle(interativo?0xe49a4d:0xc4864b).fillRoundedRect(-25,-25,50,10,6).lineStyle(2,0xffd98a,.55).strokeRoundedRect(-24,-24,48,48,8);for(const [x,y] of [[-22,-22],[22,-22],[-22,22],[22,22]])g.fillStyle(0xd9c08b).fillCircle(x,y,2.5);c.add([g,cena.add.text(0,1,String(valor),{fontFamily:FONTE,fontSize:'25px',fontStyle:'bold',color:'#fff8d9',stroke:'#59331e',strokeThickness:4}).setOrigin(.5)]);if(interativo)c.setInteractive({useHandCursor:true});return c;}
    function pesos():{left:number;right:number}{const soma=(itens:number[])=>itens.reduce((a,b)=>a+b,0),adicionados=ocupacao.filter((item):item is Phaser.GameObjects.Container=>!!item).map(item=>estados.get(item)!.valor);return {left:soma(dados.left)+(dados.dropSide==='left'?soma(adicionados):0),right:soma(dados.right)+(dados.dropSide==='right'?soma(adicionados):0)};}
    function atualizarBalanca(animar=true):void {const peso=pesos(),delta=peso.right-peso.left,alvo=Phaser.Math.Clamp(delta*2.2,-ANGULO_MAXIMO,ANGULO_MAXIMO);tweenBalanca?.stop();if(!animar){estadoVisual.angulo=alvo;aplicarGeometria();return;}tweenBalanca=cena.tweens.add({targets:estadoVisual,angulo:alvo,duration:430,ease:'Sine.Out',onUpdate:aplicarGeometria,onComplete:()=>{if(delta===0&&ocupacao.filter(Boolean).length===dados.slots&&!concluido){concluido=true;status.setText('EQUILÍBRIO!').setColor('#3b9870');cena.tweens.add({targets:estadoVisual,angulo:1.15,duration:85,yoyo:true,repeat:1,ease:'Sine.InOut',onUpdate:aplicarGeometria,onComplete:()=>{estadoVisual.angulo=0;aplicarGeometria();const ultimo=ocupacao.filter((item):item is Phaser.GameObjects.Container=>!!item).slice(-1)[0];aoResponder(ocupacao.filter((item):item is Phaser.GameObjects.Container=>!!item).map(item=>String(estados.get(item)!.valor)),ultimo);}});}else if(ocupacao.filter(Boolean).length===dados.slots)status.setText('AINDA NÃO EQUILIBROU — TOQUE NO BLOCO PARA TROCAR').setColor('#a76a3e');else status.setText('TOQUE NO BLOCO PARA COLOCAR NA BALANÇA').setColor('#7b674c');}});}
    function aplicarGeometria():void {const rad=Phaser.Math.DegToRad(estadoVisual.angulo),cos=Math.cos(rad),sin=Math.sin(rad);viga.setAngle(estadoVisual.angulo);const posicoes:Record<Lado,{x:number;y:number}>={left:{x:-MEIA_VIGA*cos,y:pivoY-MEIA_VIGA*sin},right:{x:MEIA_VIGA*cos,y:pivoY+MEIA_VIGA*sin}};(['left','right'] as Lado[]).forEach(lado=>{const prato=pratos[lado],p=posicoes[lado];prato.grupo.setPosition(p.x,p.y);if(lado===dados.dropSide)ocupacao.forEach((bloco,i)=>{if(!bloco||estados.get(bloco)?.arrastando)return;bloco.setPosition(p.x+prato.posicoesX[prato.fixos.length+i],p.y+COMPRIMENTO_CORRENTE-34);});});}
    function encaixar(bloco:Phaser.GameObjects.Container):void {const estado=estados.get(bloco)!;if(estado.slot!==undefined||concluido)return;const slot=ocupacao.findIndex(item=>!item);if(slot<0){voltar(bloco);return;}ocupacao[slot]=bloco;estado.slot=slot;pratos[dados.dropSide].slots[slot].setAlpha(0);const prato=pratos[dados.dropSide],alvoX=prato.grupo.x+prato.posicoesX[prato.fixos.length+slot],alvoY=prato.grupo.y+COMPRIMENTO_CORRENTE-34;cena.tweens.add({targets:bloco,x:alvoX,y:alvoY,scale:1,duration:170,ease:'Back.Out',onComplete:()=>atualizarBalanca()});}
    function removerDoPrato(bloco:Phaser.GameObjects.Container):void {const estado=estados.get(bloco)!;if(estado.slot===undefined)return;const slot=estado.slot;ocupacao[slot]=undefined;estado.slot=undefined;pratos[dados.dropSide].slots[slot].setAlpha(1);atualizarBalanca();}
    function voltar(bloco:Phaser.GameObjects.Container):void {const estado=estados.get(bloco)!;cena.tweens.add({targets:bloco,x:estado.origemX,y:estado.origemY,scale:1,duration:230,ease:'Back.Out'});}
    function destacarPrato(ativo:boolean):void {pratos[dados.dropSide].realce.setAlpha(ativo?.95:0);}
    return {destruir:()=>{tweenBalanca?.stop();blocos.forEach(bloco=>cena.input.setDraggable(bloco,false));}};
};
