import * as Phaser from 'phaser';
import type { DadosBalancaReino, InstanciaDesafio } from './DesafiosReino';
import { barraRaster, circuloRaster, linhaRaster, painelRaster } from './ArteRaster';

const FONTE='Arial Rounded MT Bold, Arial Black, Arial',TAMANHO_BLOCO=62,MEIA_VIGA=218,COMPRIMENTO_CORRENTE=72,ANGULO_MAXIMO=10;
type Lado='left'|'right';
interface EstadoBloco {valor:number;origemX:number;origemY:number;slot?:number;slotInicial?:number;arrastando:boolean;inicioX:number;inicioY:number}
interface Prato {grupo:Phaser.GameObjects.Container;zona:Phaser.GameObjects.Zone;realce:Phaser.GameObjects.NineSlice;slots:Phaser.GameObjects.NineSlice[];posicoesX:number[];fixos:number[]}

export const criarMiniJogoBalancaReino=(cena:Phaser.Scene,pai:Phaser.GameObjects.Container,desafio:InstanciaDesafio,aoResponder:(resposta:string[],bloco:Phaser.GameObjects.Container)=>boolean):{destruir:()=>void}=>{
    const dados=desafio.payload as unknown as DadosBalancaReino,pivoY=-60,estadoVisual={angulo:0},ocupacao:(Phaser.GameObjects.Container|undefined)[]=Array(dados.slots),estados=new Map<Phaser.GameObjects.Container,EstadoBloco>(),blocos:Phaser.GameObjects.Container[]=[];
    let concluido=false,tweenBalanca:Phaser.Tweens.Tween|undefined;
    pai.add(cena.add.text(0,-169,'Toque nos blocos até os dois lados ficarem com o mesmo peso.',{fontFamily:FONTE,fontSize:'15px',fontStyle:'bold',color:'#567068'}).setOrigin(.5));
    const pratoEsquerdo=criarPrato('left',dados.left,dados.dropSide==='left'?dados.slots:0),pratoDireito=criarPrato('right',dados.right,dados.dropSide==='right'?dados.slots:0),pratos:Record<Lado,Prato>={left:pratoEsquerdo,right:pratoDireito};
    const suporte=cena.add.container(0,33,[circuloRaster(cena,0,92,82,0x263b32,.2).setScale(2,.23),painelRaster(cena,0,84,156,24,0x7f3e20),barraRaster(cena,0,15,46,125,0x8f4924),painelRaster(cena,0,-44,62,15,0x718085)]),viga=cena.add.container(0,pivoY).setName('balanca-viga');viga.add([painelRaster(cena,0,3,462,31,0x3c2418,.28),painelRaster(cena,0,-1,464,28,0x7a3c1d),barraRaster(cena,0,-7,440,7,0xc77a39),circuloRaster(cena,-212,0,14,0x29373b),circuloRaster(cena,212,0,14,0x29373b)]);
    const eixo=cena.add.container(0,pivoY,[circuloRaster(cena,0,0,50,0xc69b4e),circuloRaster(cena,0,0,44,0x29363a),circuloRaster(cena,0,0,24,0xcbd3d2),circuloRaster(cena,0,0,12,0x6f3b21)]);
    pai.add([pratoEsquerdo.grupo,pratoDireito.grupo,suporte,viga,eixo]);
    const status=cena.add.text(0,114,'TOQUE EM UM BLOCO PARA COLOCÁ-LO NO ESPAÇO VAZIO',{fontFamily:FONTE,fontSize:'11px',fontStyle:'bold',color:'#7b674c'}).setOrigin(.5),totalOpcoes=desafio.options.length,espaco=82,inicio=-(totalOpcoes-1)*espaco/2;pai.add(status);
    desafio.options.forEach((opcao,i)=>{const bloco=criarBloco(Number(opcao),true).setPosition(inicio+i*espaco,177).setScrollFactor(0),estado:EstadoBloco={valor:Number(opcao),origemX:bloco.x,origemY:bloco.y,arrastando:false,inicioX:0,inicioY:0};estados.set(bloco,estado);blocos.push(bloco);pai.add(bloco);cena.input.setDraggable(bloco);bloco.on('pointerdown',(pointer:Phaser.Input.Pointer)=>{estado.inicioX=pointer.x;estado.inicioY=pointer.y;});bloco.on('pointerup',(pointer:Phaser.Input.Pointer)=>{if(concluido||estado.arrastando||Phaser.Math.Distance.Between(pointer.x,pointer.y,estado.inicioX,estado.inicioY)>12)return;if(estado.slotInicial!==undefined)voltar(bloco);else encaixar(bloco);estado.slotInicial=undefined;});bloco.on('dragstart',()=>{if(concluido)return;estado.arrastando=true;estado.slotInicial=estado.slot;if(estado.slot!==undefined)removerDoPrato(bloco);pai.bringToTop(bloco);cena.tweens.add({targets:bloco,scale:1.1,duration:100,ease:'Back.Out'});});bloco.on('drag',(_pointer:Phaser.Input.Pointer,x:number,y:number)=>{if(!concluido)bloco.setPosition(x,y);});bloco.on('dragenter',(_pointer:Phaser.Input.Pointer,zona:Phaser.GameObjects.Zone)=>{if(zona===pratos[dados.dropSide].zona)destacarPrato(true);});bloco.on('dragleave',()=>destacarPrato(false));bloco.on('drop',(_pointer:Phaser.Input.Pointer,zona:Phaser.GameObjects.Zone)=>{destacarPrato(false);if(zona===pratos[dados.dropSide].zona)encaixar(bloco);});bloco.on('dragend',(pointer:Phaser.Input.Pointer,_x:number,_y:number,solto:boolean)=>{estado.arrastando=false;cena.tweens.add({targets:bloco,scale:1,duration:100});if(!solto&&estado.slot===undefined&&Phaser.Math.Distance.Between(pointer.x,pointer.y,estado.inicioX,estado.inicioY)>12)voltar(bloco);if(solto||Phaser.Math.Distance.Between(pointer.x,pointer.y,estado.inicioX,estado.inicioY)>12)cena.time.delayedCall(0,()=>estado.slotInicial=undefined);});});
    aplicarGeometria();atualizarBalanca(false);

    function criarPrato(_lado:Lado,fixos:number[],quantidadeSlots:number):Prato {
        const grupo=cena.add.container().setName(`balanca-prato-${_lado}`),largura=190;[-72,72].forEach(x=>grupo.add(linhaRaster(cena,x,4,x,COMPRIMENTO_CORRENTE-16,4,0x667579)));grupo.add([painelRaster(cena,0,COMPRIMENTO_CORRENTE+10,largura,18,0x28383c,.2),painelRaster(cena,0,COMPRIMENTO_CORRENTE+6,largura,19,0x9b612f),barraRaster(cena,0,COMPRIMENTO_CORRENTE+2,largura-16,5,0xe2a454)]);
        const realce=painelRaster(cena,0,COMPRIMENTO_CORRENTE-33,198,82,0xffcf55,.8).setAlpha(0);grupo.add(realce);
        const total=fixos.length+quantidadeSlots,passo=60,posicoesX=Array.from({length:total},(_,i)=>(i-(total-1)/2)*passo),slots:Phaser.GameObjects.NineSlice[]=[];
        fixos.forEach((valor,i)=>grupo.add(criarBloco(valor,false).setPosition(posicoesX[i],COMPRIMENTO_CORRENTE-34)));
        for(let i=0;i<quantidadeSlots;i++){const x=posicoesX[fixos.length+i],slot=painelRaster(cena,x,COMPRIMENTO_CORRENTE-34,TAMANHO_BLOCO,TAMANHO_BLOCO,0xe2bb64,.35);slots.push(slot);grupo.add(slot);}
        const zona=cena.add.zone(0,COMPRIMENTO_CORRENTE-34,200,86).setName(`balanca-drop-${_lado}`).setRectangleDropZone(200,86).setScrollFactor(0);grupo.add(zona);return {grupo,zona,realce,slots,posicoesX,fixos};
    }
    function criarBloco(valor:number,interativo:boolean):Phaser.GameObjects.Container {const c=cena.add.container().setName(`balanca-bloco-${interativo?'movel':'fixo'}-${valor}`).setSize(TAMANHO_BLOCO,TAMANHO_BLOCO);c.add([painelRaster(cena,0,6,58,62,0x2e261f,.22),painelRaster(cena,0,0,66,66,0x58311d),painelRaster(cena,0,0,62,62,interativo?0xb96b32:0x8d5932),painelRaster(cena,0,-20,50,10,interativo?0xe49a4d:0xc4864b),cena.add.text(0,1,String(valor),{fontFamily:FONTE,fontSize:'25px',fontStyle:'bold',color:'#fff8d9',stroke:'#59331e',strokeThickness:4}).setOrigin(.5)]);if(interativo)c.setInteractive({useHandCursor:true});return c;}
    function pesos():{left:number;right:number}{const soma=(itens:number[])=>itens.reduce((a,b)=>a+b,0),adicionados=ocupacao.filter((item):item is Phaser.GameObjects.Container=>!!item).map(item=>estados.get(item)!.valor);return {left:soma(dados.left)+(dados.dropSide==='left'?soma(adicionados):0),right:soma(dados.right)+(dados.dropSide==='right'?soma(adicionados):0)};}
    function atualizarBalanca(animar=true):void {const peso=pesos(),delta=peso.right-peso.left,alvo=Phaser.Math.Clamp(delta*2.2,-ANGULO_MAXIMO,ANGULO_MAXIMO);tweenBalanca?.stop();if(!animar){estadoVisual.angulo=alvo;aplicarGeometria();return;}tweenBalanca=cena.tweens.add({targets:estadoVisual,angulo:alvo,duration:430,ease:'Sine.Out',onUpdate:aplicarGeometria,onComplete:()=>{if(delta===0&&ocupacao.filter(Boolean).length===dados.slots&&!concluido){concluido=true;status.setText('EQUILÍBRIO!').setColor('#3b9870');cena.tweens.add({targets:estadoVisual,angulo:1.15,duration:85,yoyo:true,repeat:1,ease:'Sine.InOut',onUpdate:aplicarGeometria,onComplete:()=>{estadoVisual.angulo=0;aplicarGeometria();const ultimo=ocupacao.filter((item):item is Phaser.GameObjects.Container=>!!item).slice(-1)[0];aoResponder(ocupacao.filter((item):item is Phaser.GameObjects.Container=>!!item).map(item=>String(estados.get(item)!.valor)),ultimo);}});}else if(ocupacao.filter(Boolean).length===dados.slots)status.setText('AINDA NÃO EQUILIBROU — TOQUE NO BLOCO PARA TROCAR').setColor('#a76a3e');else status.setText('TOQUE NO BLOCO PARA COLOCAR NA BALANÇA').setColor('#7b674c');}});}
    function aplicarGeometria():void {const rad=Phaser.Math.DegToRad(estadoVisual.angulo),cos=Math.cos(rad),sin=Math.sin(rad);viga.setAngle(estadoVisual.angulo);const posicoes:Record<Lado,{x:number;y:number}>={left:{x:-MEIA_VIGA*cos,y:pivoY-MEIA_VIGA*sin},right:{x:MEIA_VIGA*cos,y:pivoY+MEIA_VIGA*sin}};(['left','right'] as Lado[]).forEach(lado=>{const prato=pratos[lado],p=posicoes[lado];prato.grupo.setPosition(p.x,p.y);if(lado===dados.dropSide)ocupacao.forEach((bloco,i)=>{if(!bloco||estados.get(bloco)?.arrastando)return;bloco.setPosition(p.x+prato.posicoesX[prato.fixos.length+i],p.y+COMPRIMENTO_CORRENTE-34);});});}
    function encaixar(bloco:Phaser.GameObjects.Container):void {const estado=estados.get(bloco)!;if(estado.slot!==undefined||concluido)return;const slot=ocupacao.findIndex(item=>!item);if(slot<0){voltar(bloco);return;}ocupacao[slot]=bloco;estado.slot=slot;pratos[dados.dropSide].slots[slot].setAlpha(0);const prato=pratos[dados.dropSide],alvoX=prato.grupo.x+prato.posicoesX[prato.fixos.length+slot],alvoY=prato.grupo.y+COMPRIMENTO_CORRENTE-34;cena.tweens.add({targets:bloco,x:alvoX,y:alvoY,scale:1,duration:170,ease:'Back.Out',onComplete:()=>atualizarBalanca()});}
    function removerDoPrato(bloco:Phaser.GameObjects.Container):void {const estado=estados.get(bloco)!;if(estado.slot===undefined)return;const slot=estado.slot;ocupacao[slot]=undefined;estado.slot=undefined;pratos[dados.dropSide].slots[slot].setAlpha(1);atualizarBalanca();}
    function voltar(bloco:Phaser.GameObjects.Container):void {const estado=estados.get(bloco)!;cena.tweens.add({targets:bloco,x:estado.origemX,y:estado.origemY,scale:1,duration:230,ease:'Back.Out'});}
    function destacarPrato(ativo:boolean):void {pratos[dados.dropSide].realce.setAlpha(ativo?.95:0);}
    return {destruir:()=>{tweenBalanca?.stop();blocos.forEach(bloco=>cena.input.setDraggable(bloco,false));}};
};
